<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php if (FALSE) : ?>
    <script type="text/javascript">
<?php endif; ?>
    
    elgg.provide('elgg.wine_edit');

    elgg.wine_edit.init = function() {
 	$(function() {
                            
                            
                            
                            
                            
                var array_fr = [];
                var array_es = [];
                var array_it = [];
                var array_us = [];
                
array_us[0] = [

"Alexander Valley",
"Alta Mesa",
"Anderson Valley",
"Applegate Valley",
"Arroyo Grande Valley",
"Arroyo Seco",
"Atlas Peak",
"Ben Lomond Mountain",
"Benmore Valley",
"Bennett Valley",
"Borden Ranch",
"California Shenandoah Valley",
"Capay Valley",
"Carmel Valley",
"Catoctin",
"Cayuga Lake",
"Central Coast",
"Central Delaware Valley",
"Chalk Hill",
"Chalone",
"Chehalem Mountains",
"Chiles Valley",
"Cienega Valley",
"Clarksburg",
"Clear Lake",
"Clements Hills",
"Cole Ranch",
"Columbia Gorge",
"Columbia Valley",
"Cosumnes River",
"Covelo",
"Cucamonga Valley",
"Cumberland Valley",
"Diablo Grande",
"Diamond Mountain District",
"Dos Rios",
"Dry Creek Valley",
"Dundee Hills",
"Dunnigan Hills",
"Edna Valley",
"El Dorado",
"Eola-Amity Hills",
"Fair Play",
"Fiddletown",
"Finger Lakes",
"Green Valley of Russian River Valley",
"Guenoc Valley",
"Hames Valley",
"High Valley",
"Horse Heaven Hills",
"Howell Mountain",
"Hudson River Region",
"Jahant",
"Knights Valley",
"Lake Erie",
"Lancaster Valley",
"Lime Kiln Valley",
"Linganore",
"Livermore Valley",
"Lodi",
"Long Island",
"Los Carneros",
"Madera",
"Malibu-Newton Canyon",
"Martha's Vineyard",
"McDowell Valley",
"McMinnville",
"Mendocino",
"Mendocino Ridge",
"Merritt Island",
"Mokelumne River",
"Monterey",
"Monticello",
"Mt. Harlan",
"Mt. Veeder",
"Napa Valley",
"Niagara Escarpment",
"North Coast",
"North Fork of Long Island",
"North Fork of Roanoke",
"North Yuba",
"Northern Neck George Washington Birthplace",
"Northern Sonoma",
"Oak Knoll District",
"Oakville",
"Outer Coastal Plain",
"Pacheco Pass",
"Paicines",
"Paso Robles",
"Potter Valley",
"Puget Sound",
"Ramona Valley",
"Rattlesnake Hills",
"Red Hill Douglas County",
"Red Hills Lake County",
"Red Mountain",
"Redwood Valley",
"Ribbon Ridge",
"River Junction",
"Rockpile",
"Rocky Knob",
"Rogue Valley",
"Russian River Valley",
"Rutherford",
"Saddle Rock - Malibu",
"Salado Creek",
"San Antonio Valley",
"San Benito",
"San Bernabe",
"San Francisco Bay",
"San Lucas",
"San Pasqual Valley",
"San Ysidro District",
"Santa Clara Valley",
"Santa Cruz Mountains",
"Santa Lucia Highlands",
"Santa Maria Valley",
"Santa Ynez Valley",
"Seiad Valley",
"Seneca Lake",
"Shenandoah Valley",
"Sierra Foothills",
"Sloughhouse",
"Solano County Green Valley",
"Sonoma Coast",
"Sonoma Mountain",
"Sonoma Valley",
"South Coast",
"Southeastern New England",
"Southern Oregon",
"Spring Mountain District",
"St. Helena",
"Sta. Rita Hills",
"Stags Leap District",
"Suisun Valley",
"Temecula Valley",
"The Hamptons",
"Tracy Hills",
"Trinity Lakes",
"Umpqua Valley",
"Virginia's Eastern Shore",
"Wahluke Slope",
"Walla Walla Valley",
"Warren Hills",
"Western Connecticut Highlands",
"Wild Horse Valley",
"Willamette Valley",
"Willow Creek",
"Yadkin Valley",
"Yakima Valley",
"Yamhill-Carlton District",
"York Mountain",
"Yorkville Highlands",
"Yountville"
    
    
];

array_us[1] = [
    

"California",
"California",
"California",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"Maryland",
"New York",
"California",
"New Jersey",
"California",
"California",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"Oregon",
"Oregon",
"California",
"California",
"California",
"Maryland",
"California",
"California",
"California",
"California",
"Oregon",
"California",
"California",
"California",
"Oregon",
"California",
"California",
"New York",
"California",
"California",
"California",
"California",
"Washington",
"California",
"New York",
"California",
"California",
"New York",
"Pennsylvanie",
"California",
"Maryland",
"California",
"California",
"New York",
"California",
"California",
"California",
"Massachusetts",
"California",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"Virginie",
"California",
"California",
"California",
"New York",
"California",
"New York",
"Virginie",
"California",
"Virginie",
"California",
"California",
"California",
"New Jersey",
"California",
"California",
"California",
"California",
"Washington",
"California",
"Washington",
"Oregon",
"California",
"Washington",
"California",
"Oregon",
"California",
"California",
"Virginie",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"New York",
"Virginie",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"Connecticut",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"Long Island",
"California",
"California",
"Oregon",
"Virginie",
"Washington",
"Washington",
"New Jersey",
"Connecticut",
"California",
"Oregon",
"California",
"Caroline du Nord",
"Oregon",
"Oregon",
"California",
"California",
"California",
    
];



array_it[0] = [
"Abruzzo",
"Aglianico del Taburno",
"Aglianico del Taburno",
"Aglianico del Vulture",
"Aglianico del Vulture Superiore",
"Albana di Romagna",
"Albugnano",
"Alcamo",
"Aleatico di Gradoli",
"Aleatico di Puglia",
"Alezio",
"Alghero",
"Alta Langa",
"Alta Langa",
"Amarone della Valpolicella",
"Amelia",
"Ansonica Costa dell'Argentario",
"Aprilia",
"Arborea",
"Arcole",
"Asolo Prosecco",
"Assisi",
"Asti",
"Atina",
"Aversa Asprinio",
"Bagnoli di Sopra",
"Barbaresco",
"Barbera d'Alba",
"Barbera d'Asti",
"Barbera d'Asti",
"Barbera del Monferrato",
"Barbera del Monferrato Superiore",
"Barco Reale di Carmignano",
"Bardolino",
"Bardolino Superiore",
"Barletta",
"Barolo",
"Bianchello del Metauro",
"Bianco Capena",
"Bianco dell'Empolese",
"Bianco della Valdinievole",
"Bianco di Custoza",
"Bianco di Pitigliano",
"Bianco Pisano di San Torpe",
"Bianco Vergine della Valdichiana",
"Biferno",
"Bivongi",
"Boca",
"Bolgheri",
"Bonarda dell'Otrepo Pavese",
"Bosco Eliceo",
"Botticino",
"Brachetto d'Acqui or Acqui",
"Bramaterra",
"Breganze",
"Brindisi",
"Brunello di Montalcino",
"Buttafuoco dell'Oltrepo Pavese",
"Cacc'e mmitte di Lucera",
"Cagnina di Romagna",
"Caldaro",
"Calosso",
"Campi Flegrei",
"Campidano di Terralba",
"Canavese",
"Candia dei Colli Apuani",
"Canellino di Frascati",
"Cannonau di Sardegna",
"Capalbio",
"Capri",
"Capriano del Colle",
"Carema",
"Carignano del Sulcis",
"Carmignano",
"Carso",
"Casteggio",
"Castel del Monte",
"Castel del Monte Bombino Nero",
"Castel del Monte Nero di Troia Reserva",
"Castel del Monte Rosso Riserva",
"Castel San Lorenzo",
"Casteller",
"Castelli di Jesi Verdicchio Riserva",
"Castelli Romani",
"Cellatica",
"Cerasuolo d'Abruzzo",
"Cerasuolo di Vittoria",
"Cerveteri",
"Cesanese del Piglio",
"Cesanese del Piglio or Piglio",
"Cesanese di Affile",
"Cesanese di Olevano Romano",
"Chianti",
"Chianti Superiore",
"Cilento",
"Cinque Terre",
"Cinque Terre Sciacchetra",
"Circeo",
"Ciro",
"Cisterna d'Asti",
"Classico",
"Colli Albani",
"Colli Altotiberini",
"Colli Amerini",
"Colli Aretini",
"Colli Asolani Prosecco",
"Colli Astiani in the region surrounding Vigliano d'Asti",
"Colli Berici",
"Colli Bolognesi",
"Colli Bolognesi",
"Colli Bolognesi Classico Pignoletto",
"Colli del Trasimeno",
"Colli dell'Etruria Centrale",
"Colli della Sabina",
"Colli di Conegliano",
"Colli di Conegliano",
"Colli di Faenza",
"Colli di Imola",
"Colli di Luni",
"Colli di Luni",
"Colli di Parma",
"Colli di Rimini",
"Colli di Scandiano e di Canossa",
"Colli Etruschi Viterbesi",
"Colli Euganei",
"Colli Euganei Fior d'Arancio",
"Colli Fiorentini",
"Colli Lanuvini",
"Colli Maceratesi",
"Colli Martani",
"Colli Orientali del Friuli",
"Colli Orientali del Friuli Cialla",
"Colli Orientali del Friuli Picolit",
"Colli Orientali del Friuli Rosazzo",
"Colli Perugini",
"Colli Pesaresi",
"Colli Piacentini",
"Colli Romagna Centrale",
"Colli Senesi",
"Colli Tortonesi",
"Collina Torinese",
"Colline di Levanto",
"Colline Joniche Taratine",
"Colline Lucchesi",
"Colline Novaresi",
"Colline Pisane",
"Colline Saluzzesi",
"Collio",
"Conegliano Valdobbiadene",
"Conero",
"Contea di Sclafani",
"Contessa Entellina",
"Controguerra",
"Copertino",
"Cori",
"Cortese dell'Alto Monferrato",
"Corti Benedettine del Padovano",
"Cortona",
"Costa d'Amalfi",
"Coste della Sesia",
"Delia Nivolelli Nero d'Avola",
"Dolcetto d'Acqui",
"Dolcetto d'Alba",
"Dolcetto d'Asti",
"Dolcetto delle Langhe Monregalesi",
"Dolcetto di Diano d'Alba",
"Dolcetto di Diano d'Alba or Diano d'Alba",
"Dolcetto di Dogliani",
"Dolcetto di Dogliani Superiore or Dogliani",
"Dolcetto di Ovada",
"Dolcetto di Ovada Superiore or Ovada",
"Donnici",
"Elba",
"Eloro",
"Erbaluce di Caluso",
"Erbaluce di Caluso or Caluso",
"Erice",
"Esino",
"Est! Est!! Est!!! di Montefiascone",
"Etna",
"Falanghina del Sannio",
"Falerio dei Colli Ascolani",
"Falerno del Massico",
"Fara",
"Faro",
"Fiano di Avellino",
"Fior d'Arancio Colli Euganei",
"Franciacorta",
"Frascati",
"Frascati Superiore",
"Freisa d'Asti",
"Freisa di Chieri",
"Friuli Annia",
"Friuli Aquileia",
"Friuli Grave",
"Friuli Isonzo",
"Friuli Latisana",
"Gabiano",
"Galatina",
"Galluccio",
"Gambellara",
"Garda",
"Garda",
"Garda Colli Mantovani",
"Gattinara",
"Gavi or Cortese di Gavi",
"Genazzano",
"Ghemme",
"Gioia del Colle",
"Giro di Cagliari",
"Golfo del Tigullio",
"Gravina",
"Greco di Bianco",
"Greco di Tufo",
"Grignolino d'Asti",
"Grignolino del Monferrato Casalese",
"Guardiolo",
"Gutturnio",
"Irpina",
"Ischia",
"Kalterersee",
"Lacrima di Morro d'Alba",
"Lago di Caldaro",
"Lago di Corbara",
"Lambrusco di Sorbara",
"Lambrusco Grasparossa di Castelvetro",
"Lambrusco Mantovano",
"Lambrusco Salamino di Santacroce",
"Lamezia",
"Langhe",
"Lessona",
"Leverano",
"Lison Pramaggiore",
"Lison Pramaggiore",
"Lison-Pramaggiore",
"Lizzano",
"Loazzolo",
"Locorotondo",
"Lugana",
"Lugana",
"Malanotte Raboso Superiore",
"Malvasia delle Lipari",
"Malvasia di Bosa",
"Malvasia di Cagliari",
"Malvasia di Casorzo d'Asti",
"Malvasia di Castelnuovo Don Bosco",
"Mamertino di Milazzo",
"Mandrolisai",
"Maremma Toscana",
"Marino",
"Marsala",
"Martina",
"Matera",
"Matino",
"Melissa",
"Menfi",
"Merlara",
"Modena",
"Molise",
"Monferrato",
"Monica di Cagliari",
"Monica di Sardegna",
"Monreale",
"Montalbano",
"Montecarlo",
"Montecompatri Colonna",
"Montecucco",
"Montefalco",
"Montello",
"Montello e Colli Asolani",
"Montepulciano d'Abruzzo",
"Montepulciano d'Abruzzo",
"Monteregio di Massa Marittima",
"Montescudaio",
"Montespertoli",
"Monti Lessini",
"Morellino di Scansano",
"Morellino di Scansano",
"Moscadello di Montalcino",
"Moscato di Cagliari",
"Moscato di Pantelleria",
"Moscato di Sardegna",
"Moscato di Scanzo",
"Moscato di Siracusa",
"Moscato di Sorso Sennori",
"Moscato di Trani",
"Nardo",
"Nasco di Cagliari",
"Nebbiolo d'Alba",
"Negroamaro di Terra d'Otranto",
"Nettuno",
"Nizza in the region surrounding Nizza Monferrato",
"Noto",
"Nuragus di Cagliari",
"Offida",
"Offida",
"Oltrepo Pavese",
"Oltrepo Pavese Metodo Classico",
"Orcia",
"Orta Nova",
"Ortona",
"Ortrugo",
"Orvieto",
"Orvieto",
"Ostuni",
"Pagadebit di Romagna",
"Parrina",
"Penisola Sorrentina",
"Pentro di Isernia",
"Pergola",
"Piave",
"Piemonte",
"Piglio",
"Pinerolese",
"Pollino",
"Pomino",
"Pornassio",
"Primitivo di Manduria",
"Primitivo di Manduria Dolce Naturale",
"Prosecco",
"Prosecco",
"Ramandolo",
"Recioto della Valpolicella",
"Recioto di Gambellara",
"Recioto di Soave",
"Reggiano",
"Reno",
"Riesi",
"Riviera del Brenta",
"Riviera del Garda Bresciano",
"Riviera Ligure di Ponente",
"Roero",
"Roma",
"Romagna Albana Spumante (Bianco Spumante)",
"Rosazzo",
"Rossese di Dolceacqua",
"Rosso Barletta",
"Rosso Canosa",
"Rosso Conero",
"Rosso di Cerignola",
"Rosso di Montalcino",
"Rosso di Montepulciano",
"Rosso Orvietano",
"Rosso Piceno",
"Rubino di Cantavenna",
"Ruche di Castagnole Monferrato",
"Ruche di Castagnole Monferrato",
"Rufina",
"Sagrantino di Montefalco",
"Salaparuta",
"Salice Salentino",
"Sambuca di Sicilia",
"San Colombano al Lambro",
"San Gimignano",
"San Martino della Battaglia",
"San Martino della Battaglia",
"San Severo",
"San Vito di Luzzi",
"Sangiovese di Romagna",
"Sannio",
"Sant'Agata dei Goti",
"Sant'Anna di Isola Capo Rizzuto",
"Sant'Antimo",
"Santa Maddalena",
"Santa Margherita di Belice",
"Sardegna Semidano",
"Savuto",
"Scanzo",
"Scavigna",
"Sciacca",
"Sforzato di Valtellina or Sfurzat di Valtellina",
"Siracusa",
"Sizzano",
"Soave",
"Soave Superiore",
"Solopaca",
"Sovana",
"Spoleto",
"Squinzano",
"Sudtirol",
"Taburno",
"Tarquinia",
"Taurasi",
"Tavoliere",
"Tavoliere delle Puglie",
"Teroldego Rotaliano",
"Terra d'Otranto",
"Terracina or Moscato di Terracina",
"Terre dell'Alta Val d'Agri",
"Terre di Franciacorta",
"Terre Tollesi",
"Tinella in the region surrounding Costigliole d'Asti",
"Tintilia",
"Todi",
"Torgiano",
"Torgiano Rosso Riserva",
"Trebbiano d'Abruzzo",
"Trebbiano di Romagna",
"Trentino",
"Trento a sparkling wine",
"Tullum",
"Val d'Arbia",
"Val di Cornia",
"Val Polcevera",
"Valcalepio",
"Valdadige",
"Valdadige",
"Valdadige",
"Valle d'Aosta",
"Valpolicella",
"Valpolicella Ripasso",
"Valsusa",
"Valtellina Rosso",
"Valtellina Superiore",
"Valtenesi",
"Velletri",
"Venezia",
"Verbicaro",
"Verdicchio dei Castelli di Jesi",
"Verdicchio di Matelica",
"Verdicchio di Matelica Riserva",
"Verduno Pelaverga",
"Vermentino di Gallura",
"Vermentino di Sardegna",
"Vernaccia di Oristano",
"Vernaccia di San Gimignano",
"Vernaccia di Serrapetrona",
"Vesuvio",
"Vicenza",
"Vignanello",
"Villamagna",
"Vin Santo del Chianti",
"Vin Santo del Chianti Classico",
"Vin Santo di Gambellara",
"Vin Santo di Montepulciano",
"Vino Nobile di Montepulciano",
"Vittoria",
"Zagarolo"   
];


array_it[1] = [
"Abruzzo",
"Campania",
"Campania",
"Basilicata",
"Basilicata",
"Emilia Romagna",
"Piemonte",
"Sicilia",
"Lazio",
"Apulia",
"Apulia",
"Sardegna",
"Piemonte",
"Piedmont",
"Veneto",
"Umbria",
"Toscana",
"Lazio",
"Sardegna",
"Veneto",
"Veneto",
"Umbria",
"Piedmont",
"Lazio",
"Campania",
"Veneto",
"Piedmont",
"Piemonte",
"Piemonte",
"Piedmont",
"Piemonte",
"Piedmont",
"Toscana",
"Veneto",
"Veneto",
"Apulia",
"Piedmont",
"Marche",
"Lazio",
"Toscana",
"Toscana",
"Veneto",
"Toscana",
"Toscana",
"Toscana",
"Molise",
"Calabria",
"Piemonte",
"Toscana",
"Lombardia",
"Emilia-Romagna",
"Lombardia",
"Piedmont",
"Piemonte",
"Veneto",
"Apulia",
"Tuscany",
"Lombardia",
"Apulia",
"Emilia-Romagna",
"Trentino",
"Piemonte",
"Campania",
"Sardegna",
"Piemonte",
"Toscana",
"Lazio",
"Sardegna",
"Toscana",
"Campania",
"Lombardia",
"Piemonte",
"Sardegna",
"Tuscany",
"Friuli-Venezia Giulia",
"Lombardia",
"Apulia",
"Puglia",
"Puglia",
"Puglia",
"Campania",
"Trentino",
"Marche",
"Lazio",
"Lombardia",
"Abruzzo",
"Sicily",
"Lazio",
"Lazio",
"Lazio",
"Lazio",
"Lazio",
"Tuscany",
"Tuscany",
"Campania",
"Liguria",
"Liguria",
"Lazio",
"Calabria",
"Piemonte",
"Tuscany",
"Lazio",
"Umbria",
"Umbria",
"Tuscany",
"Veneto",
"Piedmont",
"Veneto",
"Emilia-Romagna",
"Emilia Romagna",
"Emilia-Romagna",
"Umbria",
"Toscana",
"Lazio",
"Veneto",
"Veneto",
"Emilia-Romagna",
"Emilia-Romagna",
"Liguria",
"Toscana",
"Emilia-Romagna",
"Emilia-Romagna",
"Emilia-Romagna",
"Lazio",
"Veneto",
"Veneto",
"Tuscany",
"Lazio",
"Marche",
"Umbria",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Umbria",
"Marche",
"Emilia-Romagna",
"Emilia-Romagna",
"Tuscany",
"Piemonte",
"Piemonte",
"Liguria",
"Apulia",
"Toscana",
"Piemonte",
"Tuscany",
"Piemonte",
"Friuli-Venezia Giulia",
"Veneto",
"Marche",
"Sicilia",
"Sicilia",
"Abruzzo",
"Apulia",
"Lazio",
"Piemonte",
"Veneto",
"Toscana",
"Campania",
"Piemonte",
"Sicilia",
"Piemonte",
"Piemonte",
"Piemonte",
"Piemonte",
"Piemonte",
"Piedmont",
"Piemonte",
"Piedmont",
"Piemonte",
"Piedmont",
"Calabria",
"Toscana",
"Sicilia",
"Piemonte",
"Piedmont",
"Sicilia",
"Marche",
"Lazio",
"Sicilia",
"Campania",
"Marche",
"Campania",
"Piemonte",
"Sicilia",
"Campania",
"Veneto",
"Lombardia",
"Lazio",
"Lazio",
"Piemonte",
"Piemonte",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Piemonte",
"Apulia",
"Campania",
"Veneto",
"Lombardia",
"Veneto",
"Lombardia",
"Piedmont",
"Piedmont",
"Lazio",
"Piedmont",
"Apulia",
"Sardegna",
"Liguria",
"Apulia",
"Calabria",
"Campania",
"Piemonte",
"Piemonte",
"Campania",
"Emilia-Romagna",
"Campania",
"Campania",
"South Tyrol",
"Marche",
"Trentino",
"Umbria",
"Emilia-Romagna",
"Emilia-Romagna",
"Lombardia",
"Emilia-Romagna",
"Calabria",
"Piemonte",
"Piemonte",
"Apulia",
"Friuli-Venezia Giulia",
"Veneto",
"Veneto",
"Apulia",
"Piemonte",
"Apulia",
"Lombardia",
"Veneto",
"Veneto",
"Sicilia",
"Sardegna",
"Sardegna",
"Piemonte",
"Piemonte",
"Sicilia",
"Sardegna",
"Toscana",
"Lazio",
"Sicilia",
"Apulia",
"Basilicata",
"Apulia",
"Calabria",
"Sicilia",
"Veneto",
"Emilia-Romagna",
"Molise",
"Piemonte",
"Sardegna",
"Sardegna",
"Sicilia",
"Tuscany",
"Toscana",
"Lazio",
"Toscana",
"Umbria",
"Veneto",
"Veneto",
"Abruzzo",
"Abruzzo",
"Toscana",
"Toscana",
"Tuscany",
"Veneto",
"Toscana",
"Tuscany",
"Toscana",
"Sardegna",
"Sicilia",
"Sardegna",
"Lombardia",
"Sicilia",
"Sardegna",
"Apulia",
"Apulia",
"Sardegna",
"Piemonte",
"Apulia",
"Lazio",
"Piedmont",
"Sicilia",
"Sardegna",
"Marche",
"Marche",
"Lombardia",
"Lombardia",
"Toscana",
"Apulia",
"Abruzzo",
"Emilia-Romagna",
"Lazio",
"Umbria",
"Apulia",
"Emilia-Romagna",
"Toscana",
"Campania",
"Molise",
"Marche",
"Veneto",
"Piemonte",
"Lazio",
"Piemonte",
"Calabria",
"Toscana",
"Liguria",
"Apulia",
"Puglia",
"Veneto",
"Veneto",
"Friuli-Venezia Giulia",
"Veneto",
"Veneto",
"Veneto",
"Emilia-Romagna",
"Emilia-Romagna",
"Sicilia",
"Veneto",
"Lombardia",
"Liguria",
"Piedmont",
"Lazio",
"Emilia-Romagna",
"Friuli-Venezia Giulia",
"Liguria",
"Apulia",
"Apulia",
"Marche",
"Apulia",
"Toscana",
"Toscana",
"Umbria",
"Marche",
"Piemonte",
"Piemonte",
"Piedmont",
"Tuscany",
"Umbria",
"Sicilia",
"Apulia",
"Sicilia",
"Lombardia",
"Toscana",
"Lombardia",
"Veneto",
"Apulia",
"Calabria",
"Emilia-Romagna",
"Campania",
"Campania",
"Calabria",
"Toscana",
"South Tyrol",
"Sicilia",
"Sardegna",
"Calabria",
"Lombardia",
"Calabria",
"Sicilia",
"Lombardia",
"Sicilia",
"Piemonte",
"Veneto",
"Veneto",
"Campania",
"Toscana",
"Umbria",
"Apulia",
"South Tyrol",
"Campania",
"Lazio",
"Campania",
"Apulia",
"Apulia",
"Trentino",
"Apulia",
"Lazio",
"Basilicata",
"Lombardia",
"Abruzzo",
"Piedmont",
"Molise",
"Umbria",
"Umbria",
"Umbria",
"Abruzzo",
"Emilia-Romagna",
"Trentino",
"Trentino",
"Abruzzo",
"Toscana",
"Toscana",
"Liguria",
"Lombardia",
"South Tyrol",
"Trentino",
"Veneto",
"Valle d'Aosta",
"Veneto",
"Veneto",
"Piemonte",
"Lombardia",
"Lombardia",
"Lombardia",
"Lazio",
"Veneto",
"Calabria",
"Marche",
"Marche",
"Marche",
"Piemonte",
"Sardinia",
"Sardegna",
"Sardegna",
"Tuscany",
"Marche",
"Campania",
"Veneto",
"Lazio",
"Abruzzo",
"Toscana",
"Toscana",
"Veneto",
"Toscana",
"Tuscany",
"Sicilia",
"Lazio"    
    
];


array_es[0]=[
"Alella",
"Alicante",
"Almansa",
"Ampurdan Costa Brava",
"Bierzo",
"Calatayud",
"Campo de Borja",
"Cariñena",
"Cava",
"Chacolí",
"Cigales",
"Condado de Huelva",
"Costers del Segre",
"Jerez-Xérès-Sherry",
"Jumilla",
"La Mancha,",
"Málaga",
"Manchuela ",
"Méntrida",
"Mondejar",
"Monterrei",
"Montilla-Moriles",
"Navarra ",
"Penedés",
"Priorato",
"Rías Baixas",
"Ribeira Sacra ",
"Ribeiro",
"Ribera del Duero",
"Rioja (D.O.C)",
"Rioja (D.O)",
"Rueda",
"Somontano",
"Tarragona",
"Terra Alta",
"Toro",
"Utiel-Requena",
"Valdeorras",
"Valdepeñas",
"Valencia",
"Vinos de Madrid",
"Yecla"    
    
];






array_es[1]=[
"Cataluña",
"C. Valenciana",
"Castilla La Mancha",
"Cataluña",
"Castilla y León",
"Aragón",
"Aragón",
"Aragón",
"Cataluña",
"País Vascos",
"Castilla y León",
"Andaloucía",
"Cataluña",
"Andaloucía",
"Murcia",
"Castilla La Mancha",
"Andaloucía",
"Castilla La Mancha",
"Castilla La Mancha",
"Castilla La Mancha",
"Galicia",
"Andaloucía",
"Navarra ",
"Cataluña",
"Cataluña",
"Galicia",
"Galicia",
"Galicia",
"Castilla y León",
"Rioja",
"Rioja",
"Castilla y León",
"Aragón",
"Cataluña",
"Cataluña",
"Castilla y León",
"C. Valenciana",
"Galicia",
"Castilla La Mancha",
"C. Valenciana",
"Castilla La Mancha",
"Murcia"   
    
    
];





array_fr[0] = [
"Ajaccio",
"Aloxe-corton",
"Alsace grand cru",
"Alsace ou vin d'Alsace",
"Anjou",
"Anjou villages",
"Anjou villages brissac",
"Anjou-coteaux-de-la-loire",
"Arbois",
"Auxey-duresses",
"Bandol",
"Banyuls",
"Banyuls grand cru",
"Barsac",
"Bâtard-montrachet",
"Béarn",
"Beaujolais",
"Beaujolais-villages",
"Beaumes-de-venise",
"Beaune",
"Bellet ou vin de Bellet",
"Bergerac",
"Bienvenues-bâtard-montrachet",
"Blagny",
"Blaye",
"Bonnes-mares",
"Bonnezeaux",
"Bordeaux",
"Bordeaux supérieur",
"Bourgogne",
"Bourgogne aligoté",
"Bourgogne mousseux",
"Bourgogne passe-tout-grains",
"Bourgogne, Chitry",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte d'Auxerre",
"Bourgogne, côte du Couchois",
"Bourgogne, côte Saint-Jacques",
"Bourgogne, Coulanges-la-Vineuse",
"Bourgogne, Épigneul",
"Bourgogne, hautes-côtes de Beaune",
"Bourgogne, hautes-côtes de Nuits",
"Bourgogne, la Chapelle Notre-Dame",
"Bourgogne, le Chapitre",
"Bourgogne, Montrecul",
"Bourgogne, Tonnerre ",
"Bourgogne, Vézelay",
"Bourgogne-ordinaire ou bourgogne grand ordinaire",
"Bourgueil",
"Bouzeron",
"Brouilly",
"Bugey",
"Bugey, Manicle ",
"Bugey, Montagnieu",
"Bugey,Cerdon",
"Buzet",
"Cabardès",
"Cabernet d'Anjou",
"Cabernet de Saumur",
"Cadillac",
"Cahors",
"Canon-fronsac",
"Cassis",
"Cérons",
"Chablis",
"Chablis grand cru",
"Chambertin",
"Chambertin-clos-de-bèze",
"Chambolle-musigny",
"Champagne",
"Chapelle-chambertin",
"Charlemagne",
"Charmes-chambertin",
"Chassagne-montrachet",
"Château-chalon",
"Château-grillet",
"Châteaumeillant",
"Châteauneuf-du-pape",
"Châtillon-en-diois",
"Chénas",
"Chevalier-montrachet",
"Cheverny",
"Chinon",
"Chiroubles",
"Chorey-lès-beaune",
"Clairette de Bellegarde",
"Clairette de Die",
"Clairette du Languedoc",
"Clos-de-la-roche",
"Clos-des-lambrays",
"Clos-de-tart",
"Clos-de-vougeot ou clos-vougeot",
"Clos-saint-denis",
"Collioure",
"Condrieu",
"Corbières",
"Corbières-boutenac",
"Cornas",
"Corse ou vin de Corse",
"Corton",
"Corton-charlemagne",
"Costières-de-nîmes",
"Coteaux-champenois",
"Coteaux-d'aix-en-provence",
"Coteaux-de-die",
"Coteaux-de-l'aubance",
"Coteaux-de-saumur",
"Coteaux-du-giennois",
"Coteaux-du-layon",
"Coteaux-du-loir",
"Coteaux-du-lyonnais",
"Coteaux-du-vendômois",
"Coteaux-varois-en-provence",
"Côte-de-beaune",
"Côte-de-beaune-villages",
"Côte-de-brouilly",
"Côte-de-nuits-villages",
"Côte-roannaise",
"Côte-rôtie",
"Côtes-de-bergerac",
"Côtes-de-blaye",
"Côtes-de-bordeaux",
"Côtes-de-bordeaux, Blaye",
"Côtes-de-bordeaux, Cadillac",
"Côtes-de-bordeaux, Castillon ",
"Côtes-de-bordeaux, Francs",
"Côtes-de-bordeaux-saint-macaire",
"Côtes-de-bourg ou bourg ou bourgeais",
"Côtes-de-duras",
"Côtes-de-montravel",
"Côtes-de-provence",
"Côtes-de-toul",
"Côtes-du-forez",
"Côtes-du-jura",
"Côtes-du-marmandais",
"Côtes-du-rhône",
"Côtes-du-rhône villages",
"Côtes-du-rhône-villages , Cairanne",
"Côtes-du-rhône-villages , Chusclan",
"Côtes-du-rhône-villages , Laudun",
"Côtes-du-rhône-villages , Massif d'Uchaux",
"Côtes-du-rhône-villages , Plan de Dieu",
"Côtes-du-rhône-villages , Puyméras",
"Côtes-du-rhône-villages , Roaix",
"Côtes-du-rhône-villages , Rochegude",
"Côtes-du-rhône-villages , Rousset-les-Vignes",
"Côtes-du-rhône-villages , Sablet",
"Côtes-du-rhône-villages , Saint-Gervais",
"Côtes-du-rhône-villages , Saint-Maurice",
"Côtes-du-rhône-villages , Saint-Pantaléon-les-Vignes",
"Côtes-du-rhône-villages , Séguret",
"Côtes-du-rhône-villages , Signargues",
"Côtes-du-rhône-villages , Valréas",
"Côtes-du-rhône-villages , Visan",
"Côtes-du-roussillon",
"Côtes-du-roussillon villages",
"Côtes-du-vivarais",
"Cour-cheverny",
"Crémant d'Alsace",
"Crémant de Bordeaux",
"Crémant de Bourgogne",
"Crémant de Die",
"Crémant de Limoux",
"Crémant de Loire",
"Crémant du Jura",
"Criots-bâtard-montrachet",
"Crozes-hermitage ou crozes-ermitage",
"Échezeaux",
"Entre-deux-mers",
"Faugères",
"Fiefs-vendéens",
"Fitou",
"Fixin",
"Fleurie",
"Fronsac",
"Fronton",
"Gaillac",
"Gaillac-premières-côtes",
"Gevrey-chambertin",
"Gigondas",
"Givry",
"Grands-échezeaux",
"Graves",
"Graves-de-vayres",
"Graves-supérieures",
"Grignan-les-adhémar",
"Griotte-chambertin",
"Haut-médoc",
"Haut-montravel",
"Hermitage ou ermitage",
"Irancy",
"Irouléguy",
"Jasnières",
"Juliénas",
"Jurançon",
"Ladoix",
"La-grande-rue",
"Lalande-de-pomerol",
"Languedoc",
"Languedoc, grés de Montpellier",
"Languedoc, La Clape",
"Languedoc, La Méjanelle",
"Languedoc, Montpeyroux",
"Languedoc, Pézenas",
"Languedoc, Pic Saint-Loup",
"Languedoc, picpoul de Pinet",
"Languedoc, Quatourze",
"Languedoc, Saint-Christol",
"Languedoc, Saint-Drézery",
"Languedoc, Saint-Georges-d'Orques",
"Languedoc, Saint-Saturnin",
"Languedoc, terrasses du Larzac",
"Languedoc, Vérargues",
"Languedoc,Cabrières",
"La-romanée",
"La-tâche",
"Latricières-chambertin",
"Les-baux-de-provence",
"L'étoile",
"Limoux",
"Lirac",
"Listrac-médoc",
"Loupiac",
"Luberon",
"Lussac-saint-émilion",
"Mâcon",
"Madiran",
"Malepère",
"Maranges",
"Marcillac",
"Margaux",
"Marsannay",
"Maury",
"Mazis-chambertin",
"Mazoyères-chambertin",
"Médoc",
"Menetou-salon",
"Mercurey",
"Meursault",
"Minervois",
"Minervois-la-livinière",
"Monbazillac",
"Montagne-saint-émilion",
"Montagny",
"Monthélie",
"Montlouis-sur-loire",
"Montrachet",
"Montravel",
"Morey-saint-denis",
"Morgon",
"Moselle4",
"Moulin-à-vent",
"Moulis ou moulis-en-médoc",
"Muscadet",
"Muscadet-coteaux-de-la-loire",
"Muscadet-côtes-de-grandlieu",
"Muscadet-sèvre-et-maine",
"Muscat de Beaumes-de-Venise",
"Muscat de Frontignan ou vin de Frontignan",
"Muscat de Lunel",
"Muscat de Mireval",
"Muscat de Rivesaltes",
"Muscat de Saint-Jean-de-Minervois",
"Muscat du Cap-Corse",
"Musigny",
"Néac",
"Nuits-saint-georges",
"Orléans",
"Orléans-cléry",
"Pacherenc-du-vic-bilh",
"Palette",
"Patrimonio",
"Pauillac",
"Pécharmant",
"Pernand-vergelesses",
"Pessac-léognan",
"Petit-chablis",
"Pierrevert",
"Pomerol",
"Pommard",
"Pouilly-fuissé",
"Pouilly-fumé ou blanc-fumé de Pouilly",
"Pouilly-loché",
"Pouilly-sur-loire",
"Pouilly-vinzelles",
"Premières-côtes-de-bordeaux",
"Puisseguin-saint-émilion",
"Puligny-montrachet",
"Quarts-de-chaume",
"Quincy",
"Rasteau",
"Régnié",
"Reuilly",
"Richebourg",
"Rivesaltes",
"Romanée-conti",
"Romanée-saint-vivant",
"Rosé d'Anjou",
"Rosé de Loire",
"Rosé des Riceys",
"Rosette",
"Roussette de Savoie",
"Roussette du Bugey",
"Ruchottes-chambertin",
"Rully",
"Saint-amour",
"Saint-aubin",
"Saint-bris",
"Saint-chinian",
"Sainte-croix-du-mont",
"Sainte-foy-bordeaux",
"Saint-émilion",
"Saint-émilion grand cru",
"Saint-estèphe",
"Saint-georges-saint-émilion",
"Saint-joseph",
"Saint-julien",
"Saint-nicolas-de-bourgueil",
"Saint-péray",
"Saint-pourçain",
"Saint-romain",
"Saint-véran",
"Sancerre",
"Santenay",
"Saumur",
"Saumur-champigny",
"Saussignac",
"Sauternes",
"Savennières",
"Savigny-lès-beaune",
"Seyssel",
"Tavel",
"Touraine",
"Touraine-noble-joué",
"Vacqueyras",
"Valençay",
"Ventoux",
"Vin de Savoie ou savoie",
"Vin de Savoie ou savoie, Abymes",
"Vin de Savoie ou savoie, Apremont",
"Vin de Savoie ou savoie, Arbin",
"Vin de Savoie ou savoie, Ayze",
"Vin de Savoie ou savoie, Charpignat",
"Vin de Savoie ou savoie, Chautagne",
"Vin de Savoie ou savoie, Chignin",
"Vin de Savoie ou savoie, Chignin-Bergeron ou Bergeron",
"Vin de Savoie ou savoie, Cruet",
"Vin de Savoie ou savoie, Jongieux",
"Vin de Savoie ou savoie, Marignan",
"Vin de Savoie ou savoie, Marin",
"Vin de Savoie ou savoie, Montmélian",
"Vin de Savoie ou savoie, Ripaille",
"Vin de Savoie ou savoie, Sainte-Marie-d'Alloix",
"Vin de Savoie ou savoie, Saint-Jean-de-la-Porte",
"Vin de Savoie ou savoie, Saint-Jeoire-Prieuré ",
"Vinsobres",
"Viré-clessé",
"Volnay",
"Vosne-romanée",
"Vougeot",
"Vouvray"

               ];
               
array_fr[1] = [
"Corse",
"Bourgogne, côte de Beaune",
"Alsace",
"Alsace",
"Vallée de la Loire, Anjou",
"Vallée de la Loire, Anjou",
"Vallée de la Loire, Anjou",
"Vallée de la Loire, Anjou",
"Jura",
"Bourgogne, côte de Beaune",
"Provence",
"Languedoc-Roussillon, Roussillon",
"Languedoc-Roussillon, Roussillon",
"Bordeaux, Sauternais",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Beaujolais",
"Beaujolais",
"Vallée du Rhône",
"Bourgogne, côte de Beaune",
"Provence",
"Sud-Ouest",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bordeaux",
"Bourgogne, côte de Nuits",
"Vallée de la Loire",
"Bordeaux",
"Bordeaux",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Vallée de la Loire",
"Bourgogne, côte chalonnaise",
"Beaujolais",
"Bugey",
"Bugey",
"Bugey",
"Bugey",
"Sud-Ouest",
"Languedoc",
"Vallée de la Loire",
"Vallée de la Loire",
"Bordeaux",
"Sud-Ouest",
"Bordeaux",
"Provence",
"Bordeaux, Graves",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Champagne",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Beaune",
"Jura",
"Vallée du Rhône",
"Vallée de la Loire",
"Vallée du Rhône",
"Vallée du Rhône",
"Beaujolais",
"Bourgogne, côte de Beaune",
"Vallée de la Loire",
"Vallée de la Loire",
"Beaujolais",
"Bourgogne, côte de Beaune",
"Vallée du Rhône",
"Vallée du Rhône",
"Languedoc",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Roussillon",
"Vallée du Rhône",
"Languedoc",
"Languedoc",
"Vallée du Rhône",
"Corse",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Vallée du Rhône",
"Champagne",
"Provence",
"Vallée du Rhône",
"Vallée de la Loire",
"Vallée de la Loire",
"Vallée de la Loire",
"Vallée de la Loire",
"Vallée de la Loire",
"Lyonnais",
"Vallée de la Loire",
"Provence",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Beaujolais",
"Bourgogne, côte de Nuits",
"Vallée de la Loire",
"Vallée du Rhône",
"Sud-Ouest",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Sud-Ouest",
"Sud-Ouest",
"Provence",
"Lorraine",
"Vallée de la Loire",
"Jura",
"Sud-Ouest",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Vallée du Rhône",
"Roussillon",
"Roussillon",
"Vallée du Rhône",
"Vallée de la Loire",
"Alsace",
"Bordeaux",
"Bourgogne",
"Vallée du Rhône",
"Languedoc",
"Vallée de la Loire",
"Jura",
"Bourgogne, côte de Beaune",
"Vallée du Rhône",
"Bourgogne, côte de Nuits",
"Bordeaux",
"Languedoc",
"Vallée de la Loire, Vignoble nantais",
"Languedoc",
"Bourgogne, côte de Nuits",
"Beaujolais",
"Bordeaux",
"Sud-Ouest",
"Sud-Ouest",
"Sud-Ouest",
"Bourgogne, côte de Nuits",
"Vallée du Rhône",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte de Nuits",
"Bordeaux, Graves",
"Bordeaux",
"Bordeaux, Graves",
"Vallée du Rhône",
"Bourgogne, côte de Nuits",
"Bordeaux, Médoc",
"Sud-Ouest",
"Vallée du Rhône",
"Bourgogne, Basse-Bourgogne",
"Sud-Ouest",
"Vallée de la Loire",
"Beaujolais",
"Sud-Ouest",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Nuits",
"Bordeaux",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Provence",
"Jura",
"Languedoc",
"Vallée du Rhône",
"Bordeaux, Médoc",
"Bordeaux",
"Vallée du Rhône",
"Bordeaux",
"Bourgogne, Mâconnais",
"Sud-Ouest",
"Languedoc",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Bordeaux, Médoc",
"Bourgogne, côte de Nuits",
"Roussillon",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bordeaux, Médoc",
"Vallée de la Loire",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte de Beaune",
"Languedoc",
"Languedoc",
"Sud-Ouest",
"Bordeaux",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte de Beaune",
"Vallée de la Loire",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Bourgogne, côte de Nuits",
"Beaujolais",
"Lorraine",
"Beaujolais",
"Bordeaux, Médoc",
"Vallée de la Loire, Vignoble nantais",
"Vallée de la Loire, Vignoble nantais",
"Vallée de la Loire, Vignoble nantais",
"Vallée de la Loire, Vignoble nantais",
"Vallée du Rhône",
"Languedoc",
"Languedoc",
"Languedoc",
"Roussillon",
"Languedoc",
"Corse",
"Bourgogne, côte de Nuits",
"Bordeaux",
"Bourgogne, côte de Nuits",
"Vallée de la Loire",
"Vallée de la Loire",
"Sud-Ouest",
"Provence",
"Corse",
"Bordeaux, Médoc",
"Sud-Ouest",
"Bourgogne, côte de Beaune",
"Bordeaux, Graves",
"Bourgogne, Basse-Bourgogne",
"Provence",
"Bordeaux",
"Bourgogne, côte de Beaune",
"Bourgogne, Mâconnais",
"Vallée de la Loire",
"Bourgogne, Mâconnais",
"Vallée de la Loire",
"Bourgogne, Mâconnais",
"Bordeaux",
"Bordeaux",
"Bourgogne, côte de Beaune",
"Vallée de la Loire",
"Vallée de la Loire",
"Vallée du Rhône",
"Beaujolais",
"Vallée de la Loire",
"Bourgogne, côte de Nuits",
"Roussillon",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Vallée de la Loire",
"Vallée de la Loire",
"Champagne",
"Sud-Ouest",
"Savoie",
"Bugey",
"Bourgogne, côte de Nuits",
"Bourgogne, côte chalonnaise",
"Beaujolais",
"Bourgogne, côte de Beaune",
"Bourgogne, Basse-Bourgogne",
"Languedoc",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux, Médoc",
"Bordeaux",
"Vallée du Rhône",
"Bordeaux, Médoc",
"Vallée de la Loire",
"Vallée du Rhône",
"Vallée de la Loire",
"Bourgogne, côte de Beaune",
"Bourgogne, Mâconnais",
"Vallée de la Loire",
"Bourgogne, côte de Beaune",
"Vallée de la Loire, Anjou",
"Vallée de la Loire, Anjou",
"Sud-Ouest",
"Bordeaux, Sauternais",
"Vallée de la Loire, Anjou",
"Bourgogne, côte de Beaune",
"Savoie et Bugey",
"Vallée du Rhône",
"Vallée de la Loire, Touraine",
"Vallée de la Loire, Touraine",
"Vallée du Rhône",
"Vallée de la Loire",
"Vallée du Rhône",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Vallée du Rhône",
"Bourgogne, Mâconnais",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Vallée de la Loire, Touraine"
               ];
                
                var accentMap = {
			"é": "e",
			"è": "e",
                        "î": "i",
                        "â": "a"

		};
                
         
                
                var normalize = function( term ) {
			var ret = "";
			for ( var i = 0; i < term.length; i++ ) {
				ret += accentMap[ term.charAt(i) ] || term.charAt(i);
			}
			return ret;
		};
                

                 $("#id_country").change(function(){
                        $('#id_description').val('');
                        $('#id_region').val('');

                 });


                
                $( "#id_appellation" ).autocomplete({
			source: function( request, response ) {
                                
				var matcher = new RegExp( $.ui.autocomplete.escapeRegex( request.term ), "i" );
                                if ($('#id_country').val() == "France") {
				response( $.grep( array_fr[0], function( value ) {
					value = value.label || value.value || value;
                                        return matcher.test( value ) || matcher.test( normalize( value ) );
				}) );
                                }
                                
                                if ($('#id_country').val() == "Spain") {
				response( $.grep( array_es[0], function( value ) {
					value = value.label || value.value || value;
                                        return matcher.test( value ) || matcher.test( normalize( value ) );
				}) );
                                }
                                if ($('#id_country').val() == "Italia") {
				response( $.grep( array_it[0], function( value ) {
					value = value.label || value.value || value;
                                        return matcher.test( value ) || matcher.test( normalize( value ) );
				}) );
                                }
                                if ($('#id_country').val() == "United States") {
				response( $.grep( array_us[0], function( value ) {
					value = value.label || value.value || value;
                                        return matcher.test( value ) || matcher.test( normalize( value ) );
				}) );
                                }
                               
			},
                        
                        close: function(event, ui) {
                            
                                $('#id_region').val('');
                                
                                if ($('#id_country').val() == "France") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_fr[0]);
                                $('#id_region').val($('#id_region').val() + array_fr[1][index]);
                                }
                                if ($('#id_country').val() == "Spain") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_es[0]);
                                $('#id_region').val($('#id_region').val() + array_es[1][index]);
                                }
                                if ($('#id_country').val() == "Italia") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_it[0]);
                                $('#id_region').val($('#id_region').val() + array_it[1][index]);
                                }
                                if ($('#id_country').val() == "United States") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_us[0]);
                                $('#id_region').val($('#id_region').val() + array_us[1][index]);
                                }                                
                                
                            }
		});

                
                
	});       
        
    
    
    
 //validation
    
    jQuery.validator.messages.required = "";

        $("#id_wineform").validate({
    
            highlight: function(element, errorClass) {
                $(element).parent().css({
                    "border-radius":"0px"
                });
                $(element).parent().css({
                    "box-shadow":"0px 0px 10px #ff0000"
                });

       
            },
        
            unhighlight: function(element, errorClass) {
                $(element).parent().css({
                    "box-shadow":"none"
                });

        
            },
            invalidHandler: function(e, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    var message = errors == 1
                        ? 'You missed 1 field. It has been highlighted below'
                    : 'You missed ' + errors + ' fields.  They have been highlighted below';
                    alert(message);
                    //$("div.error span").html(message);
                    //$("div.error").show();
                    //$("div.validate_error_label label").css("color", "red");
                                                             

                } else {
                     alert("no errors found");

                    //$("div.error").hide();
                    //$("div.validate_error_label label").css("color", "black");

                }
            }
        });
        
    
    
        
  }
  
  


  
elgg.register_hook_handler('init', 'system', elgg.wine_edit.init);    
     
<?php if (FALSE) : ?></script><?php endif; ?>