<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php if (FALSE) : ?>
    <script type="text/javascript">
<?php endif; ?>
    
    elgg.provide('elgg.wine_edit');

    elgg.wine_edit.init = function() {
 	$(function() {
                            
                            
                            
                            
                            
                var array_fr = [];
                var array_es = [];
                var array_it = [];
                var array_us = [];
                
array_us[0] = [

"Alexander Valley",
"Alta Mesa",
"Anderson Valley",
"Applegate Valley",
"Arroyo Grande Valley",
"Arroyo Seco",
"Atlas Peak",
"Ben Lomond Mountain",
"Benmore Valley",
"Bennett Valley",
"Borden Ranch",
"California Shenandoah Valley",
"Capay Valley",
"Carmel Valley",
"Catoctin",
"Cayuga Lake",
"Central Coast",
"Central Delaware Valley",
"Chalk Hill",
"Chalone",
"Chehalem Mountains",
"Chiles Valley",
"Cienega Valley",
"Clarksburg",
"Clear Lake",
"Clements Hills",
"Cole Ranch",
"Columbia Gorge",
"Columbia Valley",
"Cosumnes River",
"Covelo",
"Cucamonga Valley",
"Cumberland Valley",
"Diablo Grande",
"Diamond Mountain District",
"Dos Rios",
"Dry Creek Valley",
"Dundee Hills",
"Dunnigan Hills",
"Edna Valley",
"El Dorado",
"Eola-Amity Hills",
"Fair Play",
"Fiddletown",
"Finger Lakes",
"Green Valley of Russian River Valley",
"Guenoc Valley",
"Hames Valley",
"High Valley",
"Horse Heaven Hills",
"Howell Mountain",
"Hudson River Region",
"Jahant",
"Knights Valley",
"Lake Erie",
"Lancaster Valley",
"Lime Kiln Valley",
"Linganore",
"Livermore Valley",
"Lodi",
"Long Island",
"Los Carneros",
"Madera",
"Malibu-Newton Canyon",
"Martha's Vineyard",
"McDowell Valley",
"McMinnville",
"Mendocino",
"Mendocino Ridge",
"Merritt Island",
"Mokelumne River",
"Monterey",
"Monticello",
"Mt. Harlan",
"Mt. Veeder",
"Napa Valley",
"Niagara Escarpment",
"North Coast",
"North Fork of Long Island",
"North Fork of Roanoke",
"North Yuba",
"Northern Neck George Washington Birthplace",
"Northern Sonoma",
"Oak Knoll District",
"Oakville",
"Outer Coastal Plain",
"Pacheco Pass",
"Paicines",
"Paso Robles",
"Potter Valley",
"Puget Sound",
"Ramona Valley",
"Rattlesnake Hills",
"Red Hill Douglas County",
"Red Hills Lake County",
"Red Mountain",
"Redwood Valley",
"Ribbon Ridge",
"River Junction",
"Rockpile",
"Rocky Knob",
"Rogue Valley",
"Russian River Valley",
"Rutherford",
"Saddle Rock - Malibu",
"Salado Creek",
"San Antonio Valley",
"San Benito",
"San Bernabe",
"San Francisco Bay",
"San Lucas",
"San Pasqual Valley",
"San Ysidro District",
"Santa Clara Valley",
"Santa Cruz Mountains",
"Santa Lucia Highlands",
"Santa Maria Valley",
"Santa Ynez Valley",
"Seiad Valley",
"Seneca Lake",
"Shenandoah Valley",
"Sierra Foothills",
"Sloughhouse",
"Solano County Green Valley",
"Sonoma Coast",
"Sonoma Mountain",
"Sonoma Valley",
"South Coast",
"Southeastern New England",
"Southern Oregon",
"Spring Mountain District",
"St. Helena",
"Sta. Rita Hills",
"Stags Leap District",
"Suisun Valley",
"Temecula Valley",
"The Hamptons",
"Tracy Hills",
"Trinity Lakes",
"Umpqua Valley",
"Virginia's Eastern Shore",
"Wahluke Slope",
"Walla Walla Valley",
"Warren Hills",
"Western Connecticut Highlands",
"Wild Horse Valley",
"Willamette Valley",
"Willow Creek",
"Yadkin Valley",
"Yakima Valley",
"Yamhill-Carlton District",
"York Mountain",
"Yorkville Highlands",
"Yountville"
    
    
];

array_us[1] = [
    

"California",
"California",
"California",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"Maryland",
"New York",
"California",
"New Jersey",
"California",
"California",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"Oregon",
"Oregon",
"California",
"California",
"California",
"Maryland",
"California",
"California",
"California",
"California",
"Oregon",
"California",
"California",
"California",
"Oregon",
"California",
"California",
"New York",
"California",
"California",
"California",
"California",
"Washington",
"California",
"New York",
"California",
"California",
"New York",
"Pennsylvanie",
"California",
"Maryland",
"California",
"California",
"New York",
"California",
"California",
"California",
"Massachusetts",
"California",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"Virginie",
"California",
"California",
"California",
"New York",
"California",
"New York",
"Virginie",
"California",
"Virginie",
"California",
"California",
"California",
"New Jersey",
"California",
"California",
"California",
"California",
"Washington",
"California",
"Washington",
"Oregon",
"California",
"Washington",
"California",
"Oregon",
"California",
"California",
"Virginie",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"New York",
"Virginie",
"California",
"California",
"California",
"California",
"California",
"California",
"California",
"Connecticut",
"Oregon",
"California",
"California",
"California",
"California",
"California",
"California",
"Long Island",
"California",
"California",
"Oregon",
"Virginie",
"Washington",
"Washington",
"New Jersey",
"Connecticut",
"California",
"Oregon",
"California",
"Caroline du Nord",
"Oregon",
"Oregon",
"California",
"California",
"California",
    
];



array_it[0] = [
"Abruzzo",
"Aglianico del Taburno",
"Aglianico del Taburno",
"Aglianico del Vulture",
"Aglianico del Vulture Superiore",
"Albana di Romagna",
"Albugnano",
"Alcamo",
"Aleatico di Gradoli",
"Aleatico di Puglia",
"Alezio",
"Alghero",
"Alta Langa",
"Alta Langa",
"Amarone della Valpolicella",
"Amelia",
"Ansonica Costa dell'Argentario",
"Aprilia",
"Arborea",
"Arcole",
"Asolo Prosecco",
"Assisi",
"Asti",
"Atina",
"Aversa Asprinio",
"Bagnoli di Sopra",
"Barbaresco",
"Barbera d'Alba",
"Barbera d'Asti",
"Barbera d'Asti",
"Barbera del Monferrato",
"Barbera del Monferrato Superiore",
"Barco Reale di Carmignano",
"Bardolino",
"Bardolino Superiore",
"Barletta",
"Barolo",
"Bianchello del Metauro",
"Bianco Capena",
"Bianco dell'Empolese",
"Bianco della Valdinievole",
"Bianco di Custoza",
"Bianco di Pitigliano",
"Bianco Pisano di San Torpe",
"Bianco Vergine della Valdichiana",
"Biferno",
"Bivongi",
"Boca",
"Bolgheri",
"Bonarda dell'Otrepo Pavese",
"Bosco Eliceo",
"Botticino",
"Brachetto d'Acqui or Acqui",
"Bramaterra",
"Breganze",
"Brindisi",
"Brunello di Montalcino",
"Buttafuoco dell'Oltrepo Pavese",
"Cacc'e mmitte di Lucera",
"Cagnina di Romagna",
"Caldaro",
"Calosso",
"Campi Flegrei",
"Campidano di Terralba",
"Canavese",
"Candia dei Colli Apuani",
"Canellino di Frascati",
"Cannonau di Sardegna",
"Capalbio",
"Capri",
"Capriano del Colle",
"Carema",
"Carignano del Sulcis",
"Carmignano",
"Carso",
"Casteggio",
"Castel del Monte",
"Castel del Monte Bombino Nero",
"Castel del Monte Nero di Troia Reserva",
"Castel del Monte Rosso Riserva",
"Castel San Lorenzo",
"Casteller",
"Castelli di Jesi Verdicchio Riserva",
"Castelli Romani",
"Cellatica",
"Cerasuolo d'Abruzzo",
"Cerasuolo di Vittoria",
"Cerveteri",
"Cesanese del Piglio",
"Cesanese del Piglio or Piglio",
"Cesanese di Affile",
"Cesanese di Olevano Romano",
"Chianti",
"Chianti Superiore",
"Cilento",
"Cinque Terre",
"Cinque Terre Sciacchetra",
"Circeo",
"Ciro",
"Cisterna d'Asti",
"Classico",
"Colli Albani",
"Colli Altotiberini",
"Colli Amerini",
"Colli Aretini",
"Colli Asolani Prosecco",
"Colli Astiani in the region surrounding Vigliano d'Asti",
"Colli Berici",
"Colli Bolognesi",
"Colli Bolognesi",
"Colli Bolognesi Classico Pignoletto",
"Colli del Trasimeno",
"Colli dell'Etruria Centrale",
"Colli della Sabina",
"Colli di Conegliano",
"Colli di Conegliano",
"Colli di Faenza",
"Colli di Imola",
"Colli di Luni",
"Colli di Luni",
"Colli di Parma",
"Colli di Rimini",
"Colli di Scandiano e di Canossa",
"Colli Etruschi Viterbesi",
"Colli Euganei",
"Colli Euganei Fior d'Arancio",
"Colli Fiorentini",
"Colli Lanuvini",
"Colli Maceratesi",
"Colli Martani",
"Colli Orientali del Friuli",
"Colli Orientali del Friuli Cialla",
"Colli Orientali del Friuli Picolit",
"Colli Orientali del Friuli Rosazzo",
"Colli Perugini",
"Colli Pesaresi",
"Colli Piacentini",
"Colli Romagna Centrale",
"Colli Senesi",
"Colli Tortonesi",
"Collina Torinese",
"Colline di Levanto",
"Colline Joniche Taratine",
"Colline Lucchesi",
"Colline Novaresi",
"Colline Pisane",
"Colline Saluzzesi",
"Collio",
"Conegliano Valdobbiadene",
"Conero",
"Contea di Sclafani",
"Contessa Entellina",
"Controguerra",
"Copertino",
"Cori",
"Cortese dell'Alto Monferrato",
"Corti Benedettine del Padovano",
"Cortona",
"Costa d'Amalfi",
"Coste della Sesia",
"Delia Nivolelli Nero d'Avola",
"Dolcetto d'Acqui",
"Dolcetto d'Alba",
"Dolcetto d'Asti",
"Dolcetto delle Langhe Monregalesi",
"Dolcetto di Diano d'Alba",
"Dolcetto di Diano d'Alba or Diano d'Alba",
"Dolcetto di Dogliani",
"Dolcetto di Dogliani Superiore or Dogliani",
"Dolcetto di Ovada",
"Dolcetto di Ovada Superiore or Ovada",
"Donnici",
"Elba",
"Eloro",
"Erbaluce di Caluso",
"Erbaluce di Caluso or Caluso",
"Erice",
"Esino",
"Est! Est!! Est!!! di Montefiascone",
"Etna",
"Falanghina del Sannio",
"Falerio dei Colli Ascolani",
"Falerno del Massico",
"Fara",
"Faro",
"Fiano di Avellino",
"Fior d'Arancio Colli Euganei",
"Franciacorta",
"Frascati",
"Frascati Superiore",
"Freisa d'Asti",
"Freisa di Chieri",
"Friuli Annia",
"Friuli Aquileia",
"Friuli Grave",
"Friuli Isonzo",
"Friuli Latisana",
"Gabiano",
"Galatina",
"Galluccio",
"Gambellara",
"Garda",
"Garda",
"Garda Colli Mantovani",
"Gattinara",
"Gavi or Cortese di Gavi",
"Genazzano",
"Ghemme",
"Gioia del Colle",
"Giro di Cagliari",
"Golfo del Tigullio",
"Gravina",
"Greco di Bianco",
"Greco di Tufo",
"Grignolino d'Asti",
"Grignolino del Monferrato Casalese",
"Guardiolo",
"Gutturnio",
"Irpina",
"Ischia",
"Kalterersee",
"Lacrima di Morro d'Alba",
"Lago di Caldaro",
"Lago di Corbara",
"Lambrusco di Sorbara",
"Lambrusco Grasparossa di Castelvetro",
"Lambrusco Mantovano",
"Lambrusco Salamino di Santacroce",
"Lamezia",
"Langhe",
"Lessona",
"Leverano",
"Lison Pramaggiore",
"Lison Pramaggiore",
"Lison-Pramaggiore",
"Lizzano",
"Loazzolo",
"Locorotondo",
"Lugana",
"Lugana",
"Malanotte Raboso Superiore",
"Malvasia delle Lipari",
"Malvasia di Bosa",
"Malvasia di Cagliari",
"Malvasia di Casorzo d'Asti",
"Malvasia di Castelnuovo Don Bosco",
"Mamertino di Milazzo",
"Mandrolisai",
"Maremma Toscana",
"Marino",
"Marsala",
"Martina",
"Matera",
"Matino",
"Melissa",
"Menfi",
"Merlara",
"Modena",
"Molise",
"Monferrato",
"Monica di Cagliari",
"Monica di Sardegna",
"Monreale",
"Montalbano",
"Montecarlo",
"Montecompatri Colonna",
"Montecucco",
"Montefalco",
"Montello",
"Montello e Colli Asolani",
"Montepulciano d'Abruzzo",
"Montepulciano d'Abruzzo",
"Monteregio di Massa Marittima",
"Montescudaio",
"Montespertoli",
"Monti Lessini",
"Morellino di Scansano",
"Morellino di Scansano",
"Moscadello di Montalcino",
"Moscato di Cagliari",
"Moscato di Pantelleria",
"Moscato di Sardegna",
"Moscato di Scanzo",
"Moscato di Siracusa",
"Moscato di Sorso Sennori",
"Moscato di Trani",
"Nardo",
"Nasco di Cagliari",
"Nebbiolo d'Alba",
"Negroamaro di Terra d'Otranto",
"Nettuno",
"Nizza in the region surrounding Nizza Monferrato",
"Noto",
"Nuragus di Cagliari",
"Offida",
"Offida",
"Oltrepo Pavese",
"Oltrepo Pavese Metodo Classico",
"Orcia",
"Orta Nova",
"Ortona",
"Ortrugo",
"Orvieto",
"Orvieto",
"Ostuni",
"Pagadebit di Romagna",
"Parrina",
"Penisola Sorrentina",
"Pentro di Isernia",
"Pergola",
"Piave",
"Piemonte",
"Piglio",
"Pinerolese",
"Pollino",
"Pomino",
"Pornassio",
"Primitivo di Manduria",
"Primitivo di Manduria Dolce Naturale",
"Prosecco",
"Prosecco",
"Ramandolo",
"Recioto della Valpolicella",
"Recioto di Gambellara",
"Recioto di Soave",
"Reggiano",
"Reno",
"Riesi",
"Riviera del Brenta",
"Riviera del Garda Bresciano",
"Riviera Ligure di Ponente",
"Roero",
"Roma",
"Romagna Albana Spumante (Bianco Spumante)",
"Rosazzo",
"Rossese di Dolceacqua",
"Rosso Barletta",
"Rosso Canosa",
"Rosso Conero",
"Rosso di Cerignola",
"Rosso di Montalcino",
"Rosso di Montepulciano",
"Rosso Orvietano",
"Rosso Piceno",
"Rubino di Cantavenna",
"Ruche di Castagnole Monferrato",
"Ruche di Castagnole Monferrato",
"Rufina",
"Sagrantino di Montefalco",
"Salaparuta",
"Salice Salentino",
"Sambuca di Sicilia",
"San Colombano al Lambro",
"San Gimignano",
"San Martino della Battaglia",
"San Martino della Battaglia",
"San Severo",
"San Vito di Luzzi",
"Sangiovese di Romagna",
"Sannio",
"Sant'Agata dei Goti",
"Sant'Anna di Isola Capo Rizzuto",
"Sant'Antimo",
"Santa Maddalena",
"Santa Margherita di Belice",
"Sardegna Semidano",
"Savuto",
"Scanzo",
"Scavigna",
"Sciacca",
"Sforzato di Valtellina or Sfurzat di Valtellina",
"Siracusa",
"Sizzano",
"Soave",
"Soave Superiore",
"Solopaca",
"Sovana",
"Spoleto",
"Squinzano",
"Sudtirol",
"Taburno",
"Tarquinia",
"Taurasi",
"Tavoliere",
"Tavoliere delle Puglie",
"Teroldego Rotaliano",
"Terra d'Otranto",
"Terracina or Moscato di Terracina",
"Terre dell'Alta Val d'Agri",
"Terre di Franciacorta",
"Terre Tollesi",
"Tinella in the region surrounding Costigliole d'Asti",
"Tintilia",
"Todi",
"Torgiano",
"Torgiano Rosso Riserva",
"Trebbiano d'Abruzzo",
"Trebbiano di Romagna",
"Trentino",
"Trento a sparkling wine",
"Tullum",
"Val d'Arbia",
"Val di Cornia",
"Val Polcevera",
"Valcalepio",
"Valdadige",
"Valdadige",
"Valdadige",
"Valle d'Aosta",
"Valpolicella",
"Valpolicella Ripasso",
"Valsusa",
"Valtellina Rosso",
"Valtellina Superiore",
"Valtenesi",
"Velletri",
"Venezia",
"Verbicaro",
"Verdicchio dei Castelli di Jesi",
"Verdicchio di Matelica",
"Verdicchio di Matelica Riserva",
"Verduno Pelaverga",
"Vermentino di Gallura",
"Vermentino di Sardegna",
"Vernaccia di Oristano",
"Vernaccia di San Gimignano",
"Vernaccia di Serrapetrona",
"Vesuvio",
"Vicenza",
"Vignanello",
"Villamagna",
"Vin Santo del Chianti",
"Vin Santo del Chianti Classico",
"Vin Santo di Gambellara",
"Vin Santo di Montepulciano",
"Vino Nobile di Montepulciano",
"Vittoria",
"Zagarolo"   
];


array_it[1] = [
"Abruzzo",
"Campania",
"Campania",
"Basilicata",
"Basilicata",
"Emilia Romagna",
"Piemonte",
"Sicilia",
"Lazio",
"Apulia",
"Apulia",
"Sardegna",
"Piemonte",
"Piedmont",
"Veneto",
"Umbria",
"Toscana",
"Lazio",
"Sardegna",
"Veneto",
"Veneto",
"Umbria",
"Piedmont",
"Lazio",
"Campania",
"Veneto",
"Piedmont",
"Piemonte",
"Piemonte",
"Piedmont",
"Piemonte",
"Piedmont",
"Toscana",
"Veneto",
"Veneto",
"Apulia",
"Piedmont",
"Marche",
"Lazio",
"Toscana",
"Toscana",
"Veneto",
"Toscana",
"Toscana",
"Toscana",
"Molise",
"Calabria",
"Piemonte",
"Toscana",
"Lombardia",
"Emilia-Romagna",
"Lombardia",
"Piedmont",
"Piemonte",
"Veneto",
"Apulia",
"Tuscany",
"Lombardia",
"Apulia",
"Emilia-Romagna",
"Trentino",
"Piemonte",
"Campania",
"Sardegna",
"Piemonte",
"Toscana",
"Lazio",
"Sardegna",
"Toscana",
"Campania",
"Lombardia",
"Piemonte",
"Sardegna",
"Tuscany",
"Friuli-Venezia Giulia",
"Lombardia",
"Apulia",
"Puglia",
"Puglia",
"Puglia",
"Campania",
"Trentino",
"Marche",
"Lazio",
"Lombardia",
"Abruzzo",
"Sicily",
"Lazio",
"Lazio",
"Lazio",
"Lazio",
"Lazio",
"Tuscany",
"Tuscany",
"Campania",
"Liguria",
"Liguria",
"Lazio",
"Calabria",
"Piemonte",
"Tuscany",
"Lazio",
"Umbria",
"Umbria",
"Tuscany",
"Veneto",
"Piedmont",
"Veneto",
"Emilia-Romagna",
"Emilia Romagna",
"Emilia-Romagna",
"Umbria",
"Toscana",
"Lazio",
"Veneto",
"Veneto",
"Emilia-Romagna",
"Emilia-Romagna",
"Liguria",
"Toscana",
"Emilia-Romagna",
"Emilia-Romagna",
"Emilia-Romagna",
"Lazio",
"Veneto",
"Veneto",
"Tuscany",
"Lazio",
"Marche",
"Umbria",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Umbria",
"Marche",
"Emilia-Romagna",
"Emilia-Romagna",
"Tuscany",
"Piemonte",
"Piemonte",
"Liguria",
"Apulia",
"Toscana",
"Piemonte",
"Tuscany",
"Piemonte",
"Friuli-Venezia Giulia",
"Veneto",
"Marche",
"Sicilia",
"Sicilia",
"Abruzzo",
"Apulia",
"Lazio",
"Piemonte",
"Veneto",
"Toscana",
"Campania",
"Piemonte",
"Sicilia",
"Piemonte",
"Piemonte",
"Piemonte",
"Piemonte",
"Piemonte",
"Piedmont",
"Piemonte",
"Piedmont",
"Piemonte",
"Piedmont",
"Calabria",
"Toscana",
"Sicilia",
"Piemonte",
"Piedmont",
"Sicilia",
"Marche",
"Lazio",
"Sicilia",
"Campania",
"Marche",
"Campania",
"Piemonte",
"Sicilia",
"Campania",
"Veneto",
"Lombardia",
"Lazio",
"Lazio",
"Piemonte",
"Piemonte",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Friuli-Venezia Giulia",
"Piemonte",
"Apulia",
"Campania",
"Veneto",
"Lombardia",
"Veneto",
"Lombardia",
"Piedmont",
"Piedmont",
"Lazio",
"Piedmont",
"Apulia",
"Sardegna",
"Liguria",
"Apulia",
"Calabria",
"Campania",
"Piemonte",
"Piemonte",
"Campania",
"Emilia-Romagna",
"Campania",
"Campania",
"South Tyrol",
"Marche",
"Trentino",
"Umbria",
"Emilia-Romagna",
"Emilia-Romagna",
"Lombardia",
"Emilia-Romagna",
"Calabria",
"Piemonte",
"Piemonte",
"Apulia",
"Friuli-Venezia Giulia",
"Veneto",
"Veneto",
"Apulia",
"Piemonte",
"Apulia",
"Lombardia",
"Veneto",
"Veneto",
"Sicilia",
"Sardegna",
"Sardegna",
"Piemonte",
"Piemonte",
"Sicilia",
"Sardegna",
"Toscana",
"Lazio",
"Sicilia",
"Apulia",
"Basilicata",
"Apulia",
"Calabria",
"Sicilia",
"Veneto",
"Emilia-Romagna",
"Molise",
"Piemonte",
"Sardegna",
"Sardegna",
"Sicilia",
"Tuscany",
"Toscana",
"Lazio",
"Toscana",
"Umbria",
"Veneto",
"Veneto",
"Abruzzo",
"Abruzzo",
"Toscana",
"Toscana",
"Tuscany",
"Veneto",
"Toscana",
"Tuscany",
"Toscana",
"Sardegna",
"Sicilia",
"Sardegna",
"Lombardia",
"Sicilia",
"Sardegna",
"Apulia",
"Apulia",
"Sardegna",
"Piemonte",
"Apulia",
"Lazio",
"Piedmont",
"Sicilia",
"Sardegna",
"Marche",
"Marche",
"Lombardia",
"Lombardia",
"Toscana",
"Apulia",
"Abruzzo",
"Emilia-Romagna",
"Lazio",
"Umbria",
"Apulia",
"Emilia-Romagna",
"Toscana",
"Campania",
"Molise",
"Marche",
"Veneto",
"Piemonte",
"Lazio",
"Piemonte",
"Calabria",
"Toscana",
"Liguria",
"Apulia",
"Puglia",
"Veneto",
"Veneto",
"Friuli-Venezia Giulia",
"Veneto",
"Veneto",
"Veneto",
"Emilia-Romagna",
"Emilia-Romagna",
"Sicilia",
"Veneto",
"Lombardia",
"Liguria",
"Piedmont",
"Lazio",
"Emilia-Romagna",
"Friuli-Venezia Giulia",
"Liguria",
"Apulia",
"Apulia",
"Marche",
"Apulia",
"Toscana",
"Toscana",
"Umbria",
"Marche",
"Piemonte",
"Piemonte",
"Piedmont",
"Tuscany",
"Umbria",
"Sicilia",
"Apulia",
"Sicilia",
"Lombardia",
"Toscana",
"Lombardia",
"Veneto",
"Apulia",
"Calabria",
"Emilia-Romagna",
"Campania",
"Campania",
"Calabria",
"Toscana",
"South Tyrol",
"Sicilia",
"Sardegna",
"Calabria",
"Lombardia",
"Calabria",
"Sicilia",
"Lombardia",
"Sicilia",
"Piemonte",
"Veneto",
"Veneto",
"Campania",
"Toscana",
"Umbria",
"Apulia",
"South Tyrol",
"Campania",
"Lazio",
"Campania",
"Apulia",
"Apulia",
"Trentino",
"Apulia",
"Lazio",
"Basilicata",
"Lombardia",
"Abruzzo",
"Piedmont",
"Molise",
"Umbria",
"Umbria",
"Umbria",
"Abruzzo",
"Emilia-Romagna",
"Trentino",
"Trentino",
"Abruzzo",
"Toscana",
"Toscana",
"Liguria",
"Lombardia",
"South Tyrol",
"Trentino",
"Veneto",
"Valle d'Aosta",
"Veneto",
"Veneto",
"Piemonte",
"Lombardia",
"Lombardia",
"Lombardia",
"Lazio",
"Veneto",
"Calabria",
"Marche",
"Marche",
"Marche",
"Piemonte",
"Sardinia",
"Sardegna",
"Sardegna",
"Tuscany",
"Marche",
"Campania",
"Veneto",
"Lazio",
"Abruzzo",
"Toscana",
"Toscana",
"Veneto",
"Toscana",
"Tuscany",
"Sicilia",
"Lazio"    
    
];


array_es[0]=[
"Alella",
"Alicante",
"Almansa",
"Ampurdan Costa Brava",
"Bierzo",
"Calatayud",
"Campo de Borja",
"Cariñena",
"Cava",
"Chacolí",
"Cigales",
"Condado de Huelva",
"Costers del Segre",
"Jerez-Xérès-Sherry",
"Jumilla",
"La Mancha,",
"Málaga",
"Manchuela ",
"Méntrida",
"Mondejar",
"Monterrei",
"Montilla-Moriles",
"Navarra ",
"Penedés",
"Priorato",
"Rías Baixas",
"Ribeira Sacra ",
"Ribeiro",
"Ribera del Duero",
"Rioja (D.O.C)",
"Rioja (D.O)",
"Rueda",
"Somontano",
"Tarragona",
"Terra Alta",
"Toro",
"Utiel-Requena",
"Valdeorras",
"Valdepeñas",
"Valencia",
"Vinos de Madrid",
"Yecla"    
    
];






array_es[1]=[
"Cataluña",
"C. Valenciana",
"Castilla La Mancha",
"Cataluña",
"Castilla y León",
"Aragón",
"Aragón",
"Aragón",
"Cataluña",
"País Vascos",
"Castilla y León",
"Andaloucía",
"Cataluña",
"Andaloucía",
"Murcia",
"Castilla La Mancha",
"Andaloucía",
"Castilla La Mancha",
"Castilla La Mancha",
"Castilla La Mancha",
"Galicia",
"Andaloucía",
"Navarra ",
"Cataluña",
"Cataluña",
"Galicia",
"Galicia",
"Galicia",
"Castilla y León",
"Rioja",
"Rioja",
"Castilla y León",
"Aragón",
"Cataluña",
"Cataluña",
"Castilla y León",
"C. Valenciana",
"Galicia",
"Castilla La Mancha",
"C. Valenciana",
"Castilla La Mancha",
"Murcia"   
    
    
];





array_fr[0] = [
"Agenais IGP",
"Ajaccio",
"Aloxe-Corton",
"Aloxe-Corton premier cru",
"Aloxe-Corton premier cru Clos des Maréchaudes",
"Aloxe-Corton premier cru Clos du Chapitre",
"Aloxe-Corton premier cru La Coutière",
"Aloxe-Corton premier cru La Maréchaude",
"Aloxe-Corton premier cru La Toppe au Vert",
"Aloxe-Corton premier cru Les Chaillots blanc",
"Aloxe-Corton premier cru Les Fournières",
"Aloxe-Corton premier cru Les Guérets",
"Aloxe-Corton premier cru Les Maréchaudes",
"Aloxe-Corton premier cru Les Moutottes",
"Aloxe-Corton premier cru Les Paulands",
"Aloxe-Corton premier cru Les Petites Folières",
"Aloxe-Corton premier cru Les Valozières",
"Aloxe-Corton premier cru Les Vercots",
"Alpes-de-Haute-Provence IGP",
"Alpes-Maritimes IGP",
"Alpilles IGP",
"Alsace Grand Cru",
"Alsace Ou Vin D'Alsace",
"Altenberg De Bergbieten, Alsace Grand Cru",
"Altenberg De Bergheim, Alsace Grand Cru",
"Altenberg De Wolxheim, Alsace Grand Cru",
"Anjou",
"Anjou Villages",
"Anjou Villages Brissac",
"Anjou-Coteaux-De-La-Loire",
"Arbois",
"Arbois Pupillin",
"Ardèche IGP",
"Ariège IGP",
"Atlantique IGP",
"Aude IGP",
"Auxey-Duresses",
"Auxey-Duresses Côte de Beaune",
"Auxey-Duresses premier cru",
"Auxey-Duresses premier cru Bas des Duresses",
"Auxey-Duresses premier cru Climat du Val",
"Auxey-Duresses premier cru Clos du Val",
"Auxey-Duresses premier cru La Chapelle",
"Auxey-Duresses premier cru Les Bréterins",
"Auxey-Duresses premier cru Les Duresses",
"Auxey-Duresses premier cru Les Ecussaux",
"Auxey-Duresses premier cru Les Grands Champs",
"Auxey-Duresses premier cru Reugne",
"Aveyron IGP",
"Bandol",
"Banyuls",
"Banyuls Grand Cru",
"Barsac",
"Bâtard-Montrachet",
"Béarn",
"Beaujolais",
"Beaujolais-Villages",
"Beaumes-De-Venise",
"Beaune",
"Beaune premier cru",
"Beaune premier cru A l'Ecu",
"Beaune premier cru Aux Coucherias",
"Beaune premier cru Aux Cras",
"Beaune premier cru Belissand",
"Beaune premier cru Blanches Fleurs",
"Beaune premier cru Champs Pimont",
"Beaune premier cru Clos de la Feguine",
"Beaune premier cru Clos de la Mousse",
"Beaune premier cru Clos de l'Ecu",
"Beaune premier cru Clos des Avaux",
"Beaune premier cru Clos des Ursules",
"Beaune premier cru Clos du Roi",
"Beaune premier cru Clos Saint-Landry",
"Beaune premier cru En Genêt",
"Beaune premier cru En l'Orme",
"Beaune premier cru La Mignotte",
"Beaune premier cru Le Bas des Teurons",
"Beaune premier cru Le Clos des Mouches",
"Beaune premier cru Les Aigrots",
"Beaune premier cru Les Avaux",
"Beaune premier cru Les Boucherottes",
"Beaune premier cru Les Bressandes",
"Beaune premier cru Les Cents Vignes",
"Beaune premier cru Les Chouacheux",
"Beaune premier cru Les Epenotes",
"Beaune premier cru Les Fèves",
"Beaune premier cru Les Grèves",
"Beaune premier cru Les Marconnets",
"Beaune premier cru Les Montrevenots",
"Beaune premier cru Les Perrières",
"Beaune premier cru Les Reversés",
"Beaune premier cru Les Sceaux",
"Beaune premier cru Les Seurey",
"Beaune premier cru Les Sizies",
"Beaune premier cru Les Teurons",
"Beaune premier cru Les Toussaints",
"Beaune premier cru Les Tuvilains",
"Beaune premier cru Les Vignes Franches",
"Beaune premier cru Montée Rouge",
"Beaune premier cru Pertuisots",
"Beaune premier cru Sur les Grèves",
"Beaune premier cru Sur les Grèves - Clos Saint-Anne",
"Bellet Ou Vin de Bellet",
"Bergerac",
"Bienvenues-Bâtard-Montrachet",
"Blagny",
"Blagny premier cru",
"Blagny premier cru Hameau de Blagny",
"Blagny premier cru La Garenne",
"Blagny premier cru La Jeunellotte",
"Blagny premier cru La Pièce sous le Bois",
"Blagny premier cru Sous Blagny",
"Blagny premier cru Sous le Dos d'Ane",
"Blagny premier cru Sous le Puits",
"Blaye",
"Bonnes-Mares",
"Bonnezeaux",
"Bordeaux",
"Bordeaux Supérieur",
"Bouches-Du-Rhône IGP",
"Bourgogne",
"Bourgogne aligoté",
"Bourgogne Chitry",
"Bourgogne Côte Chalonnaise",
"Bourgogne Côte Saint-Jacques",
"Bourgogne Côtes d'Auxerre",
"Bourgogne Côtes du Couchois",
"Bourgogne Coulanges-la-Vineuse",
"Bourgogne Epineuil",
"Bourgogne Hautes Côtes de Beaune",
"Bourgogne Hautes Côtes de Nuits",
"Bourgogne La Chapelle Notre-Dame",
"Bourgogne Le Chapitre",
"Bourgogne Montrecul",
"Bourgogne mousseux",
"Bourgogne Passe-tout-grains",
"Bourgogne Tonnerre",
"Bourgogne Vézelay",
"Bourgogne-Ordinaire Ou Bourgogne Grand Ordinaire",
"Bourgueil",
"Bouzeron",
"Bouzeron",
"Brand, Alsace Grand Cru",
"Brouilly",
"Bruderthal, Alsace Grand Cru",
"Brulhois",
"Bugey",
"Bugey, Manicle ",
"Bugey, Montagnieu",
"Bugey,Cerdon",
"Buzet",
"Cabardès",
"Cabernet d'Anjou",
"Cabernet de Saumur",
"Cadillac",
"Cahors",
"Calvados IGP",
"Canon-Fronsac",
"Cassis",
"Cérons",
"Cévennes  IGP",
"Chablis",
"Chablis Grand Cru",
"Chablis Grand Cru Blanchot",
"Chablis Grand Cru Bougros",
"Chablis Grand Cru Grenouilles",
"Chablis Grand Cru Les Clos",
"Chablis Grand Cru Preuses",
"Chablis Grand Cru Valmur",
"Chablis Grand Cru Vaudésir",
"Chablis premier cru",
"Chablis premier cru Beauroy",
"Chablis premier cru Berdiot",
"Chablis premier cru Beugnons",
"Chablis premier cru Butteaux",
"Chablis premier cru Chapelot",
"Chablis premier cru Chatains",
"Chablis premier cru Chaume de Talvat",
"Chablis premier cru Côte de Bréchain",
"Chablis premier cru Côte de Cuisy",
"Chablis premier cru Côte de Fontenay",
"Chablis premier cru Côte de Jouan",
"Chablis premier cru Côte de Léchet",
"Chablis premier cru Côte de Savant",
"Chablis premier cru Côte de Vaubarousse",
"Chablis premier cru Côte des Prés-Girots",
"Chablis premier cru Forêts",
"Chablis premier cru Fourchaume",
"Chablis premier cru Les Beauregards",
"Chablis premier cru Les Epinottes",
"Chablis premier cru Les Fourneaux",
"Chablis premier cru Les Lys",
"Chablis premier cru L'Homme Mort",
"Chablis premier cru Mélinots",
"Chablis premier cru Mont de Milieu",
"Chablis premier cru Montée de Tonnerre",
"Chablis premier cru Montmains",
"Chablis premier cru Morein",
"Chablis premier cru Pied d'Aloup",
"Chablis premier cru Roncières",
"Chablis premier cru Sécher",
"Chablis premier cru Troesmes",
"Chablis premier cru Vaillons",
"Chablis premier cru Vau de Vey",
"Chablis premier cru Vau Ligneau",
"Chablis premier cru Vaucoupin",
"Chablis premier cru Vaugiraut",
"Chablis premier cru Vaulorent",
"Chablis premier cru Vaupulent",
"Chablis premier cru Vaux Ragons",
"Chablis premier cru Vosgros",
"Chambertin",
"Chambertin-Clos de Bèze",
"Chambolle-Musigny",
"Chambolle-Musigny premier cru",
"Chambolle-Musigny premier cru Aux Beaux Bruns",
"Chambolle-Musigny premier cru Aux Combottes",
"Chambolle-Musigny premier cru Aux Echanges",
"Chambolle-Musigny premier cru Derrière la Grange",
"Chambolle-Musigny premier cru La Combe d'Orveau",
"Chambolle-Musigny premier cru Les Amoureuses",
"Chambolle-Musigny premier cru Les Baudes",
"Chambolle-Musigny premier cru Les Borniques",
"Chambolle-Musigny premier cru Les Carrières",
"Chambolle-Musigny premier cru Les Chabiots",
"Chambolle-Musigny premier cru Les Charmes",
"Chambolle-Musigny premier cru Les Chatelots",
"Chambolle-Musigny premier cru Les Combottes",
"Chambolle-Musigny premier cru Les Cras",
"Chambolle-Musigny premier cru Les Feusselottes",
"Chambolle-Musigny premier cru Les Fuées",
"Chambolle-Musigny premier cru Les Groseilles",
"Chambolle-Musigny premier cru Les Gruenchers",
"Chambolle-Musigny premier cru Les Hauts Doix",
"Chambolle-Musigny premier cru Les Lavrottes",
"Chambolle-Musigny premier cru Les Noirots",
"Chambolle-Musigny premier cru Les Plantes",
"Chambolle-Musigny premier cru Les Sentiers",
"Chambolle-Musigny premier cru Les Véroilles",
"Champagne",
"Champagne Grand Cru",
"Champagne premier cru",
"Chapelle-Chambertin",
"Charentais  IGP",
"Charlemagne",
"Charmes-Chambertin",
"Chassagne-Montrachet",
"Chassagne-Montrachet premier cru",
"Chassagne-Montrachet premier cru Abbaye de Morgeot",
"Chassagne-Montrachet premier cru Blanchot dessus",
"Chassagne-Montrachet premier cru Bois de Chassagne",
"Chassagne-Montrachet premier cru Cailleret",
"Chassagne-Montrachet premier cru Champs Jendreau",
"Chassagne-Montrachet premier cru Chassagne",
"Chassagne-Montrachet premier cru Chassagne du Clos Cha...",
"Chassagne-Montrachet premier cru Chassagne du Clos Sai...",
"Chassagne-Montrachet premier cru Clos Pitois",
"Chassagne-Montrachet premier cru Clos Saint-Jean",
"Chassagne-Montrachet premier cru Dent de Chien",
"Chassagne-Montrachet premier cru En Cailleret",
"Chassagne-Montrachet premier cru En Remilly",
"Chassagne-Montrachet premier cru En Virondot",
"Chassagne-Montrachet premier cru Ez Crets",
"Chassagne-Montrachet premier cru Ez Crottes",
"Chassagne-Montrachet premier cru Francemont",
"Chassagne-Montrachet premier cru Guerchère",
"Chassagne-Montrachet premier cru La Boudriotte",
"Chassagne-Montrachet premier cru La Cardeuse",
"Chassagne-Montrachet premier cru La Chapelle",
"Chassagne-Montrachet premier cru La Grande Borne",
"Chassagne-Montrachet premier cru La Grande Montagne",
"Chassagne-Montrachet premier cru La Maltroie",
"Chassagne-Montrachet premier cru La Romanée",
"Chassagne-Montrachet premier cru La Roquemaure",
"Chassagne-Montrachet premier cru Les Baudines",
"Chassagne-Montrachet premier cru Les Boirettes",
"Chassagne-Montrachet premier cru Les Bondues",
"Chassagne-Montrachet premier cru Les Brussonnes",
"Chassagne-Montrachet premier cru Les Champs gain",
"Chassagne-Montrachet premier cru Les Chaumées",
"Chassagne-Montrachet premier cru Les Chaumes",
"Chassagne-Montrachet premier cru Les Chenevottes",
"Chassagne-Montrachet premier cru Les Combards",
"Chassagne-Montrachet premier cru Les Commes",
"Chassagne-Montrachet premier cru Les Embazées",
"Chassagne-Montrachet premier cru Les Fairendes",
"Chassagne-Montrachet premier cru Les Grandes Ruchottes",
"Chassagne-Montrachet premier cru Les Grands Clos",
"Chassagne-Montrachet premier cru Les Macherelles",
"Chassagne-Montrachet premier cru Les Murées",
"Chassagne-Montrachet premier cru Les Pasquelles",
"Chassagne-Montrachet premier cru Les Petites Fairendes",
"Chassagne-Montrachet premier cru Les Petits Clos",
"Chassagne-Montrachet premier cru Les Places",
"Chassagne-Montrachet premier cru Les Rebichets",
"Chassagne-Montrachet premier cru Les Vergers",
"Chassagne-Montrachet premier cru Morgeot",
"Chassagne-Montrachet premier cru Petingeret",
"Chassagne-Montrachet premier cru Tête du Clos",
"Chassagne-Montrachet premier cru Tonton Marcel",
"Chassagne-Montrachet premier cru Vide Bourse",
"Chassagne-Montrachet premier cru Vigne Blanche",
"Chassagne-Montrachet premier cru Vigne Derrière",
"Château-Chalon",
"Château-Grillet",
"Châteaumeillant",
"Châteauneuf-du-Pape",
"Châtillon-en-Diois",
"Chénas",
"Chevalier-Montrachet",
"Cheverny",
"Chinon",
"Chiroubles",
"Chorey-lès-Beaune",
"Chorey-lès-Beaune Côte de Beaune",
"Cité de Carcassonne  IGP",
"Clairette de Bellegarde",
"Clairette de Die",
"Clairette du Languedoc",
"Clos de la Roche",
"Clos de Tart",
"Clos de Vougeot Ou Clos-Vougeot",
"Clos des Lambrays",
"Clos Saint-Denis",
"Clos-Saint-Denis",
"Collines Rhodaniennes  IGP",
"Collioure",
"Comté Tolosan  IGP",
"Comtés Rhodaniens  IGP",
"Condrieu",
"Corbières",
"Corbières-Boutenac",
"Cornas",
"Corse Ou Vin de Corse",
"Corton",
"Corton-Charlemagne",
"Costières-de-Nîmes",
"Côte de Beaune",
"Côte de Beaune-Villages",
"Côte de Nuits-Villages",
"Côte Vermeille  IGP",
"Coteaux Bourguignons",
"Coteaux d'Ancenis",
"Coteaux de Coiffy  IGP",
"Coteaux de Glanes IGP",
"Coteaux de L'Ain IGP",
"Coteaux de L'Auxois IGP",
"Coteaux de Narbonne IGP",
"Coteaux de Peyriac IGP",
"Coteaux de Tannay IGP",
"Coteaux d'Ensérune IGP",
"Coteaux des Baronnies IGP",
"Coteaux du Cher et de L'Arnon IGP",
"Coteaux du Libron IGP",
"Coteaux du Pont Du Gard IGP",
"Coteaux-Champenois",
"Coteaux-d'Aix-en-Provence",
"Coteaux-de-Die",
"Coteaux-de-l'Aubance",
"Coteaux-de-Saumur",
"Coteaux-du-Giennois",
"Coteaux-du-Layon",
"Coteaux-du-Loir",
"Coteaux-du-Lyonnais",
"Coteaux-du-Vendômois",
"Coteaux-Varois-en-Provence",
"Côte-de-Brouilly",
"Côte-Roannaise",
"Côte-Rôtie",
"Côtes Catalanes IGP",
"Côtes d'Auvergne",
"Côtes de Gascogne IGP",
"Côtes de la Charité IGP",
"Côtes de Meuse IGP",
"Côtes de Millau",
"Côtes de Thau IGP",
"Côtes de Thongue IGP",
"Côtes du Lot IGP",
"Côtes du Tarn IGP",
"Côtes-de-Bergerac",
"Côtes-de-Blaye",
"Côtes-de-Bordeaux",
"Côtes-de-Bordeaux, Blaye",
"Côtes-de-Bordeaux, Cadillac",
"Côtes-de-Bordeaux, Castillon ",
"Côtes-de-Bordeaux, Francs",
"Côtes-de-Bordeaux-Saint-Macaire",
"Côtes-de-Bourg Ou Bourg Ou Bourgeais",
"Côtes-de-Duras",
"Côtes-de-Montravel",
"Côtes-de-Provence",
"Côtes-de-Toul",
"Côtes-du-Forez",
"Côtes-du-Jura",
"Côtes-du-Marmandais",
"Côtes-du-Rhône",
"Côtes-du-Rhône Villages",
"Côtes-du-Rhône-Villages , Cairanne",
"Côtes-du-Rhône-Villages , Chusclan",
"Côtes-du-Rhône-Villages , Laudun",
"Côtes-du-Rhône-Villages , Massif D'Uchaux",
"Côtes-du-Rhône-Villages , Plan De Dieu",
"Côtes-du-Rhône-Villages , Puyméras",
"Côtes-du-Rhône-Villages , Roaix",
"Côtes-du-Rhône-Villages , Rochegude",
"Côtes-du-Rhône-Villages , Rousset-Les-Vignes",
"Côtes-du-Rhône-Villages , Sablet",
"Côtes-du-Rhône-Villages , Saint-Gervais",
"Côtes-du-Rhône-Villages , Saint-Maurice",
"Côtes-du-Rhône-Villages , Saint-Pantaléon-Les-Vignes",
"Côtes-du-Rhône-Villages , Séguret",
"Côtes-du-Rhône-Villages , Signargues",
"Côtes-du-Rhône-Villages , Valréas",
"Côtes-du-Rhône-Villages , Visan",
"Côtes-du-Roussillon",
"Côtes-du-Roussillon Villages",
"Côtes-du-Vivarais",
"Cour-Cheverny",
"Crémant d'Alsace",
"Crémant de Bordeaux",
"Crémant de Bourgogne",
"Crémant de Die",
"Crémant de Limoux",
"Crémant de Loire",
"Crémant du Jura",
"Criots-Bâtard-Montrachet",
"Crozes-Hermitage Ou Crozes-Ermitage",
"Drôme IGP",
"Duché d'Uzès IGP",
"Échezeaux",
"Eichberg, Alsace Grand Cru",
"Engelberg, Alsace Grand Cru",
"Entraygues - le Fel",
"Entre-Deux-Mers",
"Estaing",
"Faugères",
"Fiefs-Vendéens",
"Fitou",
"Fixin",
"Fixin premier cru",
"Fixin premier cru Arvelets",
"Fixin premier cru Clos de la Perrière",
"Fixin premier cru Clos du Chapitre",
"Fixin premier cru Clos Napoléon",
"Fixin premier cru Hervelets",
"Fleurie",
"Florimont, Alsace Grand Cru",
"Franche-Comté IGP",
"Frankstein, Alsace Grand Cru",
"Froehn, Alsace Grand Cru",
"Fronsac",
"Fronton",
"Furstentum, Alsace Grand Cru",
"Gaillac",
"Gaillac-Premières-Côtes",
"Gard IGP",
"Geisberg, Alsace Grand Cru",
"Gers IGP",
"Gevrey-Chambertin",
"Gevrey-Chambertin premier cru",
"Gevrey-Chambertin premier cru Au Closeau",
"Gevrey-Chambertin premier cru Aux Combottes",
"Gevrey-Chambertin premier cru Bel Air",
"Gevrey-Chambertin premier cru Champeaux",
"Gevrey-Chambertin premier cru Champonnet",
"Gevrey-Chambertin premier cru Cherbaudes",
"Gevrey-Chambertin premier cru Clos des Varoilles",
"Gevrey-Chambertin premier cru Clos du Chapitre",
"Gevrey-Chambertin premier cru Clos Prieur",
"Gevrey-Chambertin premier cru Clos Saint-Jacques",
"Gevrey-Chambertin premier cru Combe au Moine",
"Gevrey-Chambertin premier cru Craipillot",
"Gevrey-Chambertin premier cru En Ergot",
"Gevrey-Chambertin premier cru Estournelles-Saint-Jacques",
"Gevrey-Chambertin premier cru Fonteny",
"Gevrey-Chambertin premier cru Issarts",
"Gevrey-Chambertin premier cru La Bossière",
"Gevrey-Chambertin premier cru La Perrière",
"Gevrey-Chambertin premier cru La Romanée",
"Gevrey-Chambertin premier cru Lavaut Saint-Jacques",
"Gevrey-Chambertin premier cru Les Cazetiers",
"Gevrey-Chambertin premier cru Les Corbeaux",
"Gevrey-Chambertin premier cru Les Goulots",
"Gevrey-Chambertin premier cru Petite Chapelle",
"Gevrey-Chambertin premier cru Petits Cazetiers",
"Gevrey-Chambertin premier cru Poissenot",
"Gigondas",
"Givry",
"Givry premier cru",
"Givry premier cru A Vigne Rouge",
"Givry premier cru Champ Nalot",
"Givry premier cru Clos Charlé",
"Givry premier cru Clos de la Baraude",
"Givry premier cru Clos du Cellier aux Moines",
"Givry premier cru Clos du Cras long",
"Givry premier cru Clos du Vernoy",
"Givry premier cru Clos Jus",
"Givry premier cru Clos Marceaux",
"Givry premier cru Clos Marole",
"Givry premier cru Clos Salomon",
"Givry premier cru Clos-Saint-Paul",
"Givry premier cru Clos-Saint-Pierre",
"Givry premier cru Crausot",
"Givry premier cru Crémillons",
"Givry premier cru En Choué",
"Givry premier cru En Veau",
"Givry premier cru La Brûlée",
"Givry premier cru La Grande Berge",
"Givry premier cru La Matrosse",
"Givry premier cru La Petite Berge",
"Givry premier cru La Plante",
"Givry premier cru Le Champ Lalot",
"Givry premier cru Le Médenchot",
"Givry premier cru Le Paradis",
"Givry premier cru Le Petit Prétan",
"Givry premier cru Le Pied de Chaume",
"Givry premier cru Le Pied du Clou",
"Givry premier cru Le Vernoy",
"Givry premier cru Le Vigron",
"Givry premier cru Les Bois Chevaux",
"Givry premier cru Les Bois Gautiers",
"Givry premier cru Les Combes",
"Givry premier cru Les Galaffres",
"Givry premier cru Les Grandes Vignes",
"Givry premier cru Les Grands Prétans",
"Givry premier cru Petit Marole",
"Givry premier cru Servoisine",
"Gloeckelberg, Alsace Grand Cru",
"Goldert, Alsace Grand Cru",
"Grands-Échezeaux",
"Graves",
"Graves-de-Vayres",
"Graves-Supérieures",
"Grignan-les-Adhémar",
"Griotte-Chambertin",
"Gros Plant du Pays Nantais",
"Hatschbourg, Alsace Grand Cru",
"Haute Vallée de L'Aude IGP",
"Haute Vallée de L'Orb IGP",
"Haute-Marne IGP",
"Hautes-Alpes IGP",
"Haute-Vienne IGP",
"Haut-Médoc",
"Haut-Montravel",
"Haut-Poitou",
"Hengst, Alsace Grand Cru",
"Hermitage Ou Ermitage",
"Ile de Beauté IGP",
"Irancy",
"Irouléguy",
"Isère IGP",
"Jasnières",
"Juliénas",
"Jurançon",
"Kaefferkopf, Alsace Grand Cru",
"Kanzlerberg, Alsace Grand Cru",
"Kastelberg, Alsace Grand Cru",
"Kessler, Alsace Grand Cru",
"Kirchberg De Barr, Alsace Grand Cru",
"Kirchberg De Ribeauvillé, Alsace Grand Cru",
"Kitterlé, Alsace Grand Cru",
"La Grande Rue",
"La Romanée",
"La Tâche",
"Ladoix",
"Ladoix Côte de Beaune",
"Ladoix premier cru",
"Ladoix premier cru Basses Mourottes",
"Ladoix premier cru Bois Roussot",
"Ladoix premier cru En Naget",
"Ladoix premier cru Hautes Mourottes",
"Ladoix premier cru La Corvée",
"Ladoix premier cru La Micaude",
"Ladoix premier cru Le Clou d'Orge",
"Ladoix premier cru Le Rognet et Corton",
"Ladoix premier cru Les Buis",
"Ladoix premier cru Les Grêchons et Foutrières",
"Ladoix premier cru Les Joyeuses",
"Lalande-de-Pomerol",
"Landes IGP",
"Languedoc",
"Languedoc, Grés de Montpellier",
"Languedoc, La Clape",
"Languedoc, La Méjanelle",
"Languedoc, Montpeyroux",
"Languedoc, Pézenas",
"Languedoc, Pic Saint-Loup",
"Languedoc, Picpoul de Pinet",
"Languedoc, Quatourze",
"Languedoc, Saint-Christol",
"Languedoc, Saint-Drézery",
"Languedoc, Saint-Georges-D'Orques",
"Languedoc, Saint-Saturnin",
"Languedoc, Terrasses Du Larzac",
"Languedoc, Vérargues",
"Languedoc,Cabrières",
"Latricières-Chambertin",
"Lavilledieu IGP",
"Le Pays Cathare IGP",
"Les-Baux-De-Provence",
"L'Étoile",
"Limoux",
"Lirac",
"Listrac-Médoc",
"Loupiac",
"Luberon",
"Lussac-Saint-Émilion",
"Mâcon",
"Mâcon Azé",
"Mâcon Bray",
"Mâcon Burgy",
"Mâcon Bussières",
"Mâcon Chaintré",
"Mâcon Chardonnay",
"Mâcon Charnay-lès-Mâcon",
"Mâcon Cruzille",
"Mâcon Davayé",
"Mâcon Fuissé",
"Mâcon Igé",
"Mâcon La Roche-Vineuse",
"Mâcon Loché",
"Mâcon Lugny",
"Mâcon Mancey",
"Mâcon Milly-Lamartine",
"Mâcon Montbellet",
"Mâcon Péronne",
"Mâcon Pierreclos",
"Mâcon Prissé",
"Mâcon Saint-Gengoux-le-National",
"Mâcon Serrières",
"Mâcon Solutré-Pouilly",
"Mâcon Uchizy",
"Mâcon Vergisson",
"Mâcon Verzé",
"Mâcon Vinzelles",
"Macvin du Jura",
"Madiran",
"Malepère",
"Mambourg, Alsace Grand Cru",
"Mandelberg, Alsace Grand Cru",
"Maranges",
"Maranges Côte de Beaune",
"Maranges premier cru",
"Maranges premier cru Clos de la Boutière",
"Maranges premier cru Clos de la Fussière",
"Maranges premier cru La Fussière",
"Maranges premier cru Le Clos des Loyères",
"Maranges premier cru Le Clos des Rois",
"Maranges premier cru Le Croix Moines",
"Maranges premier cru Les Clos Roussots",
"Marcillac",
"Marckrain, Alsace Grand Cru",
"Margaux",
"Marsannay",
"Maures IGP",
"Maury",
"Mazis-Chambertin",
"Mazoyères-Chambertin",
"Méditerranée IGP",
"Médoc",
"Menetou-Salon",
"Mercurey",
"Mercurey premier cru",
"Mercurey premier cru Clos de Paradis",
"Mercurey premier cru Clos des Barraults",
"Mercurey premier cru Clos des grands Voyens",
"Mercurey premier cru Clos des Myglands",
"Mercurey premier cru Clos Marcilly",
"Mercurey premier cru Clos Tonnerre",
"Mercurey premier cru Clos Voyens",
"Mercurey premier cru Grand Clos Fortoul",
"Mercurey premier cru Griffères",
"Mercurey premier cru La Bondue",
"Mercurey premier cru La Cailloute",
"Mercurey premier cru La Chassière",
"Mercurey premier cru La Levrière",
"Mercurey premier cru La Mission",
"Mercurey premier cru Le Clos du Roy",
"Mercurey premier cru Le Clos l'Evêque",
"Mercurey premier cru Les Byots",
"Mercurey premier cru Les Champs Martin",
"Mercurey premier cru Les Combins",
"Mercurey premier cru Les Crêts",
"Mercurey premier cru Les Croichots",
"Mercurey premier cru Les Fourneaux",
"Mercurey premier cru Les Montaigus",
"Mercurey premier cru Les Naugues",
"Mercurey premier cru Les Puillets",
"Mercurey premier cru Les Ruelles",
"Mercurey premier cru Les Saumonts",
"Mercurey premier cru Les Vasées",
"Mercurey premier cru Les Velley",
"Mercurey premier cru Sazenay",
"Meursault",
"Meursault Côte de Beaune",
"Meursault premier cru",
"Meursault premier cru Charmes",
"Meursault premier cru Clos des Perrières",
"Meursault premier cru Genevrières",
"Meursault premier cru La Jeunellotte",
"Meursault premier cru La Pièce sous le Bois",
"Meursault premier cru Le Porusot",
"Meursault premier cru Les Bouchères",
"Meursault premier cru Les Caillerets",
"Meursault premier cru Les Cras",
"Meursault premier cru Les Gouttes d'Or",
"Meursault premier cru Les Plures",
"Meursault premier cru Les Ravelles",
"Meursault premier cru Les Santenots Blancs",
"Meursault premier cru Les Santenots du Milieu",
"Meursault premier cru Perrières",
"Meursault premier cru Porusot",
"Meursault premier cru Sous Blagny",
"Meursault premier cru Sous le Dos d'Ane",
"Minervois",
"Minervois-La-Livinière",
"Moenchberg, Alsace Grand Cru",
"Monbazillac",
"Mont Caume IGP",
"Montagne-Saint-Émilion",
"Montagny",
"Montagny premier cru",
"Montagny premier cru Champ Toizeau",
"Montagny premier cru Chazelle",
"Montagny premier cru Cornevent",
"Montagny premier cru Creux de Beaux Champs",
"Montagny premier cru La Condemine du Vieux Château",
"Montagny premier cru La Grande Pièce",
"Montagny premier cru La Moullière",
"Montagny premier cru Le Clos Chaudron",
"Montagny premier cru Le Cloux",
"Montagny premier cru Le Clouzot",
"Montagny premier cru Le Vieux Château",
"Montagny premier cru L'Epaule",
"Montagny premier cru Les Bassets",
"Montagny premier cru Les Beaux Champs",
"Montagny premier cru Les Bonneveaux",
"Montagny premier cru Les Bordes",
"Montagny premier cru Les Bouchots",
"Montagny premier cru Les Burnins",
"Montagny premier cru Les Chaniots",
"Montagny premier cru Les Chaumelottes",
"Montagny premier cru Les Coères",
"Montagny premier cru Les Combes",
"Montagny premier cru Les Coudrettes",
"Montagny premier cru Les Craboulettes",
"Montagny premier cru Les Garchères",
"Montagny premier cru Les Gouresses",
"Montagny premier cru Les Jardins",
"Montagny premier cru Les Las",
"Montagny premier cru Les Macles",
"Montagny premier cru Les Maroques",
"Montagny premier cru Les Paquiers",
"Montagny premier cru Les Perrières",
"Montagny premier cru Les Pidances",
"Montagny premier cru Les Platières",
"Montagny premier cru Les Resses",
"Montagny premier cru Les Treuffères",
"Montagny premier cru Les Vignes Derrière",
"Montagny premier cru Les Vignes des Prés",
"Montagny premier cru Les Vignes longues",
"Montagny premier cru Mont Laurent",
"Montagny premier cru Montcuchot",
"Montagny premier cru Montorge",
"Montagny premier cru Sainte-Morille",
"Montagny premier cru Saint-Ytages",
"Montagny premier cru Sous les Feilles",
"Montagny premier cru Vigne du soleil",
"Montagny premier cru Vignes Couland",
"Montagny premier cru Vignes Saint-Pierre",
"Montagny premier cru Vignes sur le Cloux",
"Monthélie",
"Monthélie premier cru",
"Monthélie premier cru Clos des Toisières",
"Monthélie premier cru La Taupine",
"Monthélie premier cru Le Cas Rougeot",
"Monthélie premier cru Le Château Gaillard",
"Monthélie premier cru Le Clos Gauthey",
"Monthélie premier cru Le Clou des Chênes",
"Monthélie premier cru Le Meix Bataille",
"Monthélie premier cru Le Village",
"Monthélie premier cru Les Barbières",
"Monthélie premier cru Les Champs Fulliots",
"Monthélie premier cru Les Clous",
"Monthélie premier cru Les Duresses",
"Monthélie premier cru Les Riottes",
"Monthélie premier cru Les Vignes Rondes",
"Monthélie premier cru Sur la Velle",
"Montlouis-Sur-Loire",
"Montrachet",
"Montravel",
"Morey-Saint-Denis",
"Morey-Saint-Denis premier cru",
"Morey-Saint-Denis premier cru Aux Charmes",
"Morey-Saint-Denis premier cru Aux Cheseaux",
"Morey-Saint-Denis premier cru Clos Baulet",
"Morey-Saint-Denis premier cru Clos des Ormes",
"Morey-Saint-Denis premier cru Clos Sorbè",
"Morey-Saint-Denis premier cru Côte Rotie",
"Morey-Saint-Denis premier cru La Bussière",
"Morey-Saint-Denis premier cru La Riotte",
"Morey-Saint-Denis premier cru Le Village",
"Morey-Saint-Denis premier cru Les Blanchards",
"Morey-Saint-Denis premier cru Les Chaffots",
"Morey-Saint-Denis premier cru Les Charrières",
"Morey-Saint-Denis premier cru Les Chenevery",
"Morey-Saint-Denis premier cru Les Faconnières",
"Morey-Saint-Denis premier cru Les Genavrières",
"Morey-Saint-Denis premier cru Les Gruenchers",
"Morey-Saint-Denis premier cru Les Millandes",
"Morey-Saint-Denis premier cru Les Ruchots",
"Morey-Saint-Denis premier cru Les Sorbès",
"Morey-Saint-Denis premier cru Monts Luisants",
"Morgon",
"Moselle",
"Moulin-à-Vent",
"Moulis Ou Moulis-en-Médoc",
"Muenchberg, Alsace Grand Cru",
"Muscadet",
"Muscadet-Coteaux-de-la-Loire",
"Muscadet-Côtes-de-Grandlieu",
"Muscadet-Sèvre-et-Maine",
"Muscat de Beaumes-de-Venise",
"Muscat de Frontignan Ou Vin de Frontignan",
"Muscat de Lunel",
"Muscat de Mireval",
"Muscat de Rivesaltes",
"Muscat de Saint-Jean-de-Minervois",
"Muscat du Cap-Corse",
"Musigny",
"Néac",
"Nuits-Saint-Georges",
"Nuits-Saint-Georges premier cru",
"Nuits-Saint-Georges premier cru Aux Argillas",
"Nuits-Saint-Georges premier cru Aux Boudots",
"Nuits-Saint-Georges premier cru Aux Bousselots",
"Nuits-Saint-Georges premier cru Aux Chaignots",
"Nuits-Saint-Georges premier cru Aux Champs Perdrix",
"Nuits-Saint-Georges premier cru Aux Cras",
"Nuits-Saint-Georges premier cru Aux Murgers",
"Nuits-Saint-Georges premier cru Aux Perdrix",
"Nuits-Saint-Georges premier cru Aux Thorey",
"Nuits-Saint-Georges premier cru Aux Vignerondes",
"Nuits-Saint-Georges premier cru Chaines Carteaux",
"Nuits-Saint-Georges premier cru Château Gris",
"Nuits-Saint-Georges premier cru Clos Arlot",
"Nuits-Saint-Georges premier cru Clos de la Maréchale",
"Nuits-Saint-Georges premier cru Clos des Argillières",
"Nuits-Saint-Georges premier cru Clos des Corvées",
"Nuits-Saint-Georges premier cru Clos des Corvées Pagets",
"Nuits-Saint-Georges premier cru Clos des Forêts Saint-...",
"Nuits-Saint-Georges premier cru Clos des Grandes Vignes",
"Nuits-Saint-Georges premier cru Clos des Porrets-Saint...",
"Nuits-Saint-Georges premier cru Clos Saint-Marc",
"Nuits-Saint-Georges premier cru En la Perrière Noblot",
"Nuits-Saint-Georges premier cru La Richemone",
"Nuits-Saint-Georges premier cru Les Argillières",
"Nuits-Saint-Georges premier cru Les Cailles",
"Nuits-Saint-Georges premier cru Les Chabœufs",
"Nuits-Saint-Georges premier cru Les Crots",
"Nuits-Saint-Georges premier cru Les Damodes",
"Nuits-Saint-Georges premier cru Les Didiers",
"Nuits-Saint-Georges premier cru Les Hauts Pruliers",
"Nuits-Saint-Georges premier cru Les Perrières",
"Nuits-Saint-Georges premier cru Les Porrets-Saint-Georges",
"Nuits-Saint-Georges premier cru Les Poulettes",
"Nuits-Saint-Georges premier cru Les Procès",
"Nuits-Saint-Georges premier cru Les Pruliers",
"Nuits-Saint-Georges premier cru Les Saints-Georges",
"Nuits-Saint-Georges premier cru Les Terres Blanches",
"Nuits-Saint-Georges premier cru Les Vallerots",
"Nuits-Saint-Georges premier cru Les Vaucrains",
"Nuits-Saint-Georges premier cru Roncière",
"Nuits-Saint-Georges premier cru Rue de Chaux",
"Ollwiller, Alsace Grand Cru",
"Orléans",
"Orléans-Cléry",
"Osterberg, Alsace Grand Cru",
"Pacherenc-du-Vic-Bilh",
"Palette",
"Patrimonio",
"Pauillac",
"Pays d'Hérault IGP",
"Pays d'Oc IGP",
"Pécharmant",
"Périgord IGP",
"Périgord Vin de Domme IGP",
"Pernand-Vergelesses",
"Pernand-Vergelesses premier cru",
"Pernand-Vergelesses premier cru Clos Berthet",
"Pernand-Vergelesses premier cru Creux de la Net",
"Pernand-Vergelesses premier cru En Caradeux",
"Pernand-Vergelesses premier cru Ile des Vergelesses",
"Pernand-Vergelesses premier cru Les Fichots",
"Pernand-Vergelesses premier cru Sous Frétille",
"Pernand-Vergelesses premier cru Vergelesses",
"Pernand-Vergelesses premier cru Village de Pernand",
"Pessac-Léognan",
"Petit Chablis",
"Pfersigberg, Alsace Grand Cru",
"Pfingstberg, Alsace Grand Cru",
"Pierrevert",
"Pomerol",
"Pommard",
"Pommard premier cru",
"Pommard premier cru Clos Blanc",
"Pommard premier cru Clos de la Commaraine",
"Pommard premier cru Clos de Verger",
"Pommard premier cru Clos des Epeneaux",
"Pommard premier cru Derrière Saint-Jean",
"Pommard premier cru En Largillière",
"Pommard premier cru La Chanière",
"Pommard premier cru La Platière",
"Pommard premier cru La Refène",
"Pommard premier cru Le Clos Micot",
"Pommard premier cru Le Village",
"Pommard premier cru Les Arvelets",
"Pommard premier cru Les Bertins",
"Pommard premier cru Les Boucherottes",
"Pommard premier cru Les Chanlins-Bas",
"Pommard premier cru Les Chaponnières",
"Pommard premier cru Les Charmots",
"Pommard premier cru Les Combes Dessus",
"Pommard premier cru Les Croix Noires",
"Pommard premier cru Les Fremiers",
"Pommard premier cru Les Grands Epenots",
"Pommard premier cru Les Jarolières",
"Pommard premier cru Les Petits Epenots",
"Pommard premier cru Les Pézerolles",
"Pommard premier cru Les Poutures",
"Pommard premier cru Les Rugiens Bas",
"Pommard premier cru Les Rugiens Hauts",
"Pommard premier cru Les Saussilles",
"Pouilly-Fuissé",
"Pouilly-Fumé Ou Blanc-Fumé de Pouilly",
"Pouilly-Loché",
"Pouilly-sur-Loire",
"Pouilly-Vinzelles",
"Praelatenberg, Alsace Grand Cru",
"Premières-Côtes-de-Bordeaux",
"Puisseguin-Saint-Émilion",
"Puligny-Montrachet",
"Puligny-Montrachet Côte de Beaune",
"Puligny-Montrachet premier cru",
"Puligny-Montrachet premier cru Champ Canet",
"Puligny-Montrachet premier cru Champ Gain",
"Puligny-Montrachet premier cru Clavaillon",
"Puligny-Montrachet premier cru Clos de la Garenne",
"Puligny-Montrachet premier cru Clos de la Mouchère",
"Puligny-Montrachet premier cru Hameau de Blagny",
"Puligny-Montrachet premier cru La Garenne",
"Puligny-Montrachet premier cru La Truffière",
"Puligny-Montrachet premier cru Le Cailleret",
"Puligny-Montrachet premier cru Les Chalumaux",
"Puligny-Montrachet premier cru Les Combettes",
"Puligny-Montrachet premier cru Les Demoiselles",
"Puligny-Montrachet premier cru Les Folatières",
"Puligny-Montrachet premier cru Les Perrières",
"Puligny-Montrachet premier cru Les Pucelles",
"Puligny-Montrachet premier cru Les Referts",
"Puligny-Montrachet premier cru Sous le Puits",
"Puy-De-Dôme IGP",
"Quarts-de-Chaume",
"Quincy",
"Rangen, Alsace Grand Cru",
"Rasteau",
"Régnié",
"Reuilly",
"Richebourg",
"Rivesaltes",
"Romanée-Conti",
"Romanée-Saint-Vivant",
"Rosacker, Alsace Grand Cru",
"Rosé d'Anjou",
"Rosé de Loire",
"Rosé des Riceys",
"Rosette",
"Roussette de Savoie",
"Roussette du Bugey",
"Ruchottes-Chambertin",
"Rully",
"Rully premier cru",
"Rully premier cru Agneux",
"Rully premier cru Champs Cloux",
"Rully premier cru Chapitre",
"Rully premier cru Clos du Chaigne",
"Rully premier cru Clos St Jacques",
"Rully premier cru Cloux",
"Rully premier cru Grésigny",
"Rully premier cru La Bressande",
"Rully premier cru La Fosse",
"Rully premier cru La Pucelle",
"Rully premier cru La Renarde",
"Rully premier cru Le Meix Cadot",
"Rully premier cru Le Meix Caillet",
"Rully premier cru Les Pierres",
"Rully premier cru Margotés",
"Rully premier cru Marissou",
"Rully premier cru Molesme",
"Rully premier cru Montpalais",
"Rully premier cru Pillot",
"Rully premier cru Préaux",
"Rully premier cru Rabourcé",
"Rully premier cru Raclot",
"Rully premier cru Vauvry",
"Sable de Camargue IGP",
"Saering, Alsace Grand Cru",
"Saint-Amour",
"Saint-Aubin",
"Saint-Aubin Côte de Beaune",
"Saint-Aubin premier cru",
"Saint-Aubin premier cru Bas de Vermarain à l'Est",
"Saint-Aubin premier cru Derrière Chez Edouard",
"Saint-Aubin premier cru Derrière la Tour",
"Saint-Aubin premier cru Echaille",
"Saint-Aubin premier cru En Créot",
"Saint-Aubin premier cru En la Ranché",
"Saint-Aubin premier cru En Montceau",
"Saint-Aubin premier cru En Remilly",
"Saint-Aubin premier cru En Vollon à l'Est",
"Saint-Aubin premier cru Es Champs",
"Saint-Aubin premier cru La Chatenière",
"Saint-Aubin premier cru Le Bas de Gamay à l'Est",
"Saint-Aubin premier cru Le Charmois",
"Saint-Aubin premier cru Le Puits",
"Saint-Aubin premier cru Les Castets",
"Saint-Aubin premier cru Les Champlots",
"Saint-Aubin premier cru Les Combes",
"Saint-Aubin premier cru Les Combes au Sud",
"Saint-Aubin premier cru Les Cortons",
"Saint-Aubin premier cru Les Frionnes",
"Saint-Aubin premier cru Les Murgers des dents de chien",
"Saint-Aubin premier cru Les Perrières",
"Saint-Aubin premier cru Les Travers de Marinot",
"Saint-Aubin premier cru Marinot",
"Saint-Aubin premier cru Pitangeret",
"Saint-Aubin premier cru Sous Roche Dumay",
"Saint-Aubin premier cru Sur Gamay",
"Saint-Aubin premier cru Sur le sentier du Clou",
"Saint-Aubin premier cru Vignes Moingeon",
"Saint-Aubin premier cru Village",
"Saint-Bris",
"Saint-Chinian",
"Sainte-Croix-du-Mont",
"Sainte-Foy-Bordeaux",
"Sainte-Marie-La-Blanche IGP",
"Saint-Émilion",
"Saint-Émilion Grand Cru",
"Saint-Estèphe",
"Saint-Georges-Saint-Émilion",
"Saint-Guilhem-le-Désert IGP",
"Saint-Joseph",
"Saint-Julien",
"Saint-Mont",
"Saint-Nicolas-de-Bourgueil",
"Saint-Péray",
"Saint-Pourçain",
"Saint-Romain",
"Saint-Romain Côte de Beaune",
"Saint-Véran",
"Sancerre",
"Santenay",
"Santenay Côte de Beaune",
"Santenay premier cru",
"Santenay premier cru Beauregard",
"Santenay premier cru Beaurepaire",
"Santenay premier cru Clos de Tavannes",
"Santenay premier cru Clos des Mouches",
"Santenay premier cru Clos Faubard",
"Santenay premier cru Clos Rousseau",
"Santenay premier cru Grand Clos Rousseau",
"Santenay premier cru La Comme",
"Santenay premier cru La Maladière",
"Santenay premier cru Les Gravières",
"Santenay premier cru Les Gravières-Clos de Tavannes",
"Santenay premier cru Passetemps",
"Saône-Et-Loire IGP",
"Saumur",
"Saumur-Champigny",
"Saussignac",
"Sauternes",
"Savennières",
"Savigny-lès-Beaune",
"Savigny-lès-Beaune Côte de Beaune",
"Savigny-lès-Beaune premier cru",
"Savigny-lès-Beaune premier cru Aux Clous",
"Savigny-lès-Beaune premier cru Aux Fourneaux",
"Savigny-lès-Beaune premier cru Aux Gravains",
"Savigny-lès-Beaune premier cru Aux Guettes",
"Savigny-lès-Beaune premier cru Aux Serpentières",
"Savigny-lès-Beaune premier cru Basses Vergelesses",
"Savigny-lès-Beaune premier cru Bataillère",
"Savigny-lès-Beaune premier cru Champ Chevrey",
"Savigny-lès-Beaune premier cru La Dominode",
"Savigny-lès-Beaune premier cru Les Charnières",
"Savigny-lès-Beaune premier cru Les Hauts Jarrons",
"Savigny-lès-Beaune premier cru Les Hauts Marconnets",
"Savigny-lès-Beaune premier cru Les Jarrons",
"Savigny-lès-Beaune premier cru Les Lavières",
"Savigny-lès-Beaune premier cru Les Marconnets",
"Savigny-lès-Beaune premier cru Les Narbantons",
"Savigny-lès-Beaune premier cru Les Peuillets",
"Savigny-lès-Beaune premier cru Les Rouvrettes",
"Savigny-lès-Beaune premier cru Les Talmettes",
"Savigny-lès-Beaune premier cru Les Vergelesses",
"Savigny-lès-Beaune premier cru Petits Godeaux",
"Savigny-lès-Beaune premier cru Redrescul",
"Schlossberg, Alsace Grand Cru",
"Schoenenbourg, Alsace Grand Cru",
"Seyssel",
"Sommerberg, Alsace Grand Cru",
"Sonnenglanz, Alsace Grand Cru",
"Spiegel, Alsace Grand Cru",
"Sporen, Alsace Grand Cru",
"Steinert, Alsace Grand Cru",
"Steingrubler, Alsace Grand Cru",
"Steinklotz, Alsace Grand Cru",
"Tavel",
"Thézac-Perricard IGP",
"Touraine",
"Touraine-Noble-Joué",
"Tursan",
"Urfé IGP",
"Vacqueyras",
"Val De Loire IGP",
"Valençay",
"Vallée Du Paradis IGP",
"Vallée Du Torgan IGP",
"Var IGP",
"Vaucluse IGP",
"Ventoux",
"Vicomté D'Aumelas IGP",
"Vin de Pays des Gaules",
"Vin de Savoie Ou Savoie",
"Vin de Savoie Ou Savoie, Abymes",
"Vin de Savoie Ou Savoie, Apremont",
"Vin de Savoie Ou Savoie, Arbin",
"Vin de Savoie Ou Savoie, Ayze",
"Vin de Savoie Ou Savoie, Charpignat",
"Vin de Savoie Ou Savoie, Chautagne",
"Vin de Savoie Ou Savoie, Chignin",
"Vin de Savoie Ou Savoie, Chignin-Bergeron Ou Bergeron",
"Vin de Savoie Ou Savoie, Cruet",
"Vin de Savoie Ou Savoie, Jongieux",
"Vin de Savoie Ou Savoie, Marignan",
"Vin de Savoie Ou Savoie, Marin",
"Vin de Savoie Ou Savoie, Montmélian",
"Vin de Savoie Ou Savoie, Ripaille",
"Vin de Savoie Ou Savoie, Sainte-Marie-D'Alloix",
"Vin de Savoie Ou Savoie, Saint-Jean-De-La-Porte",
"Vin de Savoie Ou Savoie, Saint-Jeoire-Prieuré ",
"Vin des Allobroges IGP",
"Vins de la Corrèze IGP",
"Vinsobres",
"Viré-Clessé",
"Volnay",
"Volnay premier cru",
"Volnay premier cru Carelle sous la Chapelle",
"Volnay premier cru Champans",
"Volnay premier cru Clos de la Barre",
"Volnay premier cru Clos de la Bousse-d'Or",
"Volnay premier cru Clos de la Cave des Ducs",
"Volnay premier cru Clos de la Chapelle",
"Volnay premier cru Clos de la Rougeotte",
"Volnay premier cru Clos de l'Audignac",
"Volnay premier cru Clos des 60 ouvrées",
"Volnay premier cru Clos des Chênes",
"Volnay premier cru Clos des Ducs",
"Volnay premier cru Clos du Château des Ducs",
"Volnay premier cru Clos du Verseuil",
"Volnay premier cru En Chevret",
"Volnay premier cru Fremiets",
"Volnay premier cru Fremiets - Clos de la Rougeotte",
"Volnay premier cru La Gigotte",
"Volnay premier cru Lassolle",
"Volnay premier cru Le Ronceret",
"Volnay premier cru Le Village",
"Volnay premier cru Les Angles",
"Volnay premier cru Les Brouillards",
"Volnay premier cru Les Caillerets",
"Volnay premier cru Les Lurets",
"Volnay premier cru Les Mitans",
"Volnay premier cru Pitures Dessus",
"Volnay premier cru Robardelle",
"Volnay premier cru Santenots",
"Volnay premier cru Taille Pieds",
"Vorbourg, Alsace Grand Cru",
"Vosne-Romanée",
"Vosne-Romanée premier cru",
"Vosne-Romanée premier cru Au-dessus des Malconsorts",
"Vosne-Romanée premier cru Aux Brulées",
"Vosne-Romanée premier cru Aux Malconsorts",
"Vosne-Romanée premier cru Aux Raignots",
"Vosne-Romanée premier cru Clos des Réas",
"Vosne-Romanée premier cru Cros Parentoux",
"Vosne-Romanée premier cru En Orveaux",
"Vosne-Romanée premier cru La Croix Rameau",
"Vosne-Romanée premier cru Les Beaux Monts",
"Vosne-Romanée premier cru Les Chaumes",
"Vosne-Romanée premier cru Les Gaudichots",
"Vosne-Romanée premier cru Les Petis Monts",
"Vosne-Romanée premier cru Les Rouges",
"Vosne-Romanée premier cru Les Suchots",
"Vougeot",
"Vougeot premier cru",
"Vougeot premier cru Clos de la Perrière",
"Vougeot premier cru Le Clos Blanc",
"Vougeot premier cru Les Crâs",
"Vougeot premier cru Les Petits Vougeots",
"Vouvray",
"Wiebelsberg, Alsace Grand Cru",
"Wineck-Schlossberg, Alsace Grand Cru",
"Winzenberg, Alsace Grand Cru",
"Yonne IGP",
"Zinnkoepflé, Alsace Grand Cru",
"Zotzenberg, Alsace Grand Cru"


               ];
               
array_fr[1] = [
"Sud-Ouest",
"Corse",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Provence",
"Provence",
"Provence",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"vallée de la Loire, Anjou",
"vallée de la Loire, Anjou",
"vallée de la Loire, Anjou",
"vallée de la Loire, Anjou",
"Jura",
"Jura",
"vallée du Rhône",
"Sud-Ouest",
"Sud-Ouest",
"Languedoc",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Provence",
"Languedoc-Roussillon, Roussillon",
"Languedoc-Roussillon, Roussillon",
"Bordeaux, Sauternais",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Beaujolais",
"Beaujolais",
"vallée du Rhône",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Provence",
"Sud-Ouest",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bordeaux",
"Bourgogne, côte de Nuits",
"vallée de la Loire",
"Bordeaux",
"Bordeaux",
"Provence",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"Bourgogne",
"vallée de la Loire",
"Bourgogne, côte chalonnaise",
"",
"Alsace",
"Beaujolais",
"Alsace",
"Sud-Ouest",
"Bugey",
"Bugey",
"Bugey",
"Bugey",
"Sud-Ouest",
"Languedoc",
"vallée de la Loire",
"vallée de la Loire",
"Bordeaux",
"Sud-Ouest",
"vallée de la Loire",
"Bordeaux",
"Provence",
"Bordeaux, Graves",
"vallée du Rhône",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, Basse-Bourgogne",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Champagne",
"Champagne",
"Champagne",
"Bourgogne, côte de Nuits",
"Cognac",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Jura",
"vallée du Rhône",
"vallée de la Loire",
"vallée du Rhône",
"vallée du Rhône",
"Beaujolais",
"Bourgogne, côte de Beaune",
"vallée de la Loire",
"vallée de la Loire",
"Beaujolais",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Languedoc",
"vallée du Rhône",
"vallée du Rhône",
"Languedoc",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"vallée du Rhône",
"Roussillon",
"Sud-Ouest",
"vallée du Rhône",
"vallée du Rhône",
"Languedoc",
"Languedoc",
"vallée du Rhône",
"Corse",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"vallée du Rhône",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Nuits",
"Roussillon",
"Bourgogne",
"vallée de la Loire, Vignoble nantais",
"Champagne",
"Sud-Ouest",
"Savoie",
"Bourgogne",
"Languedoc",
"Languedoc",
"Bourgogne",
"Languedoc",
"vallée du Rhône",
"vallée de la Loire",
"Languedoc",
"vallée du Rhône",
"Champagne",
"Provence",
"vallée du Rhône",
"vallée de la Loire",
"vallée de la Loire",
"vallée de la Loire",
"vallée de la Loire",
"vallée de la Loire",
"Lyonnais",
"vallée de la Loire",
"Provence",
"Beaujolais",
"vallée de la Loire",
"vallée du Rhône",
"Roussillon",
"vallée de la Loire",
"Sud-Ouest",
"vallée de la Loire",
"Lorraine",
"Sud-Ouest",
"Languedoc",
"Languedoc",
"Sud-Ouest",
"Sud-Ouest",
"Sud-Ouest",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Bordeaux",
"Sud-Ouest",
"Sud-Ouest",
"Provence",
"Lorraine",
"vallée de la Loire",
"Jura",
"Sud-Ouest",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"Roussillon",
"Roussillon",
"vallée du Rhône",
"vallée de la Loire",
"Alsace",
"Bordeaux",
"Bourgogne",
"vallée du Rhône",
"Languedoc",
"vallée de la Loire",
"Jura",
"Bourgogne, côte de Beaune",
"vallée du Rhône",
"vallée du Rhône",
"vallée du Rhône",
"Bourgogne, côte de Nuits",
"Alsace",
"Alsace",
"Sud-Ouest",
"Bordeaux",
"Sud-Ouest",
"Languedoc",
"vallée de la Loire, Vignoble nantais",
"Languedoc",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Beaujolais",
"Alsace",
"Jura",
"Alsace",
"Alsace",
"Bordeaux",
"Sud-Ouest",
"Alsace",
"Sud-Ouest",
"Sud-Ouest",
"vallée du Rhône",
"Alsace",
"Sud-Ouest",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"vallée du Rhône",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Alsace",
"Alsace",
"Bourgogne, côte de Nuits",
"Bordeaux, Graves",
"Bordeaux",
"Bordeaux, Graves",
"vallée du Rhône",
"Bourgogne, côte de Nuits",
"vallée de la Loire, Vignoble nantais",
"Alsace",
"Languedoc",
"Languedoc",
"Champagne",
"Provence",
"vallée de la Loire",
"Bordeaux, Médoc",
"Sud-Ouest",
"vallée de la Loire, Anjou-Touraine",
"Alsace",
"vallée du Rhône",
"Corse",
"Bourgogne, Basse-Bourgogne",
"Sud-Ouest",
"Savoie",
"vallée de la Loire",
"Beaujolais",
"Sud-Ouest",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bordeaux",
"Sud-Ouest",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Languedoc",
"Bourgogne, côte de Nuits",
"Sud-Ouest",
"Languedoc",
"Provence",
"Jura",
"Languedoc",
"vallée du Rhône",
"Bordeaux, Médoc",
"Bordeaux",
"vallée du Rhône",
"Bordeaux",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Bourgogne, Mâconnais",
"Jura",
"Sud-Ouest",
"Languedoc",
"Alsace",
"Alsace",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Alsace",
"Bordeaux, Médoc",
"Bourgogne, côte de Nuits",
"Provence",
"Roussillon",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Provence",
"Bordeaux, Médoc",
"vallée de la Loire",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Languedoc",
"Languedoc",
"Alsace",
"Sud-Ouest",
"Provence",
"Bordeaux",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"vallée de la Loire",
"Bourgogne, côte de Beaune",
"Sud-Ouest",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Beaujolais",
"Lorraine",
"Beaujolais",
"Bordeaux, Médoc",
"Alsace",
"vallée de la Loire, Vignoble nantais",
"vallée de la Loire, Vignoble nantais",
"vallée de la Loire, Vignoble nantais",
"vallée de la Loire, Vignoble nantais",
"vallée du Rhône",
"Languedoc",
"Languedoc",
"Languedoc",
"Roussillon",
"Languedoc",
"Corse",
"Bourgogne, côte de Nuits",
"Bordeaux",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Alsace",
"vallée de la Loire",
"vallée de la Loire",
"Alsace",
"Sud-Ouest",
"Provence",
"Corse",
"Bordeaux, Médoc",
"Languedoc",
"Languedoc",
"Sud-Ouest",
"Sud-Ouest",
"Sud-Ouest",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bordeaux, Graves",
"Bourgogne, Basse-Bourgogne",
"Alsace",
"Alsace",
"Provence",
"Bordeaux",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, Mâconnais",
"vallée de la Loire",
"Bourgogne, Mâconnais",
"vallée de la Loire",
"Bourgogne, Mâconnais",
"Alsace",
"Bordeaux",
"Bordeaux",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"vallée de la Loire",
"vallée de la Loire",
"vallée de la Loire",
"Alsace",
"vallée du Rhône",
"Beaujolais",
"vallée de la Loire",
"Bourgogne, côte de Nuits",
"Roussillon",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Alsace",
"vallée de la Loire",
"vallée de la Loire",
"Champagne",
"Sud-Ouest",
"Savoie",
"Bugey",
"Bourgogne, côte de Nuits",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"Bourgogne, côte chalonnaise",
"vallée du Rhône",
"Alsace",
"Beaujolais",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, Basse-Bourgogne",
"Languedoc",
"Bordeaux",
"Bordeaux",
"Bourgogne",
"Bordeaux",
"Bordeaux",
"Bordeaux, Médoc",
"Bordeaux",
"Languedoc",
"vallée du Rhône",
"Bordeaux, Médoc",
"Sud-Ouest",
"vallée de la Loire",
"vallée du Rhône",
"vallée de la Loire",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, Mâconnais",
"vallée de la Loire",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne",
"vallée de la Loire, Anjou",
"vallée de la Loire, Anjou",
"Sud-Ouest",
"Bordeaux, Sauternais",
"vallée de la Loire, Anjou",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Alsace",
"Alsace",
"Savoie et Bugey",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"Alsace",
"vallée du Rhône",
"Sud-Ouest",
"vallée de la Loire, Touraine",
"vallée de la Loire, Touraine",
"Sud-Ouest",
"vallée de la Loire",
"vallée du Rhône",
"vallée de la Loire",
"vallée de la Loire",
"Languedoc",
"Roussillon",
"Provence",
"vallée du Rhône",
"vallée du Rhône",
"Languedoc",
"Beaujolais",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Savoie",
"Sud-Ouest",
"vallée du Rhône",
"Bourgogne, Mâconnais",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Bourgogne, côte de Beaune",
"Alsace",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"Bourgogne, côte de Nuits",
"vallée de la Loire, Touraine",
"Alsace",
"Alsace",
"Alsace",
"Bourgogne",
"Alsace",
"Alsace"


        ];
                
             
                var accentMap = {
            "à": "a", "â": "a", "é": "e", "è": "e", "ê": "e", "ë": "e",
            "ï": "i", "î": "i", "ô": "o", "ö": "o", "û": "u", "ù": "u"
            };
         
                
                var normalize = function( term ) {
        		var ret = "";
			for ( var i = 0; i < term.length; i++ ) {
				ret += accentMap[ term.charAt(i) ] || term.charAt(i);
			}
			return ret;
		};
                

                 $("#id_country").change(function(){
                        $('#id_description').val('');
                        $('#id_region').val('');

                 });

    function split( val ) {
      return val.split( / \s*/ );
    }
    function extractLast( term ) {
      return split( term ).pop();
    }
    function extractFirst( term ) {
      return split( term ).shift();
    }
                
                $( "#id_appellation" )
                
                      // don't navigate away from the field on tab when selecting an item
                        .bind( "keydown", function( event ) {
                            if ( event.keyCode === $.ui.keyCode.TAB &&
                                $( this ).data( "ui-autocomplete" ).menu.active ) {
                            event.preventDefault();
                            }
                        })

                        .autocomplete({
			        minLength: 0,
                                source: function( request, response ) {
                                    
                                    
                                var matcher = new RegExp( $.ui.autocomplete.escapeRegex( extractLast(request.term) ), "i" );
                                var matcher2 = new RegExp( $.ui.autocomplete.escapeRegex( extractFirst(request.term) ), "i" );
                                var search_array = [];

                                if ($('#id_country').val() == "France") {
                                    search_array = array_fr[0];
                                }
                                if ($('#id_country').val() == "Spain") {
                                    search_array = array_es[0];
                                }
                                
                                if ($('#id_country').val() == "Italia") {
                                    search_array = array_it[0];
                                }
                                if ($('#id_country').val() == "United States") {
                                    
                                    search_array = array_us[0];
                                }


                                response( $.grep( search_array, function( value ) {
                                    value = value.truc || value.value || value;
                                    // multi search returns everything it finds
                                    // return matcher.test( value ) || matcher.test( normalize( value ) ) || matcher2.test( value ) || matcher2.test( normalize( value )) ;
                                    // last only, works well
                                    return matcher.test( value ) || matcher.test( normalize( value ) );
                                }) );
                                
                                                             
                                
                                },
                                // delegate back to autocomplete, but extract the last term
                                //response( $.ui.autocomplete.filter(
                                //    array_fr[0], extractLast( request.term ) ) );
                               // },
                                focus: function() {
                                 //prevent value inserted on focus
                                    return false;
                                },
                                select: function( event, ui ) {
                                //var terms = split( this.value );

                                // remove the current input
                                //terms.pop();
                                // add the selected item
                                //terms.push( ui.item.value );
                                // add placeholder to get the comma-and-space at the end
                                //terms.push( "" );
                                //this.value = terms.join( ", " );
                                this.value=ui.item.value;
                                return false;
                                },
                                close: function(event, ui) {
                            
                                $('#id_region').val('');
                                
                                if ($('#id_country').val() == "France") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_fr[0]);
                                $('#id_region').val($('#id_region').val() + array_fr[1][index]);
                                }
                                if ($('#id_country').val() == "Spain") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_es[0]);
                                $('#id_region').val($('#id_region').val() + array_es[1][index]);
                                }
                                if ($('#id_country').val() == "Italia") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_it[0]);
                                $('#id_region').val($('#id_region').val() + array_it[1][index]);
                                }
                                if ($('#id_country').val() == "United States") {
                                var returned = $('#id_appellation').val();
                                var index = jQuery.inArray(returned, array_us[0]);
                                $('#id_region').val($('#id_region').val() + array_us[1][index]);
                                }                                
                                
                            }
                            }
                            
                            
                        )
                        /*.data('autocomplete')._renderItem = function( ul, item ) {

        var srchTerm = $.trim(this.term).split(/\s+/).join ('|');

        var strNewLabel = item.label;

            regexp = new RegExp ('(' + srchTerm + ')', "ig");

            var strNewLabel = strNewLabel.replace(regexp,"<span style='font-weight:bold;color:Blue;'>$1</span>");

      return $( "<li></li>" )
          .data( "item.autocomplete", item )
          .append( "<a>" + strNewLabel + "</a>" )
          .appendTo( ul );

   }*/;
                            
                
	});       
        
    
    
    
 //validation
    
    jQuery.validator.messages.required = "";

        $("#id_wineform").validate({
    
            highlight: function(element, errorClass) {
                $(element).parent().css({
                    "border-radius":"0px"
                });
                $(element).parent().css({
                    "box-shadow":"0px 0px 10px #ff0000"
                });

       
            },
        
            unhighlight: function(element, errorClass) {
                $(element).parent().css({
                    "box-shadow":"none"
                });

        
            },
            invalidHandler: function(e, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    var message = errors == 1
                        ? 'You missed 1 field. It has been highlighted below'
                    : 'You missed ' + errors + ' fields.  They have been highlighted below';
                    alert(message);
                    //$("div.error span").html(message);
                    //$("div.error").show();
                    //$("div.validate_error_label label").css("color", "red");
                                                             

                } else {
                     alert("no errors found");

                    //$("div.error").hide();
                    //$("div.validate_error_label label").css("color", "black");

                }
            }
        });
        
    
    
        
  }
  
  

elgg.register_hook_handler('init', 'system', elgg.wine_edit.init);    
     
<?php if (FALSE) : ?></script><?php endif; ?>