<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php if (FALSE) : ?>
    <script type="text/javascript">
<?php endif; ?>
    
    elgg.provide('elgg.wine_filter');

    elgg.wine_filter.init = function() {
 
        $(".elgg-main").on('click','.elgg-pagination li a',function(e) {
            e.preventDefault();
            var url=$(this).attr('href');
            var data=$("#filter :input").serialize();
        
            elgg.action(url,{
                data:data,
                dataType :'json',
                success: function(json) { 
                    $(".elgg-list,.elgg-pagination").remove();
                    $('.filter_ajax').after(json.content); 
                    $('.wine_count').html(json.count);
                }
            
            });
        });  

        $("#filter").change(function(){
            var url=$(this).attr('action');
            var data=$("#filter :input").serialize();
       
            elgg.action(url,{
                data:data,
                dataType :'json',
                success: function(json) { 
                    $(".elgg-list,.elgg-pagination").remove();
                    $('.filter_ajax').after(json.content); 
                    $('.wine_count').html(json.count);
                   
                }
            
            });
        });
      
        var option;
        $("#filter_country").change(function() {
        
            $("#box_appellation" ).css("display","none");
            $("#select_appellation" ).prop('disabled',true); 
            $("#box_region" ).css("display","none");
            $("#select_region" ).prop('disabled',true);
            var pays=$(this).val();
            if(pays !="all" && (pays == "France" || pays !== "United States" || pays !=="Italy" || pays !=="Spain")){
             //   $("#box_region" ).css("display","none");
             //   $("#select_region" ).prop('disabled',true);
            //}else{
                option='<option value="all">'+elgg.echo('all')+'</option>'+eval("region_"+$(this).val().replace(/\s+/g, ''));
                $("#select_region" ).html(option).prop('disabled', false);
                $("#box_region" ).css("display","block");
            }
    
        });
    
        $("#select_region").change(function() {
        
            if($(this).val()=="all"){
                $("#box_appellation" ).css("display","none");
                $("#select_appellation" ).prop('disabled',true);
            }else{
              
                var option='<option value="all">'+elgg.echo('all')+'</option>';
                var obj_appellation=eval("appellation_"+$("#filter_country").val().replace(/\s+/g, ''));
                
                //parcours du l'object appellation: region construction d'un tableau d'appellation avec les index
                var found_appellation = Object.keys(obj_appellation).filter(function(key){
                    var expr= new RegExp($("#select_region").val(),"g");
                    return obj_appellation[key].match(expr);
                });
                if($("#filter_country").val()== "France"){
                    found_appellation.sort().push("Vin de Table","Vin de France");}else
                    {
                        found_appellation.sort();
                    }
                //Construction de la liste des options
                $.map(found_appellation, function( val, i ) {
                    option=option+'<option value="'+val+'">'+val+'</option>';
                });
            
                $("#select_appellation" ).html(option).prop('disabled', false);
                $("#box_appellation" ).css("display","block");     
            }
        
        
        });    
    }
  
    //Liste des Tableaux
    var region_France=
        '<option value="Alsace">Alsace</option>'+
        '<option value="Beaujolais">Beaujolais</option>'+
        '<option value="Bordeaux">Bordeaux</option>'+
        '<option value="Bordeaux, Graves">Bordeaux, Graves</option>'+
        '<option value="Bordeaux, Médoc">Bordeaux, Médoc</option>'+
        '<option value="Bordeaux, Sauternais">Bordeaux, Sauternais</option>'+
        '<option value="Bourgogne">Bourgogne</option>'+
        '<option value="Bourgogne, Basse-Bourgogne">Bourgogne, Basse-Bourgogne</option>'+
        '<option value="Bourgogne, côte chalonnaise">Bourgogne, côte chalonnaise</option>'+
        '<option value="Bourgogne, côte de Beaune">Bourgogne, côte de Beaune</option>'+
        '<option value="Bourgogne, côte de Nuits">Bourgogne, côte de Nuits</option>'+
        '<option value="Bourgogne, Mâconnais">Bourgogne, Mâconnais</option>'+
        '<option value="Bugey">Bugey</option>'+
        '<option value="Champagne">Champagne</option>'+
        '<option value="Cognac">Cognac</option>'+
        '<option value="Corse">Corse</option>'+
        '<option value="Jura">Jura</option>'+
        '<option value="Languedoc">Languedoc</option>'+
        '<option value="Languedoc-Roussillon, Roussillon">Languedoc-Roussillon, Roussillon</option>'+
        '<option value="Lorraine">Lorraine</option>'+
        '<option value="Lyonnais">Lyonnais</option>'+
        '<option value="Provence">Provence</option>'+
        '<option value="Roussillon">Roussillon</option>'+
        '<option value="Savoie">Savoie</option>'+
        '<option value="Savoie et Bugey">Savoie et Bugey</option>'+
        '<option value="Sud-Ouest">Sud-Ouest</option>'+
        '<option value="vallée de la Loire">vallée de la Loire</option>'+
        '<option value="vallée de la Loire, Anjou">vallée de la Loire, Anjou</option>'+
        '<option value="vallée de la Loire, Anjou-Touraine">vallée de la Loire, Anjou-Touraine</option>'+
        '<option value="vallée de la Loire, Touraine">vallée de la Loire, Touraine</option>'+
        '<option value="vallée de la Loire, Vignoble nantais">vallée de la Loire, Vignoble nantais</option>'+
        '<option value="vallée du Rhône">vallée du Rhône</option>';


    var region_Italy=
        '<option value="Abruzzo">Abruzzo</option>'+
        '<option value="Basilicata">Basilicata</option>'+
        '<option value="Calabria">Calabria</option>'+
        '<option value="Campania">Campania</option>'+
        '<option value="Emilia-Romagna">Emilia-Romagna</option>'+
        '<option value="Friuli-Venezia Giulia">Friuli-Venezia Giulia</option>'+
        '<option value="Lazio">Lazio</option>'+
        '<option value="Liguria">Liguria</option>'+
        '<option value="Lombardia">Lombardia</option>'+
        '<option value="Molise">Molise</option>'+
        '<option value="Piemonte">Piemonte</option>'+
        '<option value="Puglia">Puglia</option>'+
        '<option value="Sardegna">Sardegna</option>'+
        '<option value="Sicilia">Sicilia</option>'+
        '<option value="Toscana">Toscana</option>'+
        '<option value="Trentino-Alto Adige">Trentino-Alto Adige</option>'+
        '<option value="Umbria">Umbria</option>'+
        '<option value="Valle d\'Aosta">Valle d\'Aosta</option>'+
        '<option value="Veneto">Veneto</option>';

    var region_UnitedStates=
        '<option value="California">California</option>'+
        '<option value="Caroline du Nord">Caroline du Nord</option>'+
        '<option value="Connecticut">Connecticut</option>'+
        '<option value="Connecticut">Connecticut</option>'+
        '<option value="Long Island">Long Island</option>'+
        '<option value="New Jersey">New Jersey</option>'+
        '<option value="New York">New York</option>'+
        '<option value="Oregon">Oregon</option>'+
        '<option value="Virginie">Virginie</option>'+
        '<option value="Washington">Washington</option>';



    var region_Spain=
        '<option value="Andalucía">Andalucía</option>'+
        '<option value="Aragón">Aragón</option>'+
        '<option value="Cantabria">Cantabria</option>'+
        '<option value="Castilla y León">Castilla y León</option>'+
        '<option value="Castilla-La Mancha">Castilla-La Mancha</option>'+
        '<option value="Cataluña">Cataluña</option>'+
        '<option value="Comunidad de Madrid">Comunidad de Madrid</option>'+
        '<option value="Comunidad Valenciana">Comunidad Valenciana</option>'+
        '<option value="Extremadura">Extremadura</option>'+
        '<option value="Galicia">Galicia</option>'+
        '<option value="Islas Canarias">Islas Canarias</option>'+
        '<option value="La Rioja">La Rioja</option>'+
        '<option value="Navarra">Navarra</option>'+
        '<option value="País Vasco">País Vasco</option>'+
        '<option value="Principado de Asturias">Principado de Asturias</option>'+
        '<option value="Provincia de Alicante">Provincia de Alicante</option>'+
        '<option value="Región de Murcia">Región de Murcia</option>';

  




    var appellation_France={"Alsace Grand Cru":"Alsace",
"Alsace Ou Vin D'Alsace":"Alsace",
"Crémant d'Alsace":"Alsace",
"Beaujolais":"Beaujolais",
"Beaujolais-Villages":"Beaujolais",
"Brouilly":"Beaujolais",
"Chénas":"Beaujolais",
"Chiroubles":"Beaujolais",
"Côte-de-Brouilly":"Beaujolais",
"Fleurie":"Beaujolais",
"Juliénas":"Beaujolais",
"Morgon":"Beaujolais",
"Moulin-à-Vent":"Beaujolais",
"Régnié":"Beaujolais",
"Saint-Amour":"Beaujolais",
"Vin de Pays des Gaules":"Beaujolais",
"Blaye":"Bordeaux",
"Bordeaux":"Bordeaux",
"Bordeaux Supérieur":"Bordeaux",
"Cadillac":"Bordeaux",
"Canon-Fronsac":"Bordeaux",
"Côtes-de-Blaye":"Bordeaux",
"Côtes-de-Bordeaux":"Bordeaux",
"Côtes-de-Bordeaux, Blaye":"Bordeaux",
"Côtes-de-Bordeaux, Cadillac":"Bordeaux",
"Côtes-de-Bordeaux, Castillon ":"Bordeaux",
"Côtes-de-Bordeaux, Francs":"Bordeaux",
"Côtes-de-Bordeaux-Saint-Macaire":"Bordeaux",
"Côtes-de-Bourg Ou Bourg Ou Bourgeais":"Bordeaux",
"Crémant de Bordeaux":"Bordeaux",
"Entre-Deux-Mers":"Bordeaux",
"Fronsac":"Bordeaux",
"Graves-de-Vayres":"Bordeaux",
"Lalande-de-Pomerol":"Bordeaux",
"Loupiac":"Bordeaux",
"Lussac-Saint-Émilion":"Bordeaux",
"Montagne-Saint-Émilion":"Bordeaux",
"Néac":"Bordeaux",
"Pomerol":"Bordeaux",
"Premières-Côtes-de-Bordeaux":"Bordeaux",
"Puisseguin-Saint-Émilion":"Bordeaux",
"Sainte-Croix-du-Mont":"Bordeaux",
"Sainte-Foy-Bordeaux":"Bordeaux",
"Saint-Émilion":"Bordeaux",
"Saint-Émilion Grand Cru":"Bordeaux",
"Saint-Georges-Saint-Émilion":"Bordeaux",
"Cérons":"Bordeaux, Graves",
"Graves":"Bordeaux, Graves",
"Graves-Supérieures":"Bordeaux, Graves",
"Pessac-Léognan":"Bordeaux, Graves",
"Haut-Médoc":"Bordeaux, Médoc",
"Listrac-Médoc":"Bordeaux, Médoc",
"Margaux":"Bordeaux, Médoc",
"Médoc":"Bordeaux, Médoc",
"Moulis Ou Moulis-en-Médoc":"Bordeaux, Médoc",
"Pauillac":"Bordeaux, Médoc",
"Saint-Estèphe":"Bordeaux, Médoc",
"Saint-Julien":"Bordeaux, Médoc",
"Barsac":"Bordeaux, Sauternais",
"Sauternes":"Bordeaux, Sauternais",
"Bourgogne":"Bourgogne",
"Bourgogne aligoté":"Bourgogne",
"Bourgogne Chitry":"Bourgogne",
"Bourgogne Côte Chalonnaise":"Bourgogne",
"Bourgogne Côte Saint-Jacques":"Bourgogne",
"Bourgogne Côtes d'Auxerre":"Bourgogne",
"Bourgogne Côtes du Couchois":"Bourgogne",
"Bourgogne Coulanges-la-Vineuse":"Bourgogne",
"Bourgogne Epineuil":"Bourgogne",
"Bourgogne Hautes Côtes de Beaune":"Bourgogne",
"Bourgogne Hautes Côtes de Nuits":"Bourgogne",
"Bourgogne La Chapelle Notre-Dame":"Bourgogne",
"Bourgogne Le Chapitre":"Bourgogne",
"Bourgogne Montrecul":"Bourgogne",
"Bourgogne mousseux":"Bourgogne",
"Bourgogne Passe-tout-grains":"Bourgogne",
"Bourgogne Tonnerre":"Bourgogne",
"Bourgogne Vézelay":"Bourgogne",
"Bourgogne-Ordinaire Ou Bourgogne Grand Ordinaire":"Bourgogne",
"Coteaux Bourguignons":"Bourgogne",
"Coteaux de L'Auxois IGP":"Bourgogne",
"Coteaux de Tannay IGP":"Bourgogne",
"Crémant de Bourgogne":"Bourgogne",
"Sainte-Marie-La-Blanche IGP":"Bourgogne",
"Saône-Et-Loire IGP":"Bourgogne",
"Yonne IGP":"Bourgogne",
"Chablis":"Bourgogne, Basse-Bourgogne",
"Chablis Grand Cru":"Bourgogne, Basse-Bourgogne",
"Chablis premier cru":"Bourgogne, Basse-Bourgogne",
"Irancy":"Bourgogne, Basse-Bourgogne",
"Petit Chablis":"Bourgogne, Basse-Bourgogne",
"Saint-Bris":"Bourgogne, Basse-Bourgogne",
"Bouzeron":"Bourgogne, côte chalonnaise",
"Givry":"Bourgogne, côte chalonnaise",
"Givry premier cru":"Bourgogne, côte chalonnaise",
"Mercurey":"Bourgogne, côte chalonnaise",
"Mercurey premier cru":"Bourgogne, côte chalonnaise",
"Montagny":"Bourgogne, côte chalonnaise",
"Montagny premier cru":"Bourgogne, côte chalonnaise",
"Rully":"Bourgogne, côte chalonnaise",
"Rully premier cru":"Bourgogne, côte chalonnaise",
"Aloxe-Corton":"Bourgogne, côte de Beaune",
"Aloxe-Corton premier cru":"Bourgogne, côte de Beaune",
"Auxey-Duresses":"Bourgogne, côte de Beaune",
"Auxey-Duresses Côte de Beaune":"Bourgogne, côte de Beaune",
"Auxey-Duresses premier cru":"Bourgogne, côte de Beaune",
"Bâtard-Montrachet":"Bourgogne, côte de Beaune",
"Beaune":"Bourgogne, côte de Beaune",
"Beaune premier cru":"Bourgogne, côte de Beaune",
"Bienvenues-Bâtard-Montrachet":"Bourgogne, côte de Beaune",
"Blagny":"Bourgogne, côte de Beaune",
"Blagny premier cru":"Bourgogne, côte de Beaune",
"Charlemagne":"Bourgogne, côte de Beaune",
"Chassagne-Montrachet":"Bourgogne, côte de Beaune",
"Chassagne-Montrachet premier cru":"Bourgogne, côte de Beaune",
"Chevalier-Montrachet":"Bourgogne, côte de Beaune",
"Chorey-lès-Beaune":"Bourgogne, côte de Beaune",
"Chorey-lès-Beaune Côte de Beaune":"Bourgogne, côte de Beaune",
"Corton":"Bourgogne, côte de Beaune",
"Corton-Charlemagne":"Bourgogne, côte de Beaune",
"Côte de Beaune":"Bourgogne, côte de Beaune",
"Côte de Beaune-Villages":"Bourgogne, côte de Beaune",
"Criots-Bâtard-Montrachet":"Bourgogne, côte de Beaune",
"Ladoix":"Bourgogne, côte de Beaune",
"Ladoix Côte de Beaune":"Bourgogne, côte de Beaune",
"Ladoix premier cru":"Bourgogne, côte de Beaune",
"Maranges":"Bourgogne, côte de Beaune",
"Maranges Côte de Beaune":"Bourgogne, côte de Beaune",
"Maranges premier cru":"Bourgogne, côte de Beaune",
"Meursault":"Bourgogne, côte de Beaune",
"Meursault Côte de Beaune":"Bourgogne, côte de Beaune",
"Meursault premier cru":"Bourgogne, côte de Beaune",
"Monthélie":"Bourgogne, côte de Beaune",
"Monthélie premier cru":"Bourgogne, côte de Beaune",
"Montrachet":"Bourgogne, côte de Beaune",
"Pernand-Vergelesses":"Bourgogne, côte de Beaune",
"Pernand-Vergelesses premier cru":"Bourgogne, côte de Beaune",
"Pommard":"Bourgogne, côte de Beaune",
"Pommard premier cru":"Bourgogne, côte de Beaune",
"Puligny-Montrachet":"Bourgogne, côte de Beaune",
"Puligny-Montrachet premier cru":"Bourgogne, côte de Beaune",
"Saint-Aubin":"Bourgogne, côte de Beaune",
"Saint-Aubin premier cru":"Bourgogne, côte de Beaune",
"Saint-Romain":"Bourgogne, côte de Beaune",
"Saint-Romain Côte de Beaune":"Bourgogne, côte de Beaune",
"Santenay":"Bourgogne, côte de Beaune",
"Santenay Côte de Beaune":"Bourgogne, côte de Beaune",
"Santenay premier cru":"Bourgogne, côte de Beaune",
"Savigny-lès-Beaune":"Bourgogne, côte de Beaune",
"Savigny-lès-Beaune premier cru":"Bourgogne, côte de Beaune",
"Volnay":"Bourgogne, côte de Beaune",
"Volnay premier cru":"Bourgogne, côte de Beaune",
"Bonnes-Mares":"Bourgogne, côte de Nuits",
"Chambertin":"Bourgogne, côte de Nuits",
"Chambertin-Clos de Bèze":"Bourgogne, côte de Nuits",
"Chambolle-Musigny":"Bourgogne, côte de Nuits",
"Chambolle-Musigny premier cru":"Bourgogne, côte de Nuits",
"Chapelle-Chambertin":"Bourgogne, côte de Nuits",
"Charmes-Chambertin":"Bourgogne, côte de Nuits",
"Clos de la Roche":"Bourgogne, côte de Nuits",
"Clos de Tart":"Bourgogne, côte de Nuits",
"Clos de Vougeot Ou Clos-Vougeot":"Bourgogne, côte de Nuits",
"Clos des Lambrays":"Bourgogne, côte de Nuits",
"Clos Saint-Denis":"Bourgogne, côte de Nuits",
"Côte de Nuits-Villages":"Bourgogne, côte de Nuits",
"Échezeaux":"Bourgogne, côte de Nuits",
"Fixin":"Bourgogne, côte de Nuits",
"Fixin premier cru":"Bourgogne, côte de Nuits",
"Gevrey-Chambertin":"Bourgogne, côte de Nuits",
"Gevrey-Chambertin premier cru":"Bourgogne, côte de Nuits",
"Grands-Échezeaux":"Bourgogne, côte de Nuits",
"Griotte-Chambertin":"Bourgogne, côte de Nuits",
"La Grande Rue":"Bourgogne, côte de Nuits",
"La Romanée":"Bourgogne, côte de Nuits",
"La Tâche":"Bourgogne, côte de Nuits",
"Latricières-Chambertin":"Bourgogne, côte de Nuits",
"Marsannay":"Bourgogne, côte de Nuits",
"Mazis-Chambertin":"Bourgogne, côte de Nuits",
"Mazoyères-Chambertin":"Bourgogne, côte de Nuits",
"Morey-Saint-Denis":"Bourgogne, côte de Nuits",
"Morey-Saint-Denis premier cru":"Bourgogne, côte de Nuits",
"Musigny":"Bourgogne, côte de Nuits",
"Nuits-Saint-Georges":"Bourgogne, côte de Nuits",
"Nuits-Saint-Georges premier cru":"Bourgogne, côte de Nuits",
"Richebourg":"Bourgogne, côte de Nuits",
"Romanée-Conti":"Bourgogne, côte de Nuits",
"Romanée-Saint-Vivant":"Bourgogne, côte de Nuits",
"Ruchottes-Chambertin":"Bourgogne, côte de Nuits",
"Vosne-Romanée":"Bourgogne, côte de Nuits",
"Vosne-Romanée premier cru":"Bourgogne, côte de Nuits",
"Vougeot":"Bourgogne, côte de Nuits",
"Mâcon":"Bourgogne, Mâconnais",
"Mâcon Azé":"Bourgogne, Mâconnais",
"Mâcon Bray":"Bourgogne, Mâconnais",
"Mâcon Burgy":"Bourgogne, Mâconnais",
"Mâcon Bussières":"Bourgogne, Mâconnais",
"Mâcon Chaintré":"Bourgogne, Mâconnais",
"Mâcon Chardonnay":"Bourgogne, Mâconnais",
"Mâcon Charnay-lès-Mâcon":"Bourgogne, Mâconnais",
"Mâcon Cruzille":"Bourgogne, Mâconnais",
"Mâcon Davayé":"Bourgogne, Mâconnais",
"Mâcon Fuissé":"Bourgogne, Mâconnais",
"Mâcon Igé":"Bourgogne, Mâconnais",
"Mâcon La Roche-Vineuse":"Bourgogne, Mâconnais",
"Mâcon Loché":"Bourgogne, Mâconnais",
"Mâcon Lugny":"Bourgogne, Mâconnais",
"Mâcon Mancey":"Bourgogne, Mâconnais",
"Mâcon Milly-Lamartine":"Bourgogne, Mâconnais",
"Mâcon Montbellet":"Bourgogne, Mâconnais",
"Mâcon Péronne":"Bourgogne, Mâconnais",
"Mâcon Pierreclos":"Bourgogne, Mâconnais",
"Mâcon Prissé":"Bourgogne, Mâconnais",
"Mâcon Saint-Gengoux-le-National":"Bourgogne, Mâconnais",
"Mâcon Serrières":"Bourgogne, Mâconnais",
"Mâcon Solutré-Pouilly":"Bourgogne, Mâconnais",
"Mâcon Uchizy":"Bourgogne, Mâconnais",
"Mâcon Vergisson":"Bourgogne, Mâconnais",
"Mâcon Verzé":"Bourgogne, Mâconnais",
"Mâcon Vinzelles":"Bourgogne, Mâconnais",
"Pouilly-Fuissé":"Bourgogne, Mâconnais",
"Pouilly-Loché":"Bourgogne, Mâconnais",
"Pouilly-Vinzelles":"Bourgogne, Mâconnais",
"Saint-Véran":"Bourgogne, Mâconnais",
"Viré-Clessé":"Bourgogne, Mâconnais",
"Bugey":"Bugey",
"Bugey, Manicle ":"Bugey",
"Bugey, Montagnieu":"Bugey",
"Bugey,Cerdon":"Bugey",
"Roussette du Bugey":"Bugey",
"Champagne":"Champagne",
"Champagne Grand Cru":"Champagne",
"Champagne premier cru":"Champagne",
"Coteaux de Coiffy  IGP":"Champagne",
"Coteaux-Champenois":"Champagne",
"Haute-Marne IGP":"Champagne",
"Rosé des Riceys":"Champagne",
"Charentais  IGP":"Cognac",
"Ajaccio":"Corse",
"Corse Ou Vin de Corse":"Corse",
"Ile de Beauté IGP":"Corse",
"Muscat du Cap-Corse":"Corse",
"Patrimonio":"Corse",
"Arbois":"Jura",
"Arbois Pupillin":"Jura",
"Château-Chalon":"Jura",
"Côtes-du-Jura":"Jura",
"Crémant du Jura":"Jura",
"Franche-Comté IGP":"Jura",
"L'Étoile":"Jura",
"Macvin du Jura":"Jura",
"Aude IGP":"Languedoc",
"Cabardès":"Languedoc",
"Cité de Carcassonne  IGP":"Languedoc",
"Clairette du Languedoc":"Languedoc",
"Corbières":"Languedoc",
"Corbières-Boutenac":"Languedoc",
"Coteaux de Narbonne IGP":"Languedoc",
"Coteaux de Peyriac IGP":"Languedoc",
"Coteaux d'Ensérune IGP":"Languedoc",
"Coteaux du Libron IGP":"Languedoc",
"Côtes de Thau IGP":"Languedoc",
"Côtes de Thongue IGP":"Languedoc",
"Crémant de Limoux":"Languedoc",
"Faugères":"Languedoc",
"Fitou":"Languedoc",
"Haute Vallée de L'Aude IGP":"Languedoc",
"Haute Vallée de L'Orb IGP":"Languedoc",
"Languedoc":"Languedoc",
"Languedoc, Grés de Montpellier":"Languedoc",
"Languedoc, La Clape":"Languedoc",
"Languedoc, La Méjanelle":"Languedoc",
"Languedoc, Montpeyroux":"Languedoc",
"Languedoc, Pézenas":"Languedoc",
"Languedoc, Pic Saint-Loup":"Languedoc",
"Languedoc, Picpoul de Pinet":"Languedoc",
"Languedoc, Quatourze":"Languedoc",
"Languedoc, Saint-Christol":"Languedoc",
"Languedoc, Saint-Drézery":"Languedoc",
"Languedoc, Saint-Georges-D'Orques":"Languedoc",
"Languedoc, Saint-Saturnin":"Languedoc",
"Languedoc, Terrasses Du Larzac":"Languedoc",
"Languedoc, Vérargues":"Languedoc",
"Languedoc,Cabrières":"Languedoc",
"Le Pays Cathare IGP":"Languedoc",
"Limoux":"Languedoc",
"Malepère":"Languedoc",
"Minervois":"Languedoc",
"Minervois-La-Livinière":"Languedoc",
"Muscat de Frontignan Ou Vin de Frontignan":"Languedoc",
"Muscat de Lunel":"Languedoc",
"Muscat de Mireval":"Languedoc",
"Muscat de Saint-Jean-de-Minervois":"Languedoc",
"Pays d'Hérault IGP":"Languedoc",
"Pays d'Oc IGP":"Languedoc",
"Saint-Chinian":"Languedoc",
"Saint-Guilhem-le-Désert IGP":"Languedoc",
"Vallée Du Paradis IGP":"Languedoc",
"Vicomté D'Aumelas IGP":"Languedoc",
"Banyuls":"Languedoc-Roussillon, Roussillon",
"Banyuls Grand Cru":"Languedoc-Roussillon, Roussillon",
"Côtes de Meuse IGP":"Lorraine",
"Côtes-de-Toul":"Lorraine",
"Moselle":"Lorraine",
"Coteaux-du-Lyonnais":"Lyonnais",
"Alpes-de-Haute-Provence IGP":"Provence",
"Alpes-Maritimes IGP":"Provence",
"Alpilles IGP":"Provence",
"Bandol":"Provence",
"Bellet Ou Vin de Bellet":"Provence",
"Bouches-Du-Rhône IGP":"Provence",
"Cassis":"Provence",
"Coteaux-d'Aix-en-Provence":"Provence",
"Coteaux-Varois-en-Provence":"Provence",
"Côtes-de-Provence":"Provence",
"Hautes-Alpes IGP":"Provence",
"Les-Baux-De-Provence":"Provence",
"Maures IGP":"Provence",
"Méditerranée IGP":"Provence",
"Mont Caume IGP":"Provence",
"Palette":"Provence",
"Pierrevert":"Provence",
"Var IGP":"Provence",
"Collioure":"Roussillon",
"Côte Vermeille  IGP":"Roussillon",
"Côtes Catalanes IGP":"Roussillon",
"Côtes-du-Roussillon":"Roussillon",
"Côtes-du-Roussillon Villages":"Roussillon",
"Maury":"Roussillon",
"Muscat de Rivesaltes":"Roussillon",
"Rivesaltes":"Roussillon",
"Vallée Du Torgan IGP":"Roussillon",
"Coteaux de L'Ain IGP":"Savoie",
"Isère IGP":"Savoie",
"Roussette de Savoie":"Savoie",
"Vin de Savoie Ou Savoie":"Savoie",
"Vin de Savoie Ou Savoie, Abymes":"Savoie",
"Vin de Savoie Ou Savoie, Apremont":"Savoie",
"Vin de Savoie Ou Savoie, Arbin":"Savoie",
"Vin de Savoie Ou Savoie, Ayze":"Savoie",
"Vin de Savoie Ou Savoie, Charpignat":"Savoie",
"Vin de Savoie Ou Savoie, Chautagne":"Savoie",
"Vin de Savoie Ou Savoie, Chignin":"Savoie",
"Vin de Savoie Ou Savoie, Chignin-Bergeron Ou Bergeron":"Savoie",
"Vin de Savoie Ou Savoie, Cruet":"Savoie",
"Vin de Savoie Ou Savoie, Jongieux":"Savoie",
"Vin de Savoie Ou Savoie, Marignan":"Savoie",
"Vin de Savoie Ou Savoie, Marin":"Savoie",
"Vin de Savoie Ou Savoie, Montmélian":"Savoie",
"Vin de Savoie Ou Savoie, Ripaille":"Savoie",
"Vin de Savoie Ou Savoie, Sainte-Marie-D'Alloix":"Savoie",
"Vin de Savoie Ou Savoie, Saint-Jean-De-La-Porte":"Savoie",
"Vin de Savoie Ou Savoie, Saint-Jeoire-Prieuré ":"Savoie",
"Vin des Allobroges IGP":"Savoie",
"Seyssel":"Savoie et Bugey",
"Agenais IGP":"Sud-Ouest",
"Ariège IGP":"Sud-Ouest",
"Armagnac":"Sud-Ouest",
"Atlantique IGP":"Sud-Ouest",
"Aveyron IGP":"Sud-Ouest",
"Béarn":"Sud-Ouest",
"Bergerac":"Sud-Ouest",
"Brulhois":"Sud-Ouest",
"Buzet":"Sud-Ouest",
"Cahors":"Sud-Ouest",
"Cognac":"Sud-Ouest",
"Comté Tolosan  IGP":"Sud-Ouest",
"Coteaux de Glanes IGP":"Sud-Ouest",
"Côtes de Gascogne IGP":"Sud-Ouest",
"Côtes de Millau":"Sud-Ouest",
"Côtes du Lot IGP":"Sud-Ouest",
"Côtes du Tarn IGP":"Sud-Ouest",
"Côtes-de-Bergerac":"Sud-Ouest",
"Côtes-de-Duras":"Sud-Ouest",
"Côtes-de-Montravel":"Sud-Ouest",
"Côtes-du-Marmandais":"Sud-Ouest",
"Entraygues - le Fel":"Sud-Ouest",
"Estaing":"Sud-Ouest",
"Fronton":"Sud-Ouest",
"Gaillac":"Sud-Ouest",
"Gaillac-Premières-Côtes":"Sud-Ouest",
"Gers IGP":"Sud-Ouest",
"Haut-Montravel":"Sud-Ouest",
"Irouléguy":"Sud-Ouest",
"Jurançon":"Sud-Ouest",
"Landes IGP":"Sud-Ouest",
"Lavilledieu IGP":"Sud-Ouest",
"Madiran":"Sud-Ouest",
"Marcillac":"Sud-Ouest",
"Monbazillac":"Sud-Ouest",
"Montravel":"Sud-Ouest",
"Pacherenc-du-Vic-Bilh":"Sud-Ouest",
"Pécharmant":"Sud-Ouest",
"Périgord IGP":"Sud-Ouest",
"Périgord Vin de Domme IGP":"Sud-Ouest",
"Rosette":"Sud-Ouest",
"Saint-Mont":"Sud-Ouest",
"Saussignac":"Sud-Ouest",
"Thézac-Perricard IGP":"Sud-Ouest",
"Tursan":"Sud-Ouest",
"Vins de la Corrèze IGP":"Sud-Ouest",
"Bonnezeaux":"vallée de la Loire",
"Bourgueil":"vallée de la Loire",
"Cabernet d'Anjou":"vallée de la Loire",
"Cabernet de Saumur":"vallée de la Loire",
"Calvados IGP":"vallée de la Loire",
"Châteaumeillant":"vallée de la Loire",
"Cheverny":"vallée de la Loire",
"Chinon":"vallée de la Loire",
"Coteaux du Cher et de L'Arnon IGP":"vallée de la Loire",
"Coteaux-de-l'Aubance":"vallée de la Loire",
"Coteaux-de-Saumur":"vallée de la Loire",
"Coteaux-du-Giennois":"vallée de la Loire",
"Coteaux-du-Layon":"vallée de la Loire",
"Coteaux-du-Loir":"vallée de la Loire",
"Coteaux-du-Vendômois":"vallée de la Loire",
"Côte-Roannaise":"vallée de la Loire",
"Côtes d'Auvergne":"vallée de la Loire",
"Côtes de la Charité IGP":"vallée de la Loire",
"Côtes-du-Forez":"vallée de la Loire",
"Cour-Cheverny":"vallée de la Loire",
"Crémant de Loire":"vallée de la Loire",
"Haute-Vienne IGP":"vallée de la Loire",
"Jasnières":"vallée de la Loire",
"Menetou-Salon":"vallée de la Loire",
"Montlouis-Sur-Loire":"vallée de la Loire",
"Orléans":"vallée de la Loire",
"Orléans-Cléry":"vallée de la Loire",
"Pouilly-Fumé Ou Blanc-Fumé de Pouilly":"vallée de la Loire",
"Pouilly-sur-Loire":"vallée de la Loire",
"Puy-De-Dôme IGP":"vallée de la Loire",
"Quarts-de-Chaume":"vallée de la Loire",
"Quincy":"vallée de la Loire",
"Reuilly":"vallée de la Loire",
"Rosé d'Anjou":"vallée de la Loire",
"Rosé de Loire":"vallée de la Loire",
"Saint-Nicolas-de-Bourgueil":"vallée de la Loire",
"Saint-Pourçain":"vallée de la Loire",
"Sancerre":"vallée de la Loire",
"Urfé IGP":"vallée de la Loire",
"Val De Loire IGP":"vallée de la Loire",
"Valençay":"vallée de la Loire",
"Anjou":"vallée de la Loire, Anjou",
"Anjou Villages":"vallée de la Loire, Anjou",
"Anjou Villages Brissac":"vallée de la Loire, Anjou",
"Anjou-Coteaux-De-La-Loire":"vallée de la Loire, Anjou",
"Saumur":"vallée de la Loire, Anjou",
"Saumur-Champigny":"vallée de la Loire, Anjou",
"Savennières":"vallée de la Loire, Anjou",
"Haut-Poitou":"vallée de la Loire, Anjou-Touraine",
"Touraine":"vallée de la Loire, Touraine",
"Touraine-Noble-Joué":"vallée de la Loire, Touraine",
"Vouvray":"vallée de la Loire, Touraine",
"Coteaux d'Ancenis":"vallée de la Loire, Vignoble nantais",
"Fiefs-Vendéens":"vallée de la Loire, Vignoble nantais",
"Gros Plant du Pays Nantais":"vallée de la Loire, Vignoble nantais",
"Muscadet":"vallée de la Loire, Vignoble nantais",
"Muscadet-Coteaux-de-la-Loire":"vallée de la Loire, Vignoble nantais",
"Muscadet-Côtes-de-Grandlieu":"vallée de la Loire, Vignoble nantais",
"Muscadet-Sèvre-et-Maine":"vallée de la Loire, Vignoble nantais",
"Ardèche IGP":"vallée du Rhône",
"Beaumes-De-Venise":"vallée du Rhône",
"Cévennes  IGP":"vallée du Rhône",
"Château-Grillet":"vallée du Rhône",
"Châteauneuf-du-Pape":"vallée du Rhône",
"Châtillon-en-Diois":"vallée du Rhône",
"Clairette de Bellegarde":"vallée du Rhône",
"Clairette de Die":"vallée du Rhône",
"Collines Rhodaniennes  IGP":"vallée du Rhône",
"Comtés Rhodaniens  IGP":"vallée du Rhône",
"Condrieu":"vallée du Rhône",
"Cornas":"vallée du Rhône",
"Costières-de-Nîmes":"vallée du Rhône",
"Coteaux des Baronnies IGP":"vallée du Rhône",
"Coteaux du Pont Du Gard IGP":"vallée du Rhône",
"Coteaux-de-Die":"vallée du Rhône",
"Côte-Rôtie":"vallée du Rhône",
"Côtes-du-Rhône":"vallée du Rhône",
"Côtes-du-Rhône Villages":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Cairanne":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Chusclan":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Laudun":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Massif D'Uchaux":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Plan De Dieu":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Puyméras":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Roaix":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Rochegude":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Rousset-Les-Vignes":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Sablet":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Saint-Gervais":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Saint-Maurice":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Saint-Pantaléon-Les-Vignes":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Séguret":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Signargues":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Valréas":"vallée du Rhône",
"Côtes-du-Rhône-Villages , Visan":"vallée du Rhône",
"Côtes-du-Vivarais":"vallée du Rhône",
"Crémant de Die":"vallée du Rhône",
"Crozes-Hermitage Ou Crozes-Ermitage":"vallée du Rhône",
"Drôme IGP":"vallée du Rhône",
"Duché d'Uzès IGP":"vallée du Rhône",
"Gard IGP":"vallée du Rhône",
"Gigondas":"vallée du Rhône",
"Grignan-les-Adhémar":"vallée du Rhône",
"Hermitage Ou Ermitage":"vallée du Rhône",
"Lirac":"vallée du Rhône",
"Luberon":"vallée du Rhône",
"Muscat de Beaumes-de-Venise":"vallée du Rhône",
"Rasteau":"vallée du Rhône",
"Sable de Camargue IGP":"vallée du Rhône",
"Saint-Joseph":"vallée du Rhône",
"Saint-Péray":"vallée du Rhône",
"Tavel":"vallée du Rhône",
"Vacqueyras":"vallée du Rhône",
"Vaucluse IGP":"vallée du Rhône",
"Ventoux":"vallée du Rhône",
"Vinsobres":"vallée du Rhône"}

    var appellation_Italy={"Abruzzo DOC":"Abruzzo",
"Alto Tirino IGT":"Abruzzo",
"Cerasuolo d'Abruzzo DOC":"Abruzzo",
"Colli Aprutini IGT":"Abruzzo",
"Colli del Sangro IGT":"Abruzzo",
"Colline Frentane IGT":"Abruzzo",
"Colline Pescaresi IGT":"Abruzzo",
"Colline Teatine IGT":"Abruzzo",
"Controguerra DOC":"Abruzzo",
"Del Vastese (o Histonium) IGT":"Abruzzo",
"Montepulciano d’Abruzzo DOC":"Abruzzo",
"Montepulciano d'Abruzzo Colline Teramane DOCG":"Abruzzo",
"Ortona DOC":"Abruzzo",
"Terre di Chieti IGT":"Abruzzo",
"Terre Tollesi (o Tullum) DOC":"Abruzzo",
"Trebbiano d’Abruzzo DOC":"Abruzzo",
"Valle Peligna IGT":"Abruzzo",
"Villamagna DOC":"Abruzzo",
"Aglianico del Vulture DOCG":"Basilicata",
"Aglianico del Vulture Superiore DOCG":"Basilicata",
"Basilicata IGT":"Basilicata",
"Matera DOC":"Basilicata",
"Terre dell'Alta Val d'Agri DOC":"Basilicata",
"Arghillà IGT":"Calabria",
"Bivongi DOC":"Calabria",
"Calabria IGT":"Calabria",
"Cirò DOC":"Calabria",
"Condoleo IGT":"Calabria",
"Costa Viola IGT":"Calabria",
"Donnici DOC":"Calabria",
"Esaro IGT":"Calabria",
"Greco di Bianco DOC":"Calabria",
"Lamezia DOC":"Calabria",
"Lipuda IGT":"Calabria",
"Locride IGT":"Calabria",
"Melissa DOC":"Calabria",
"Palizzi IGT":"Calabria",
"Pellaro IGT":"Calabria",
"Pollino DOC":"Calabria",
"San Vito di Luzzi DOC":"Calabria",
"Sant’Anna di Isola Capo Rizzuto DOC":"Calabria",
"Savuto DOC":"Calabria",
"Scavigna DOC":"Calabria",
"Scilla IGT":"Calabria",
"Val di Neto IGT":"Calabria",
"Valdamato IGT":"Calabria",
"Valle del Crati IGT":"Calabria",
"Verbicaro DOC":"Calabria",
"Aglianico del Taburno DOCG":"Campania",
"Aversa Asprinio (o Asprinio d'Aversa) DOC":"Campania",
"Aversa DOC":"Campania",
"Beneventano IGT":"Campania",
"Campania IGT":"Campania",
"Campi Flegrei DOC":"Campania",
"Capri DOC":"Campania",
"Castel San Lorenzo DOC":"Campania",
"Cilento DOC":"Campania",
"Colli di Salerno IGT":"Campania",
"Costa d’Amalfi DOC":"Campania",
"Dugenta IGT":"Campania",
"Epomeo IGT":"Campania",
"Falanghina del Sannio DOC":"Campania",
"Falerno del Massico DOC":"Campania",
"Fiano di Avellino DOCG":"Campania",
"Galluccio DOC":"Campania",
"Greco di Tufo DOCG":"Campania",
"Guardia Sanframondi (o Guardiolo) DOC":"Campania",
"Irpinia IGT":"Campania",
"Ischia DOC":"Campania",
"Paestum IGT":"Campania",
"Penisola Sorrentina DOC":"Campania",
"Pompeiano IGT":"Campania",
"Roccamonfina IGT":"Campania",
"Sannio DOC":"Campania",
"Sant’Agata de’ Goti DOC":"Campania",
"Solopaca DOC":"Campania",
"Taburno DOC":"Campania",
"Taurasi DOCG":"Campania",
"Terre del Volturno IGT":"Campania",
"Vesuvio DOC":"Campania",
"Albana di Romagna DOCG":"Emilia-Romagna",
"Bianco di Castelfranco Emilia IGT":"Emilia-Romagna",
"Bosco Eliceo DOC":"Emilia-Romagna",
"Cagnina di Romagna DOC":"Emilia-Romagna",
"Colli Bolognesi Classico Pignoletto DOCG":"Emilia-Romagna",
"Colli Bolognesi Colline di Oliveto DOC":"Emilia-Romagna",
"Colli Bolognesi Colline di Riosto DOC":"Emilia-Romagna",
"Colli Bolognesi Colline Marconiane DOC":"Emilia-Romagna",
"Colli Bolognesi DOC":"Emilia-Romagna",
"Colli Bolognesi Monte San Pietro DOC":"Emilia-Romagna",
"Colli Bolognesi Serravalle DOC":"Emilia-Romagna",
"Colli Bolognesi Zola Predosa DOC":"Emilia-Romagna",
"Colli di Faenza DOC":"Emilia-Romagna",
"Colli di Imola DOC":"Emilia-Romagna",
"Colli di Parma DOC":"Emilia-Romagna",
"Colli di Rimini DOC":"Emilia-Romagna",
"Colli di Scandiano e di Canossa DOC":"Emilia-Romagna",
"Colli Piacentini DOC":"Emilia-Romagna",
"Colli Piacentini Gutturnio DOC":"Emilia-Romagna",
"Colli Piacentini Monterosso Val d’Arda DOC":"Emilia-Romagna",
"Colli Piacentini Trebbianino Val Trebbia DOC":"Emilia-Romagna",
"Colli Romagna Centrale DOC":"Emilia-Romagna",
"Emilia (o dell’Emilia) IGT":"Emilia-Romagna",
"Fontana del Taro IGT":"Emilia-Romagna",
"Forlì IGT":"Emilia-Romagna",
"Gutturnio DOC":"Emilia-Romagna",
"Gutturnio Superiore DOC":"Emilia-Romagna",
"Lambrusco di Sorbara DOC":"Emilia-Romagna",
"Lambrusco Grasparossa di Castelvetro DOC":"Emilia-Romagna",
"Lambrusco Salamino di Santa Croce DOC":"Emilia-Romagna",
"Modena (o Provincia di Modena) IGT":"Emilia-Romagna",
"Ortrugo":"Emilia-Romagna",
"Pagadebit di Romagna Bertinoro DOC":"Emilia-Romagna",
"Pagadebit di Romagna DOC":"Emilia-Romagna",
"Ravenna IGT":"Emilia-Romagna",
"Reggiano DOC":"Emilia-Romagna",
"Reno DOC":"Emilia-Romagna",
"Romagna Albana Spumante DOC":"Emilia-Romagna",
"Rubicone IGT":"Emilia-Romagna",
"Sangiovese di Romagna DOC":"Emilia-Romagna",
"Sillaro or Bianco di Sillaro IGT":"Emilia-Romagna",
"Terre di Veleja IGT":"Emilia-Romagna",
"Trebbiano di Romagna DOC":"Emilia-Romagna",
"Val Tidone IGT":"Emilia-Romagna",
"Alto Livenza IGT":"Friuli-Venezia Giulia",
"Carso DOC":"Friuli-Venezia Giulia",
"Colli Orientali del Friuli  DOC":"Friuli-Venezia Giulia",
"Colli Orientali del Friuli Cialla DOC":"Friuli-Venezia Giulia",
"Colli Orientali del Friuli Picolit  DOCG":"Friuli-Venezia Giulia",
"Colli Orientali del Friuli Ramandolo DOC":"Friuli-Venezia Giulia",
"Colli Orientali del Friuli Rosazzo DOC":"Friuli-Venezia Giulia",
"Collio Goriziano (o Collio) DOC":"Friuli-Venezia Giulia",
"Friuli Annia DOC":"Friuli-Venezia Giulia",
"Friuli Aquileia DOC":"Friuli-Venezia Giulia",
"Friuli Grave DOC":"Friuli-Venezia Giulia",
"Friuli Isonzo DOC":"Friuli-Venezia Giulia",
"Friuli Latisana DOC":"Friuli-Venezia Giulia",
"Lison classico DOCG":"Friuli-Venezia Giulia",
"Lison-Pramaggiore DOC":"Friuli-Venezia Giulia",
"Ramandolo DOCG":"Friuli-Venezia Giulia",
"Rosazzo DOCG":"Friuli-Venezia Giulia",
"Venezia Giulia IGT":"Friuli-Venezia Giulia",
"Venezie (o delle Venezie) IGT":"Friuli-Venezia Giulia",
"Aleatico di Gradoli DOC":"Lazio",
"Aprilia DOC":"Lazio",
"Atina DOC":"Lazio",
"Bianco Capena DOC":"Lazio",
"Canellino di Frascati DOCG":"Lazio",
"Castelli Romani DOC":"Lazio",
"Cerveteri DOC":"Lazio",
"Cesanese del Piglio (o Piglio) DOCG":"Lazio",
"Cesanese di Affile (o Affile) DOC":"Lazio",
"Cesanese di Olevano Romano (o Olevano Romano) DOC":"Lazio",
"Circeo DOC":"Lazio",
"Civitella d’Agliano IGT":"Lazio",
"Colli Albani DOC":"Lazio",
"Colli Cimini IGT":"Lazio",
"Colli della Sabina DOC":"Lazio",
"Colli Etruschi Viterbesi DOC":"Lazio",
"Colli Lanuvini DOC":"Lazio",
"Cori DOC":"Lazio",
"Est! Est!! Est!!! di Montefiascone DOC":"Lazio",
"Frascati DOC":"Lazio",
"Frascati Superiore DOCG":"Lazio",
"Frusinante IGT":"Lazio",
"Genazzano DOC":"Lazio",
"Lazio IGT":"Lazio",
"Marino DOC":"Lazio",
"Montecompatri Colonna DOC":"Lazio",
"Nettuno IGT":"Lazio",
"Orvieto DOC":"Lazio",
"Roma":"Lazio",
"Tarquinia DOC":"Lazio",
"Terracina (o Moscato di Terracina) DOC":"Lazio",
"Velletri DOC":"Lazio",
"Vignanello DOC":"Lazio",
"Zagarolo DOC":"Lazio",
"Cinque Terre  DOC":"Liguria",
"Cinque Terre Costa da Posa DOC":"Liguria",
"Cinque Terre Costa de Campu DOC":"Liguria",
"Cinque Terre Costa de Sera DOC":"Liguria",
"Cinque Terre Sciacchetrà DOC":"Liguria",
"Colli di Luni DOC":"Liguria",
"Colline di Levanto DOC":"Liguria",
"Colline Savonesi IGT":"Liguria",
"Golfo del Tigullio DOC":"Liguria",
"Pornassio":"Liguria",
"Riviera Ligure di Ponente  DOC":"Liguria",
"Riviera Ligure di Ponente Albenga DOC":"Liguria",
"Riviera Ligure di Ponente Finale DOC":"Liguria",
"Riviera Ligure di Ponente Riviera dei Fiori DOC":"Liguria",
"Rossese di Dolceacqua (o Dolceacqua) DOC":"Liguria",
"Val Polcevera DOC":"Liguria",
"Alto Mincio IGT":"Lombardia",
"Benaco Bresciano IGT":"Lombardia",
"Bergamasca IGT":"Lombardia",
"Bonarda dell'Otrepo Pavese DOC":"Lombardia",
"Botticino DOC":"Lombardia",
"Buttafuoco dell'Oltrepo Pavese DOC":"Lombardia",
"Capriano del Colle DOC":"Lombardia",
"Casteggio DOC":"Lombardia",
"Cellatica DOC":"Lombardia",
"Collina del Milanese IGT":"Lombardia",
"Franciacorta DOCG":"Lombardia",
"Garda Bresciano DOC":"Lombardia",
"Garda Colli Mantovani":"Lombardia",
"Garda Colli Mantovani DOC":"Lombardia",
"Garda DOC":"Lombardia",
"Lambrusco Mantovano DOC":"Lombardia",
"Lugana DOCG":"Lombardia",
"Lugana Riserva DOCG":"Lombardia",
"Lugana spumante DOCG":"Lombardia",
"Lugana Superiore DOCG":"Lombardia",
"Lugana vendemmia tardiva DOCG":"Lombardia",
"Mantova (ou Provincia di Mantova) IGT":"Lombardia",
"Montenetto di Brescia IGT":"Lombardia",
"Moscato di Scanzo (o Scanzo) DOCG":"Lombardia",
"Oltrepò Pavese DOC":"Lombardia",
"Oltrepo Pavese Metodo Classico DOCG":"Lombardia",
"Pavia (o Provincia di Pavia) IGT":"Lombardia",
"Quistello IGT":"Lombardia",
"Riviera del Garda Bresciano DOC":"Lombardia",
"Ronchi di Brescia IGT":"Lombardia",
"Sabbioneta IGT":"Lombardia",
"San Colombano al Lambro DOC":"Lombardia",
"San Martino della Battaglia DOC":"Lombardia",
"Sebino IGT":"Lombardia",
"Sforzato di Valtellina (o Sfursat di Valtellina) DOCG":"Lombardia",
"Terrazze Retiche di Sondrio IGT":"Lombardia",
"Terre di Franciacorta DOC":"Lombardia",
"Valcalepio DOC":"Lombardia",
"Valtellina Superiore  DOCG":"Lombardia",
"Valtellina Superiore  Grumello DOCG":"Lombardia",
"Valtellina Superiore  Maroggia DOCG":"Lombardia",
"Valtellina Superiore Inferno DOCG":"Lombardia",
"Valtellina Superiore Sassella DOCG":"Lombardia",
"Valtellina Superiore Valgella DOCG":"Lombardia",
"Valtenesi DOC":"Lombardia",
"Bianchello del Metauro DOC":"Marche",
"Castelli di Jesi Verdicchio Classico Riserva DOCG":"Marche",
"Castelli di Jesi Verdicchio Riserva DOCG":"Marche",
"Colli Maceratesi DOC":"Marche",
"Colli Pesaresi DOC":"Marche",
"Conero DOCG":"Marche",
"Esino DOC":"Marche",
"Falerio dei Colli Ascolani DOC":"Marche",
"Lacrima di Morro d'Alba DOC":"Marche",
"Lacrima di Morro DOC":"Marche",
"Marche IGT":"Marche",
"Offida DOCG":"Marche",
"Pergola":"Marche",
"Rosso Conero DOC":"Marche",
"Rosso Piceno DOC":"Marche",
"Verdicchio dei Castelli di Jesi Classico DOC":"Marche",
"Verdicchio dei Castelli di Jesi DOC":"Marche",
"Verdicchio di Matelica DOCG":"Marche",
"Verdicchio di Matelica Riserva DOCG":"Marche",
"Vernaccia di Serrapetrona DOCG":"Marche",
"Biferno DOC":"Molise",
"Molise DOC":"Molise",
"Osco (o Terre degli Osci) IGT":"Molise",
"Pentro di Isernia DOC":"Molise",
"Rotae IGT":"Molise",
"Tintilia del Molise DOC":"Molise",
"Tintilia DOC":"Molise",
"Albugnano DOC":"Piemonte",
"Alta Langa DOCG":"Piemonte",
"Asti DOCG":"Piemonte",
"Asti Spumente DOCG":"Piemonte",
"Barbaresco DOCG":"Piemonte",
"Barbaresco Riserva DOCG":"Piemonte",
"Barbera d’Alba DOC":"Piemonte",
"Barbera d’Asti DOCG":"Piemonte",
"Barbera d’Asti Superior DOCG":"Piemonte",
"Barbera d’Asti Superior Tinella DOCG":"Piemonte",
"Barbera del Monferrato DOC":"Piemonte",
"Barbera del Monferrato Superiore DOCG":"Piemonte",
"Barolo Chinato DOCG":"Piemonte",
"Barolo DOCG":"Piemonte",
"Barolo Riserva DOCG":"Piemonte",
"Boca DOC":"Piemonte",
"Brachetto d'Acqui (o Acqui) DOCG":"Piemonte",
"Brachetto d'Acqui (o Acqui) spumente DOCG":"Piemonte",
"Bramaterra DOC":"Piemonte",
"Calosso DOC":"Piemonte",
"Canavese DOC":"Piemonte",
"Carema DOC":"Piemonte",
"Cisterna d'Asti DOC":"Piemonte",
"Colli Tortonesi DOC":"Piemonte",
"Collina Torinese DOC":"Piemonte",
"Colline Novaresi DOC":"Piemonte",
"Colline Saluzzesi DOC":"Piemonte",
"Colline Torinesi DOC":"Piemonte",
"Cortese dell’Alto Monferrato DOC":"Piemonte",
"Coste della Sesia DOC":"Piemonte",
"Dolcetto d’Acqui DOC":"Piemonte",
"Dolcetto d’Alba DOC":"Piemonte",
"Dolcetto d’Asti DOC":"Piemonte",
"Dolcetto di Diano d'Alba (o Diano d'Alba) DOCG":"Piemonte",
"Dolcetto di Diano d'Alba (o Diano d'Alba) Superiore DOCG":"Piemonte",
"Dolcetto di Dogliani DOC":"Piemonte",
"Dolcetto di Dogliani Superiore (o Dogliani) DOCG":"Piemonte",
"Dolcetto di Ovada DOC":"Piemonte",
"Dolcetto di Ovada Superiore (o Ovada) DOCG":"Piemonte",
"Erbaluce di Caluso (o Caluso)  DOCG":"Piemonte",
"Fara DOC":"Piemonte",
"Freisa d’Asti DOC":"Piemonte",
"Freisa di Chieri DOC":"Piemonte",
"Gabiano DOC":"Piemonte",
"Gattinara DOCG":"Piemonte",
"Gattinara Riserva DOCG":"Piemonte",
"Gavi (o Cortese di Gavi) DOCG":"Piemonte",
"Gavi (o Cortese di Gavi) Frizzante DOCG":"Piemonte",
"Gavi (o Cortese di Gavi) Spumante DOCG":"Piemonte",
"Ghemme DOCG":"Piemonte",
"Ghemme Riserva DOCG":"Piemonte",
"Grignolino d’Asti DOC":"Piemonte",
"Grignolino del Monferrato Casalese DOC":"Piemonte",
"Langhe DOC":"Piemonte",
"Lessona DOC":"Piemonte",
"Loazzolo DOC":"Piemonte",
"Malvasia di Casorzo d’Asti DOC":"Piemonte",
"Malvasia di Castelnuovo Don Bosco DOC":"Piemonte",
"Monferrato Casalese DOC":"Piemonte",
"Monferrato DOC":"Piemonte",
"Moscato d'Asti DOCG":"Piemonte",
"Nebbiolo d’Alba DOC":"Piemonte",
"Nizza DOCG":"Piemonte",
"Piemonte DOC":"Piemonte",
"Pinerolese DOC":"Piemonte",
"Roero Arneis DOCG":"Piemonte",
"Roero Arneis Spumante DOCG":"Piemonte",
"Roero DOCG":"Piemonte",
"Roero Superiore DOCG":"Piemonte",
"Rubino di Cantavenna DOC":"Piemonte",
"Ruchè di Castagnole Monferrato DOCG":"Piemonte",
"Sizzano DOC":"Piemonte",
"Valsusa DOC":"Piemonte",
"Verduno Pelaverga (o Verduno) DOC":"Piemonte",
"Aleatico di Puglia DOC":"Puglia",
"Alezio DOC":"Puglia",
"Brindisi DOC":"Puglia",
"Cacc’e mmitte di Lucera DOC":"Puglia",
"Castel del Monte Bombino Nero DOCG":"Puglia",
"Castel del Monte DOC":"Puglia",
"Castel del Monte Nero di Troia Reserva DOCG":"Puglia",
"Castel del Monte Rosso Riserva DOCG":"Puglia",
"Colline Joniche Taratine DOC":"Puglia",
"Copertino DOC":"Puglia",
"Daunia IGT":"Puglia",
"Galatina DOC":"Puglia",
"Gioia del Colle DOC":"Puglia",
"Gravina DOC":"Puglia",
"Leverano DOC":"Puglia",
"Martina (o Martina Franca) DOC":"Puglia",
"Matino DOC":"Puglia",
"Moscato di Trani DOC":"Puglia",
"Murgia IGT":"Puglia",
"Nardò DOC":"Puglia",
"Negroamaro di Terra d'Otranto DOC":"Puglia",
"Orta Nova DOC":"Puglia",
"Ostuni DOC":"Puglia",
"Primitivo di Manduria DOC":"Puglia",
"Primitivo di Manduria Dolce Naturale DOCG":"Puglia",
"Puglia IGT":"Puglia",
"Rosso Barletta DOC":"Puglia",
"Rosso Canosa DOC":"Puglia",
"Rosso di Cerignola DOC":"Puglia",
"Salento IGT":"Puglia",
"Salice Salentino DOC":"Puglia",
"San Severo DOC":"Puglia",
"Squinzano DOC":"Puglia",
"Tarantino IGT":"Puglia",
"Tavoliere delle Puglie DOC":"Puglia",
"Tavoliere DOC":"Puglia",
"Terra d'Otranto DOC":"Puglia",
"Valle d’Itria IGT":"Puglia",
"Alghero DOC":"Sardegna",
"Arborea DOC":"Sardegna",
"Barbagia IGT":"Sardegna",
"Camarro  IGT":"Sardegna",
"Campidano di Terralba DOC":"Sardegna",
"Cannonau di Sardegna  DOC":"Sardegna",
"Cannonau di Sardegna Capo Ferrato DOC":"Sardegna",
"Cannonau di Sardegna Jerzu DOC":"Sardegna",
"Cannonau di Sardegna Oliena (o Nepente di Oliena) DOC":"Sardegna",
"Carignano del Sulcis DOC":"Sardegna",
"Colli del Limbara  IGT":"Sardegna",
"Girò di Cagliari DOC":"Sardegna",
"Isola dei Nuraghi  IGT":"Sardegna",
"Malvasia di Bosa DOC":"Sardegna",
"Malvasia di Cagliari DOC":"Sardegna",
"Mandrolisai DOC":"Sardegna",
"Marmilla  IGT":"Sardegna",
"Monica di Cagliari DOC":"Sardegna",
"Monica di Sardegna DOC":"Sardegna",
"Moscato di Cagliari DOC":"Sardegna",
"Moscato di Sardegna DOC":"Sardegna",
"Moscato di Sardegna Gallura DOC":"Sardegna",
"Moscato di Sardegna Tempio Pausania DOC":"Sardegna",
"Moscato di Sorso Sennori DOC":"Sardegna",
"Nasco di Cagliari DOC":"Sardegna",
"Nuoro (o Provincia di Nuoro)  IGT":"Sardegna",
"Nuragus di Cagliari DOC":"Sardegna",
"Nurra IGT":"Sardegna",
"Ogliastra IGT":"Sardegna",
"Parteolla  IGT":"Sardegna",
"Planargia  IGT":"Sardegna",
"Romangia  IGT":"Sardegna",
"Sardegna Semidano DOC":"Sardegna",
"Sardegna Semidano Mogoro DOC":"Sardegna",
"Sibiola  IGT":"Sardegna",
"Tharros  IGT":"Sardegna",
"Trexenta  IGT":"Sardegna",
"Valle del Tirso  IGT":"Sardegna",
"Valli di Porto Pino  IGT":"Sardegna",
"Vermentino di Gallura DOCG":"Sardegna",
"Vermentino di Gallura Superior DOCG":"Sardegna",
"Vermentino di Sardegna DOC":"Sardegna",
"Vernaccia di Oristano DOC":"Sardegna",
"Alcamo DOC":"Sicilia",
"Cerasuolo di Vittoria Classico DOCG":"Sicilia",
"Cerasuolo di Vittoria DOCG":"Sicilia",
"Colli Ericini IGT":"Sicilia",
"Contea di Sclafani DOC":"Sicilia",
"Contessa Entellina DOC":"Sicilia",
"Delia Nivolelli DOC":"Sicilia",
"Delia Nivolelli Nero d'Avola DOC":"Sicilia",
"Eloro DOC":"Sicilia",
"Erice DOC":"Sicilia",
"Etna DOC":"Sicilia",
"Faro DOC":"Sicilia",
"Fontanarossa di Cerda IGT":"Sicilia",
"Mamertino di Milazzo DOC":"Sicilia",
"Marsala DOC":"Sicilia",
"Menfi DOC":"Sicilia",
"Monreale DOC":"Sicilia",
"Moscato di Noto DOC":"Sicilia",
"Moscato di Pantelleria DOC":"Sicilia",
"Moscato di Siracusa DOC":"Sicilia",
"Moscato Passito di Pantelleria DOC":"Sicilia",
"Noto DOC":"Sicilia",
"Riesi DOC":"Sicilia",
"Salaparuta DOC":"Sicilia",
"Salemi IGT":"Sicilia",
"Salina IGT":"Sicilia",
"Sambuca di Sicilia DOC":"Sicilia",
"Santa Margherita di Belice DOC":"Sicilia",
"Sciacca DOC":"Sicilia",
"Sicilia IGT":"Sicilia",
"Valle Belice IGT":"Sicilia",
"Aleatico dell'Elba (o Elba Aleatico) DOCG":"Toscana",
"Aleatico dell'Elba (o Elba Aleatico) passito DOCG":"Toscana",
"Alta Valle della Greve IGT":"Toscana",
"Ansonica Costa dell’Argentario DOC":"Toscana",
"Barco Reale di Carmignano DOC":"Toscana",
"Bianco dell’Empolese DOC":"Toscana",
"Bianco della Valdinievole DOC":"Toscana",
"Bianco di Pitigliano DOC":"Toscana",
"Bianco Pisano di San Torpè DOC":"Toscana",
"Bianco Vergine della Valdichiana DOC":"Toscana",
"Bolgheri  DOC":"Toscana",
"Bolgheri Sassicaia DOC":"Toscana",
"Brunello di Montalcino DOCG":"Toscana",
"Brunello di Montalcino Riserva DOCG":"Toscana",
"Candia dei Colli Apuani DOC":"Toscana",
"Capalbio DOC":"Toscana",
"Carmignano DOC":"Toscana",
"Carmignano Riserva DOCG":"Toscana",
"Chianti  DOCG":"Toscana",
"Chianti Classico DOCG":"Toscana",
"Chianti Colli Aretini DOCG":"Toscana",
"Chianti Colli Fiorentini DOCG":"Toscana",
"Chianti Colli Senesi DOCG":"Toscana",
"Chianti Colline Pisane DOCG":"Toscana",
"Chianti Montalbano DOCG":"Toscana",
"Chianti Montespertoli DOCG":"Toscana",
"Chianti Rùfina DOCG":"Toscana",
"Chianti Superiore DOCG":"Toscana",
"Colli dell’Etruria Centrale DOC":"Toscana",
"Colli della Toscana Centrale IGT":"Toscana",
"Colli dell'Etruria Centrale DOC":"Toscana",
"Colli di Luni DOC":"Toscana",
"Colline Lucchesi DOC":"Toscana",
"Cortona DOC":"Toscana",
"Elba DOC":"Toscana",
"Maremma Toscana IGT":"Toscana",
"Montecarlo DOC":"Toscana",
"Montecucco DOCG":"Toscana",
"Monteregio di Massa Marittima DOC":"Toscana",
"Montescudaio DOC":"Toscana",
"Morellino di Scansano DOCG":"Toscana",
"Moscadello di Montalcino DOC":"Toscana",
"Orcia":"Toscana",
"Parrina":"Toscana",
"Pomino":"Toscana",
"Rosso della Val di Cornia DOCG":"Toscana",
"Rosso di Montalcino":"Toscana",
"Rosso di Montepulciano":"Toscana",
"Sant'Antimo DOC":"Toscana",
"Sovana DOC":"Toscana",
"Suvereto DOCG":"Toscana",
"Toscana (o Toscano) IGT":"Toscana",
"Val d'Arbia DOC":"Toscana",
"Val di Cornia Rosso DOCG":"Toscana",
"Val di Magra IGT":"Toscana",
"Valdichiana Bianco Vergine DOC":"Toscana",
"Vernaccia di San Gimignano DOCG":"Toscana",
"Vernaccia di San Gimignano Riserva DOCG":"Toscana",
"Vin Santo del Chianti (o Vinsanto del Chianti) DOC":"Toscana",
"Vin Santo del Chianti Classico DOC":"Toscana",
"Vin Santo di Montepulciano DOC":"Toscana",
"Vino Nobile di Montepulciano DOCG":"Toscana",
"Vino Nobile di Montepulciano Riserva DOCG":"Toscana",
"Alto Adige Meranese di Collina  DOC":"Trentino-Alto Adige",
"Alto Adige Santa Maddalena  DOC":"Trentino-Alto Adige",
"Alto Adige Sottozona Colli di Bolzano  DOC":"Trentino-Alto Adige",
"Alto Adige Terlano  DOC":"Trentino-Alto Adige",
"Alto Adige Val Venosta  DOC":"Trentino-Alto Adige",
"Alto Adige Valle d’Isarco  DOC":"Trentino-Alto Adige",
"Alto Adige DOC":"Trentino-Alto Adige",
"Caldaro (o Lago di Caldaro) DOC":"Trentino-Alto Adige",
"Casteller DOC":"Trentino-Alto Adige",
"Mitterberg IGT":"Trentino-Alto Adige",
"Mitterberg tra Cauria e Tel  IGT":"Trentino-Alto Adige",
"Teroldego Rotaliano DOC":"Trentino-Alto Adige",
"Trentino DOC":"Trentino-Alto Adige",
"Trentino Sorni DOC":"Trentino-Alto Adige",
"Trento DOC":"Trentino-Alto Adige",
"Valdadige DOC":"Trentino-Alto Adige",
"Vallagarina IGT":"Trentino-Alto Adige",
"Venezie (o delle Venezie) IGT":"Trentino-Alto Adige",
"Vigneti delle Dolomiti IGT":"Trentino-Alto Adige",
"Allerona IGT":"Umbria",
"Assisi DOC":"Umbria",
"Bettona IGT":"Umbria",
"Cannara IGT":"Umbria",
"Colli Altotiberini DOC":"Umbria",
"Colli Amerini DOC":"Umbria",
"Colli del Trasimeno (ou Trasimeno) DOC":"Umbria",
"Colli Martani DOC":"Umbria",
"Colli Perugini DOC":"Umbria",
"Lago di Corbara DOC":"Umbria",
"Montefalco DOC":"Umbria",
"Montefalco Sagrantino DOCG":"Umbria",
"Montefalco Sagrantino passito DOCG":"Umbria",
"Narni IGT":"Umbria",
"Orvieto Classico DOC":"Umbria",
"Orvieto DOC":"Umbria",
"Rosso Orvietano (o Orvietano Rosso) DOC":"Umbria",
"Sagrantino di Montefalco DOCG":"Umbria",
"Sagrantino di Montefalco passito DOCG":"Umbria",
"Spello IGT":"Umbria",
"Spoleto DOC":"Umbria",
"Todi DOC":"Umbria",
"Torgiano DOC":"Umbria",
"Torgiano Rosso Riserva DOCG":"Umbria",
"Umbria IGT":"Umbria",
"Valle d'Aosta o Vallée d'Aoste DOC":"Valle d'Aosta",
"Alto Livenza IGT":"Veneto",
"Amarone della Valpolicella DOCG":"Veneto",
"Arcole DOC":"Veneto",
"Bagnoli di Sopra (o Bagnoli) Classico DOC":"Veneto",
"Bagnoli di Sopra (o Bagnoli) DOC":"Veneto",
"Bagnoli Friularo (o Friularo di Bagnoli) DOCG":"Veneto",
"Bardolino Classico DOC":"Veneto",
"Bardolino DOC":"Veneto",
"Bardolino Superiore  DOCG":"Veneto",
"Bardolino Superiore Classico DOCG":"Veneto",
"Bianco di Custoza DOC":"Veneto",
"Breganze DOC":"Veneto",
"Colli Asolani Prosecco (o Asolo-Prosecco) DOCG":"Veneto",
"Colli Berici DOC":"Veneto",
"Colli di Conegliano DOCG":"Veneto",
"Colli di Conegliano Torchiato di Fregona DOCG":"Veneto",
"Colli Euganei DOC":"Veneto",
"Colli Euganei Fior d'Arancio DOCG":"Veneto",
"Colli Trevigiani  IGT":"Veneto",
"Conegliano Valdobbiadene - Prosecco DOCG":"Veneto",
"Conselvano  IGT":"Veneto",
"Corti Benedettine del Padovano DOC":"Veneto",
"Fior d'Arancio Colli Euganei DOCG":"Veneto",
"Gambellara Classico DOC":"Veneto",
"Gambellara DOC":"Veneto",
"Garda DOC":"Veneto",
"Lessini Durello DOC":"Veneto",
"Lison classico DOCG":"Veneto",
"Lison DOCG":"Veneto",
"Lison-Pramaggiore DOC":"Veneto",
"Lugana DOCG":"Veneto",
"Marca Trevigiana  IGT":"Veneto",
"Merlara DOC":"Veneto",
"Montello e Colli Asolani DOC":"Veneto",
"Montello Rosso (o Montello) DOCG":"Veneto",
"Monti Lessini Durello DOC":"Veneto",
"Piave (o Vini del Piave) DOC":"Veneto",
"Piave Barbarigo Raboso DOC":"Veneto",
"Piave Malanotte DOCG":"Veneto",
"Prosecco di Conegliano Valdobbiadene DOC":"Veneto",
"Prosecco DOC":"Veneto",
"Recioto della Valpolicella Classico DOC":"Veneto",
"Recioto della Valpolicella DOCG":"Veneto",
"Recioto della Valpolicella Valpantena DOC":"Veneto",
"Recioto di Gambellara DOCG":"Veneto",
"Recioto di Soave Classico DOCG":"Veneto",
"Recioto di Soave DOCG":"Veneto",
"Recioto di Soave Spumante DOCG":"Veneto",
"Ripasso della Valpolicella DOC":"Veneto",
"Riviera del Brenta DOC":"Veneto",
"San Martino della Battaglia DOC":"Veneto",
"Soave Classico DOC":"Veneto",
"Soave DOC":"Veneto",
"Soave Superiore Classico DOCG":"Veneto",
"Soave Superiore DOCG":"Veneto",
"Soave Superiore Riserva DOCG":"Veneto",
"Valdadige DOC":"Veneto",
"Vallagarina IGT":"Veneto",
"Valpolicella Classico DOC":"Veneto",
"Valpolicella DOC":"Veneto",
"Valpolicella Ripasso DOC":"Veneto",
"Valpolicella Valpantena DOC":"Veneto",
"Veneto  IGT":"Veneto",
"Veneto Orientale  IGT":"Veneto",
"Venezia DOC":"Veneto",
"Venezie (o delle Venezie)  IGT":"Veneto",
"Veronese (o Provincia di Verona)  IGT":"Veneto",
"Vicenza DOC":"Veneto",
"Vigneti delle Dolomiti  IGT":"Veneto",
"Vin Santo di Gambellara DOC":"Veneto"

    }
 
    var appellation_Spain={"Altiplano de Sierra Nevada VdlT":"Andalucía",
        "Bailén VdlT":"Andalucía",
        "Cádiz VdlT":"Andalucía",
        "Condado de Huelva DO":"Andalucía",
        "Córdoba VdlT":"Andalucía",
        "Cumbres del Guadalfeo VdlT":"Andalucía",
        "Desierto de Almería VdlT":"Andalucía",
        "Granada VC":"Andalucía",
        "Jerez-Xérès-Sherry DO":"Andalucía",
        "Laderas del Genil VdlT":"Andalucía",
        "Laujar-Alpujarra VdlT":"Andalucía",
        "Lebrija VC":"Andalucía",
        "Los Palacios VdlT":"Andalucía",
        "Málaga DO":"Andalucía",
        "Manzanilla de Sanlúcar de Barrameda DO":"Andalucía",
        "Montilla-Moriles DO":"Andalucía",
        "Norte de Almería VdlT":"Andalucía",
        "Ribera del Andarax VdlT":"Andalucía",
        "Sierra Norte de Sevilla VdlT":"Andalucía",
        "Sierra Sur de Jaén VdlT":"Andalucía",
        "Sierras de Las Estancias y Los Filabres VdlT":"Andalucía",
        "Sierras de Málaga DO":"Andalucía",
        "Torreperogil VdlT":"Andalucía",
        "Villaviciosa de Córdoba VdlT":"Andalucía",
        "Vino Naranja del Condado de Huelva DO":"Andalucía",
        "Bajo Aragón VdlT":"Aragón",
        "Calatayud DO":"Aragón",
        "Campo de Borja DO":"Aragón",
        "Cariñena DO":"Aragón",
        "Ribera del Gállego-Cinco Villas VdlT":"Aragón",
        "Ribera del Jiloca VdlT":"Aragón",
        "Ribera del Queiles VdlT":"Aragón",
        "Somontano DO":"Aragón",
        "Valdejalón VdlT":"Aragón",
        "Valle del Cinca VdlT":"Aragón",
        "Costa de Cantabria VdlT":"Cantabria",
        "Liébana VdlT":"Cantabria",
        "Arlanza DO":"Castilla y León",
        "Arribes DO":"Castilla y León",
        "Bierzo DO":"Castilla y León",
        "Castilla y León VdlT":"Castilla y León",
        "Cigales DO":"Castilla y León",
        "Ribera del Duero DO":"Castilla y León",
        "Rueda DO":"Castilla y León",
        "Sierra de Salamanca VC":"Castilla y León",
        "Tierra de León DO":"Castilla y León",
        "Tierra del Vino de Zamora DO":"Castilla y León",
        "Toro DO":"Castilla y León",
        "Valles de Benavente VC":"Castilla y León",
        "Valtiendas VC":"Castilla y León",
        "Almansa DO":"Castilla-La Mancha",
        "Campo de la Guardia VP":"Castilla-La Mancha",
        "Casa del Blanco VP":"Castilla-La Mancha",
        "Castilla VdlT":"Castilla-La Mancha",
        "Dehesa del Carrizal VP":"Castilla-La Mancha",
        "Dominio de Valdepusa VP":"Castilla-La Mancha",
        "Finca Élez VP":"Castilla-La Mancha",
        "Gálvez VdlT":"Castilla-La Mancha",
        "Guijoso VP":"Castilla-La Mancha",
        "La Mancha DO":"Castilla-La Mancha",
        "Manchuela DO":"Castilla-La Mancha",
        "Méntrida DO":"Castilla-La Mancha",
        "Mondéjar DO":"Castilla-La Mancha",
        "Pago Calzadilla VP":"Castilla-La Mancha",
        "Pago Florentino VP":"Castilla-La Mancha",
        "Pozohondo VdlT":"Castilla-La Mancha",
        "Ribera del Júcar DO":"Castilla-La Mancha",
        "Sierra de Alcaraz VdlT":"Castilla-La Mancha",
        "Uclés DO":"Castilla-La Mancha",
        "Valdepeñas DO":"Castilla-La Mancha",
        "Alella DO":"Cataluña",
        "Ampurdán (o Empordà) DO":"Cataluña",
        "Cataluña DO":"Cataluña",
        "Cava DO":"Cataluña",
        "Conca de Barberá DO":"Cataluña",
        "Costers del Segre DO":"Cataluña",
        "Montsant DO":"Cataluña",
        "Penedés DO":"Cataluña",
        "Pla de Bages DO":"Cataluña",
        "Priorato DOC":"Cataluña",
        "Tarragona DO":"Cataluña",
        "Terra Alta DO":"Cataluña",
        "Vinos de Madrid DO":"Comunidad de Madrid",
        "Castelló VdlT":"Comunidad Valenciana",
        "El Terrerazo VdlT":"Comunidad Valenciana",
        "Utiel-Requena DO":"Comunidad Valenciana",
        "Valencia DO":"Comunidad Valenciana",
        "Extremadura VdlT":"Extremadura",
        "Ribera del Guadiana DO":"Extremadura",
        "Barbanza e Iria VdlT":"Galicia",
        "Betanzos VdlT":"Galicia",
        "Monterrei DO":"Galicia",
        "Rías Baixas DO":"Galicia",
        "Ribeira Sacra DO":"Galicia",
        "Ribeiro DO":"Galicia",
        "Valdeorras DO":"Galicia",
        "Valle del Miño-Orense VdlT":"Galicia",
        "Binissalem DO":"Islas Baleares",
        "Formentera  VdlT":"Islas Baleares",
        "Ibiza VdlT":"Islas Baleares",
        "Illes Balears  VdlT":"Islas Baleares",
        "Isla de Menorca  VdlT":"Islas Baleares",
        "Mallorca VdlT":"Islas Baleares",
        "Pla i Llevant DO":"Islas Baleares",
        "Serra de Tramuntana-Costa Nord VdlT":"Islas Baleares",
        "Abona DO":"Islas Canarias",
        "El Hierro DO":"Islas Canarias",
        "Gran Canaria DO":"Islas Canarias",
        "La Gomera DO":"Islas Canarias",
        "La Palma DO":"Islas Canarias",
        "Lanzarote DO":"Islas Canarias",
        "Tacoronte-Acentejo DO":"Islas Canarias",
        "Valle de Güímar DO":"Islas Canarias",
        "Valle de La Orotava DO":"Islas Canarias",
        "Ycoden-Daute-Isora DO":"Islas Canarias",
        "Rioja DOC":"La Rioja",
        "Valles de Sadacia VdlT":"La Rioja",
        "Navarra DO":"Navarra",
        "Otazu VP":"Navarra",
        "Pago de Arínzano VP":"Navarra",
        "Prado de Irache VP":"Navarra",
        "Tres Riberas VdlT":"Navarra",
        "Txakoli de Álava DO":"País Vasco",
        "Txakoli de Bizkaia DO":"País Vasco",
        "Txakoli de Getaria DO":"País Vasco",
        "Cangas VC":"Principado de Asturias",
        "Alicante DO":"Provincia de Alicante",
        "Abanilla VdlT":"Región de Murcia",
        "Bullas DO":"Región de Murcia",
        "Campo de Cartagena VdlT":"Región de Murcia",
        "Jumilla DO":"Región de Murcia",
        "Murcia VdlT":"Región de Murcia",
        "Yecla DO":"Región de Murcia"
    }

    var appellation_UnitedStates={"Alexander Valley":"California",
        "Alta Mesa":"California",
        "Anderson Valley":"California",
        "Arroyo Grande Valley":"California",
        "Arroyo Seco":"California",
        "Atlas Peak":"California",
        "Ben Lomond Mountain":"California",
        "Benmore Valley":"California",
        "Bennett Valley":"California",
        "Borden Ranch":"California",
        "California Shenandoah Valley":"California",
        "Capay Valley":"California",
        "Carmel Valley":"California",
        "Central Coast":"California",
        "Chalk Hill":"California",
        "Chalone":"California",
        "Chiles Valley":"California",
        "Cienega Valley":"California",
        "Clarksburg":"California",
        "Clear Lake":"California",
        "Clements Hills":"California",
        "Cole Ranch":"California",
        "Cosumnes River":"California",
        "Covelo":"California",
        "Cucamonga Valley":"California",
        "Diablo Grande":"California",
        "Diamond Mountain District":"California",
        "Dos Rios":"California",
        "Dry Creek Valley":"California",
        "Dunnigan Hills":"California",
        "Edna Valley":"California",
        "El Dorado":"California",
        "Fair Play":"California",
        "Fiddletown":"California",
        "Green Valley of Russian River Valley":"California",
        "Guenoc Valley":"California",
        "Hames Valley":"California",
        "High Valley":"California",
        "Howell Mountain":"California",
        "Jahant":"California",
        "Knights Valley":"California",
        "Lime Kiln Valley":"California",
        "Livermore Valley":"California",
        "Lodi":"California",
        "Los Carneros":"California",
        "Madera":"California",
        "Malibu-Newton Canyon":"California",
        "McDowell Valley":"California",
        "Mendocino":"California",
        "Mendocino Ridge":"California",
        "Merritt Island":"California",
        "Mokelumne River":"California",
        "Monterey":"California",
        "Mt. Harlan":"California",
        "Mt. Veeder":"California",
        "Napa Valley":"California",
        "North Coast":"California",
        "North Yuba":"California",
        "Northern Sonoma":"California",
        "Oak Knoll District":"California",
        "Oakville":"California",
        "Pacheco Pass":"California",
        "Paicines":"California",
        "Paso Robles":"California",
        "Potter Valley":"California",
        "Ramona Valley":"California",
        "Red Hills Lake County":"California",
        "Redwood Valley":"California",
        "River Junction":"California",
        "Rockpile":"California",
        "Russian River Valley":"California",
        "Rutherford":"California",
        "Saddle Rock - Malibu":"California",
        "Salado Creek":"California",
        "San Antonio Valley":"California",
        "San Benito":"California",
        "San Bernabe":"California",
        "San Francisco Bay":"California",
        "San Lucas":"California",
        "San Pasqual Valley":"California",
        "San Ysidro District":"California",
        "Santa Clara Valley":"California",
        "Santa Cruz Mountains":"California",
        "Santa Lucia Highlands":"California",
        "Santa Maria Valley":"California",
        "Santa Ynez Valley":"California",
        "Seiad Valley":"California",
        "Sierra Foothills":"California",
        "Sloughhouse":"California",
        "Solano County Green Valley":"California",
        "Sonoma Coast":"California",
        "Sonoma Mountain":"California",
        "Sonoma Valley":"California",
        "South Coast":"California",
        "Spring Mountain District":"California",
        "St. Helena":"California",
        "Sta. Rita Hills":"California",
        "Stags Leap District":"California",
        "Suisun Valley":"California",
        "Temecula Valley":"California",
        "Tracy Hills":"California",
        "Trinity Lakes":"California",
        "Wild Horse Valley":"California",
        "Willow Creek":"California",
        "York Mountain":"California",
        "Yorkville Highlands":"California",
        "Yountville":"California",
        "Yadkin Valley":"Caroline du Nord",
        "Southeastern New England":"Connecticut",
        "Western Connecticut Highlands":"Connecticut",
        "The Hamptons":"Long Island",
        "Catoctin":"Maryland",
        "Cumberland Valley":"Maryland",
        "Linganore":"Maryland",
        "Martha's Vineyard":"Massachusetts",
        "Central Delaware Valley":"New Jersey",
        "Outer Coastal Plain":"New Jersey",
        "Warren Hills":"New Jersey",
        "Cayuga Lake":"New York",
        "Finger Lakes":"New York",
        "Hudson River Region":"New York",
        "Lake Erie":"New York",
        "Long Island":"New York",
        "Niagara Escarpment":"New York",
        "North Fork of Long Island":"New York",
        "Seneca Lake":"New York",
        "Applegate Valley":"Oregon",
        "Chehalem Mountains":"Oregon",
        "Columbia Gorge":"Oregon",
        "Columbia Valley":"Oregon",
        "Dundee Hills":"Oregon",
        "Eola-Amity Hills":"Oregon",
        "McMinnville":"Oregon",
        "Red Hill Douglas County":"Oregon",
        "Ribbon Ridge":"Oregon",
        "Rogue Valley":"Oregon",
        "Southern Oregon":"Oregon",
        "Umpqua Valley":"Oregon",
        "Willamette Valley":"Oregon",
        "Yakima Valley":"Oregon",
        "Yamhill-Carlton District":"Oregon",
        "Lancaster Valley":"Pennsylvanie",
        "Monticello":"Virginie",
        "North Fork of Roanoke":"Virginie",
        "Northern Neck George Washington Birthplace":"Virginie",
        "Rocky Knob":"Virginie",
        "Shenandoah Valley":"Virginie",
        "Virginia's Eastern Shore":"Virginie",
        "Horse Heaven Hills":"Washington",
        "Puget Sound":"Washington",
        "Rattlesnake Hills":"Washington",
        "Red Mountain":"Washington",
        "Wahluke Slope":"Washington",
        "Walla Walla Valley":"Washington"}


    elgg.register_hook_handler('init', 'system', elgg.wine_filter.init);    
     
<?php if (FALSE) : ?></script><?php endif; ?>

